#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 17-Jun-2015 13:07
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub3, Sub4, Sub1(2), Sub2(2)
	ComplexType Sub30, Sub87, Sub88, Sub42, Sub50, Sub56, Sub68
	ComplexType Sub29, Sub57, Sub69, Sub43, Sub51, Sub55, Sub60
	ComplexType Sub49, Sub67, Sub71, Sub41, Sub45, Sub44, Sub47
	ComplexType Sub61, Sub59, Sub58, Sub73, Sub74, Sub78(2)
	ComplexType Sub40(2), Sub66(2), Sub46(2), Sub72(2), Sub70(2)
	ComplexType Sub75(2), Sub48(2), Sub62(2), Sub52(2), Sub53(2)
	ComplexType Sub65(2), Sub96(2), Sub64(2), Sub63(2), Sub76(2)
	ComplexType Sub77(2), Sub38(2), Sub37(2), Sub13(2)
	ComplexType Sub7(2,2), Sub19(2,2), Sub33(2,2), Sub20(2,2)
	ComplexType Sub21(2,2), Sub27(2,2,2), Sub31, Sub109, Sub32
	ComplexType Sub6(2,2), Sub28, pave2(2), pave3, pave4(Nbb)
	ComplexType pave5(Ncc), pave13(Ncc,2,2), pave14(Ncc,2)
	common /varXs/ Sub3, Sub4, Sub1, Sub2, Sub30, Sub87, Sub88
	common /varXs/ Sub42, Sub50, Sub56, Sub68, Sub29, Sub57
	common /varXs/ Sub69, Sub43, Sub51, Sub55, Sub60, Sub49
	common /varXs/ Sub67, Sub71, Sub41, Sub45, Sub44, Sub47
	common /varXs/ Sub61, Sub59, Sub58, Sub73, Sub74, Sub78
	common /varXs/ Sub40, Sub66, Sub46, Sub72, Sub70, Sub75
	common /varXs/ Sub48, Sub62, Sub52, Sub53, Sub65, Sub96
	common /varXs/ Sub64, Sub63, Sub76, Sub77, Sub38, Sub37
	common /varXs/ Sub13, Sub7, Sub19, Sub33, Sub20, Sub21
	common /varXs/ Sub27, Sub31, Sub109, Sub32, Sub6, Sub28
	common /varXs/ pave2, pave3, pave4, pave5, pave13, pave14

	ComplexType Sub101, Sub113(2), Sub114(2), Sub93, pave1(Nbb,2)
	ComplexType pave6(Ncc,2), pave7(Ncc,2), pave8(Ndd,2,2)
	ComplexType pave9(Ndd,2), pave10(Nbb), pave11(Ncc,2)
	ComplexType pave12(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub101, Sub113, Sub114, Sub93, pave1, pave6
	common /varXa/ pave7, pave8, pave9, pave10, pave11, pave12
	common /varXa/ S, T, U

	HelType F1, F2, F3, F7, F4, F5, F6, F8, Sub5
	HelType F12, F9, F11, F10, F15, F19, F16, F17, F13, F18, F14
	HelType Sub89, Sub99, Sub95, Sub92, Sub94, Sub98
	HelType Sub115(HelDim(2)), Sub116(HelDim(2))
	HelType Sub54(HelDim(2)), Sub79(HelDim(2))
	HelType Sub105(HelDim(2)), Sub106(HelDim(2))
	HelType Sub81(HelDim(2)), Sub80(HelDim(2)), Sub83(HelDim(2))
	HelType Sub82(HelDim(2)), Sub102(HelDim(2),2)
	HelType Sub103(HelDim(2),2), Sub36(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub104(HelDim(2),2)
	HelType Sub112(HelDim(2),2), Sub107(HelDim(2),2)
	HelType Sub86(HelDim(2),2), Sub97(HelDim(2),2)
	HelType Sub35(HelDim(2),2), Sub34(HelDim(2),2)
	HelType Sub39(HelDim(2),2), Sub91, Sub85, Sub90, Sub84
	HelType Sub110(HelDim(2),2), Sub111(HelDim(2),2)
	HelType Sub100(HelDim(2),2)
	common /varXh/ F1, F2, F3, F7, F4, F5, F6, F8, Sub5, F12, F9
	common /varXh/ F11, F10, F15, F19, F16, F17, F13, F18, F14
	common /varXh/ Sub89, Sub99, Sub95, Sub92, Sub94, Sub98
	common /varXh/ Sub115, Sub116, Sub54, Sub79, Sub105, Sub106
	common /varXh/ Sub81, Sub80, Sub83, Sub82, Sub102, Sub103
	common /varXh/ Sub36, Sub108, Sub104, Sub112, Sub107, Sub86
	common /varXh/ Sub97, Sub35, Sub34, Sub39, Sub91, Sub85
	common /varXh/ Sub90, Sub84, Sub110, Sub111, Sub100

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_x1x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
