#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 12-Jun-2015 9:32
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1(2), Sub2(2), Sub4, Sub5
	ComplexType Sub32, Sub88, Sub89, Sub48, Sub56, Sub67, Sub74
	ComplexType Sub31, Sub113, Sub68, Sub75, Sub49, Sub57, Sub66
	ComplexType Sub63, Sub55, Sub73, Sub77, Sub47, Sub51, Sub50
	ComplexType Sub53, Sub70, Sub64, Sub69, Sub79, Sub80
	ComplexType Sub84(2), Sub46(2), Sub72(2), Sub52(2), Sub78(2)
	ComplexType Sub76(2), Sub81(2), Sub54(2), Sub61(2), Sub58(2)
	ComplexType Sub59(2), Sub71(2), Sub104(2), Sub65(2)
	ComplexType Sub62(2), Sub82(2), Sub83(2), Sub43(2), Sub42(2)
	ComplexType Sub12(2), Sub7(2,2), Sub20(2,2), Sub38(2,2)
	ComplexType Sub86(2,2), Sub22(2,2), Sub23(2,2), Sub29(2,2,2)
	ComplexType Sub36, Sub33, Sub114, Sub112, Sub35, Sub34
	ComplexType Sub37, Sub119(2), Sub8(2,2), Sub30, Sub94
	ComplexType pave2(2), pave3, pave7(Nbb), pave8(Ncc)
	ComplexType pave10(Ncc,2), pave11(Ncc,2,2), pave12(Ncc,2)
	common /varXs/ Sub1, Sub2, Sub4, Sub5, Sub32, Sub88, Sub89
	common /varXs/ Sub48, Sub56, Sub67, Sub74, Sub31, Sub113
	common /varXs/ Sub68, Sub75, Sub49, Sub57, Sub66, Sub63
	common /varXs/ Sub55, Sub73, Sub77, Sub47, Sub51, Sub50
	common /varXs/ Sub53, Sub70, Sub64, Sub69, Sub79, Sub80
	common /varXs/ Sub84, Sub46, Sub72, Sub52, Sub78, Sub76
	common /varXs/ Sub81, Sub54, Sub61, Sub58, Sub59, Sub71
	common /varXs/ Sub104, Sub65, Sub62, Sub82, Sub83, Sub43
	common /varXs/ Sub42, Sub12, Sub7, Sub20, Sub38, Sub86
	common /varXs/ Sub22, Sub23, Sub29, Sub36, Sub33, Sub114
	common /varXs/ Sub112, Sub35, Sub34, Sub37, Sub119, Sub8
	common /varXs/ Sub30, Sub94, pave2, pave3, pave7, pave8
	common /varXs/ pave10, pave11, pave12

	ComplexType Sub107, Sub115(2), Sub116(2), Sub117(2)
	ComplexType Sub21(2,2), Sub124(2), Sub125(2), Sub101
	ComplexType pave1(Nbb,2), pave4(Ndd,2,2), pave5(Ndd,2)
	ComplexType pave6(Nbb), pave9(Ncc,2), pave13(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub107, Sub115, Sub116, Sub117, Sub21, Sub124
	common /varXa/ Sub125, Sub101, pave1, pave4, pave5, pave6
	common /varXa/ pave9, pave13, S, T, U

	HelType F1, F5, F6, F3, F2, F7, F8, F4, Sub6, Sub3
	HelType F12, F9, F10, F11, F15, F19, F16, F17, F13, F18, F14
	HelType Sub92, Sub91, Sub90, Sub102, Sub97, Sub99, Sub100
	HelType Sub127(HelDim(2)), Sub126(HelDim(2))
	HelType Sub60(HelDim(2)), Sub85(HelDim(2))
	HelType Sub118(HelDim(2)), Sub120(HelDim(2))
	HelType Sub98(HelDim(2)), Sub45(HelDim(2))
	HelType Sub109(HelDim(2),2), Sub110(HelDim(2),2)
	HelType Sub122(HelDim(2),2), Sub41(HelDim(2),2)
	HelType Sub87(HelDim(2),2), Sub93(HelDim(2),2)
	HelType Sub111(HelDim(2),2), Sub96(HelDim(2),2)
	HelType Sub105(HelDim(2),2), Sub40(HelDim(2),2)
	HelType Sub39(HelDim(2),2), Sub44(HelDim(2),2), Sub95
	HelType Sub103, Sub123(HelDim(2),2), Sub121(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub106(HelDim(2),2)
	common /varXh/ F1, F5, F6, F3, F2, F7, F8, F4, Sub6, Sub3
	common /varXh/ F12, F9, F10, F11, F15, F19, F16, F17, F13
	common /varXh/ F18, F14, Sub92, Sub91, Sub90, Sub102, Sub97
	common /varXh/ Sub99, Sub100, Sub127, Sub126, Sub60, Sub85
	common /varXh/ Sub118, Sub120, Sub98, Sub45, Sub109, Sub110
	common /varXh/ Sub122, Sub41, Sub87, Sub93, Sub111, Sub96
	common /varXh/ Sub105, Sub40, Sub39, Sub44, Sub95, Sub103
	common /varXh/ Sub123, Sub121, Sub108, Sub106

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_x1x1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
