#if 0
* renconst.h
* RC declarations
* generated by FormCalc 8.4 on 12-Jun-2015 9:33
#endif

        ComplexType dSB1, dCB1, dMino11, dMino21, dMUE1, dMWsq1, dMZsq1
        ComplexType dSW1, dTB1, dZAA1, dZAZ1, dZe1, dZH1, dZH2
        ComplexType dZZA1, dZZZ1, dAf1(4,3,3), dMChaOS1(2)
        ComplexType dMf1(4,1), dMNeu1(4,4), dMNeuOS1(4)
        ComplexType dMSfsq1(2,2,4,1), dMsq11Sf1(4,1), dMsq12Sf1(4,1)
        ComplexType dZbarfL1(12,4,4), dZbarfR1(12,4,4)
        ComplexType dZbarSf1(2,2,4,1), dZfL1(12,4,4), dZfR1(12,4,4)
        ComplexType dZNeu1(4), dZSf1(2,2,4,1), dZW1
        common /renconst/ dSB1, dCB1, dMino11, dMino21, dMUE1, dMWsq1
        common /renconst/ dMZsq1, dSW1, dTB1, dZAA1, dZAZ1, dZe1
        common /renconst/ dZH1, dZH2, dZZA1, dZZZ1, dAf1, dMChaOS1
        common /renconst/ dMf1, dMNeu1, dMNeuOS1, dMSfsq1, dMsq11Sf1
        common /renconst/ dMsq12Sf1, dZbarfL1, dZbarfR1, dZbarSf1
        common /renconst/ dZfL1, dZfR1, dZNeu1, dZSf1, dZW1


