#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 17-Jun-2015 12:36
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1, Sub2, Sub4(2), Sub5(2)
	ComplexType Sub31, Sub84, Sub85, Sub43, Sub61, Sub68, Sub74
	ComplexType Sub30, Sub69, Sub75, Sub44, Sub62, Sub60, Sub57
	ComplexType Sub73, Sub42, Sub47, Sub67, Sub64, Sub58, Sub63
	ComplexType Sub49, Sub50, Sub71, Sub70, Sub77, Sub66(2)
	ComplexType Sub56(2), Sub52(2), Sub53(2), Sub46(2), Sub41(2)
	ComplexType Sub48(2), Sub45(2), Sub51(2), Sub54(2), Sub55(2)
	ComplexType Sub76(2), Sub59(2), Sub65(2), Sub72(2), Sub93(2)
	ComplexType Sub78(2), Sub8(2), Sub38(2), Sub39(2), Sub6(2,2)
	ComplexType Sub34(2,2), Sub19(2,2), Sub21(2,2), Sub22(2,2)
	ComplexType Sub28(2,2,2), Sub32, Sub105, Sub33, Sub7(2,2)
	ComplexType Sub29, pave2(2), pave3, pave5(Nbb), pave6(Ncc)
	ComplexType pave13(Ncc,2,2)
	common /varXs/ Sub1, Sub2, Sub4, Sub5, Sub31, Sub84, Sub85
	common /varXs/ Sub43, Sub61, Sub68, Sub74, Sub30, Sub69
	common /varXs/ Sub75, Sub44, Sub62, Sub60, Sub57, Sub73
	common /varXs/ Sub42, Sub47, Sub67, Sub64, Sub58, Sub63
	common /varXs/ Sub49, Sub50, Sub71, Sub70, Sub77, Sub66
	common /varXs/ Sub56, Sub52, Sub53, Sub46, Sub41, Sub48
	common /varXs/ Sub45, Sub51, Sub54, Sub55, Sub76, Sub59
	common /varXs/ Sub65, Sub72, Sub93, Sub78, Sub8, Sub38
	common /varXs/ Sub39, Sub6, Sub34, Sub19, Sub21, Sub22
	common /varXs/ Sub28, Sub32, Sub105, Sub33, Sub7, Sub29
	common /varXs/ pave2, pave3, pave5, pave6, pave13

	ComplexType Sub102(2), Sub100(2), Sub20(2,2), Sub109(2)
	ComplexType Sub110(2), Sub91, pave1(Nbb,2), pave4(Nbb)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ndd,2,2)
	ComplexType pave10(Ndd,2), pave11(Ncc,2), pave12(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub102, Sub100, Sub20, Sub109, Sub110, Sub91
	common /varXa/ pave1, pave4, pave7, pave8, pave9, pave10
	common /varXa/ pave11, pave12, S, T, U

	HelType F9, F5, F3, F10, F4, F7, F6, F1, F2, F8, Sub3
	HelType F18, F14, F11, F17, F19, F12, F13, F21, F20, F22, F23
	HelType F15, F24, F16, F25, Sub86, Sub92, Sub94
	HelType Sub111(HelDim(2)), Sub112(HelDim(2))
	HelType Sub79(HelDim(2)), Sub80(HelDim(2)), Sub82(HelDim(2))
	HelType Sub81(HelDim(2)), Sub103(HelDim(2))
	HelType Sub97(HelDim(2),2), Sub37(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub98(HelDim(2),2)
	HelType Sub99(HelDim(2),2), Sub101(HelDim(2),2)
	HelType Sub83(HelDim(2),2), Sub35(HelDim(2),2)
	HelType Sub95(HelDim(2),2), Sub36(HelDim(2),2)
	HelType Sub40(HelDim(2),2), Sub89, Sub87, Sub90, Sub88
	HelType Sub107(HelDim(2),2), Sub104(HelDim(2),2)
	HelType Sub96(HelDim(2),2), Sub106(HelDim(2),2)
	common /varXh/ F9, F5, F3, F10, F4, F7, F6, F1, F2, F8, Sub3
	common /varXh/ F18, F14, F11, F17, F19, F12, F13, F21, F20
	common /varXh/ F22, F23, F15, F24, F16, F25, Sub86, Sub92
	common /varXh/ Sub94, Sub111, Sub112, Sub79, Sub80, Sub82
	common /varXh/ Sub81, Sub103, Sub97, Sub37, Sub108, Sub98
	common /varXh/ Sub99, Sub101, Sub83, Sub35, Sub95, Sub36
	common /varXh/ Sub40, Sub89, Sub87, Sub90, Sub88, Sub107
	common /varXh/ Sub104, Sub96, Sub106

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_x1x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
