#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 18-Jun-2015 10:15
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1(2), Sub2(2), Sub4, Sub5
	ComplexType Sub31, Sub87, Sub88, Sub47, Sub65, Sub72, Sub78
	ComplexType Sub30, Sub109, Sub73, Sub79, Sub48, Sub66, Sub64
	ComplexType Sub61, Sub77, Sub46, Sub51, Sub71, Sub62, Sub68
	ComplexType Sub67, Sub53, Sub54, Sub75, Sub74, Sub81
	ComplexType Sub70(2), Sub60(2), Sub56(2), Sub57(2), Sub50(2)
	ComplexType Sub45(2), Sub52(2), Sub49(2), Sub55(2), Sub58(2)
	ComplexType Sub59(2), Sub80(2), Sub63(2), Sub69(2), Sub76(2)
	ComplexType Sub98(2), Sub82(2), Sub9(2), Sub41(2), Sub42(2)
	ComplexType Sub8(2,2), Sub37(2,2), Sub20(2,2), Sub85(2,2)
	ComplexType Sub21(2,2), Sub22(2,2), Sub28(2,2,2), Sub35
	ComplexType Sub32, Sub110, Sub108, Sub34, Sub33, Sub36
	ComplexType Sub115(2), Sub7(2,2), Sub29, Sub92, pave2(2)
	ComplexType pave3, pave7(Nbb), pave8(Ncc), pave10(Ncc,2)
	ComplexType pave12(Ncc,2,2)
	common /varXs/ Sub1, Sub2, Sub4, Sub5, Sub31, Sub87, Sub88
	common /varXs/ Sub47, Sub65, Sub72, Sub78, Sub30, Sub109
	common /varXs/ Sub73, Sub79, Sub48, Sub66, Sub64, Sub61
	common /varXs/ Sub77, Sub46, Sub51, Sub71, Sub62, Sub68
	common /varXs/ Sub67, Sub53, Sub54, Sub75, Sub74, Sub81
	common /varXs/ Sub70, Sub60, Sub56, Sub57, Sub50, Sub45
	common /varXs/ Sub52, Sub49, Sub55, Sub58, Sub59, Sub80
	common /varXs/ Sub63, Sub69, Sub76, Sub98, Sub82, Sub9
	common /varXs/ Sub41, Sub42, Sub8, Sub37, Sub20, Sub85
	common /varXs/ Sub21, Sub22, Sub28, Sub35, Sub32, Sub110
	common /varXs/ Sub108, Sub34, Sub33, Sub36, Sub115, Sub7
	common /varXs/ Sub29, Sub92, pave2, pave3, pave7, pave8
	common /varXs/ pave10, pave12

	ComplexType Sub111(2), Sub112(2), Sub113(2), Sub123(2)
	ComplexType Sub103(2), Sub102(2), Sub122(2), pave1(Nbb,2)
	ComplexType pave4(Nbb), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave9(Ncc,2), pave11(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub111, Sub112, Sub113, Sub123, Sub103, Sub102
	common /varXa/ Sub122, pave1, pave4, pave5, pave6, pave9
	common /varXa/ pave11, S, T, U

	HelType F9, F1, F2, F10, F6, F4, F3, F7, F8, F5, Sub6, Sub3
	HelType F11, F18, F15, F13, F14, F16, F17, F21, F12, F22, F23
	HelType F19, F25, F20, F24, Sub91, Sub90, Sub89, Sub97
	HelType Sub96, Sub83(HelDim(2)), Sub84(HelDim(2))
	HelType Sub114(HelDim(2)), Sub116(HelDim(2))
	HelType Sub95(HelDim(2)), Sub44(HelDim(2))
	HelType Sub105(HelDim(2),2), Sub119(HelDim(2),2)
	HelType Sub106(HelDim(2),2), Sub120(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub40(HelDim(2),2)
	HelType Sub86(HelDim(2),2), Sub104(HelDim(2),2)
	HelType Sub107(HelDim(2),2), Sub94(HelDim(2),2)
	HelType Sub100(HelDim(2),2), Sub39(HelDim(2),2)
	HelType Sub38(HelDim(2),2), Sub43(HelDim(2),2), Sub93, Sub99
	HelType Sub124(HelDim(2)), Sub117(HelDim(2),2)
	HelType Sub101(HelDim(2),2), Sub118(HelDim(2),2)
	common /varXh/ F9, F1, F2, F10, F6, F4, F3, F7, F8, F5, Sub6
	common /varXh/ Sub3, F11, F18, F15, F13, F14, F16, F17, F21
	common /varXh/ F12, F22, F23, F19, F25, F20, F24, Sub91
	common /varXh/ Sub90, Sub89, Sub97, Sub96, Sub83, Sub84
	common /varXh/ Sub114, Sub116, Sub95, Sub44, Sub105, Sub119
	common /varXh/ Sub106, Sub120, Sub121, Sub40, Sub86, Sub104
	common /varXh/ Sub107, Sub94, Sub100, Sub39, Sub38, Sub43
	common /varXh/ Sub93, Sub99, Sub124, Sub117, Sub101, Sub118

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_x2x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
