      REAL*8 FUNCTION MATRIX_GD_NINJD_RES(P,NHEL,IC,CHAN)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g d -> ni nj d  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER(NGRAPHS=  14,NEIGEN=  1) 
      include "genps.inc"
      include "nexternal.inc"
      include "maxamps_ninj.inc"
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER(NWAVEFUNCS=  25, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER(ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      include "coupl.inc"
C
C VARIABLES TO APPLY THE DIAGRAM SUBTRACTION SCHEMES 
C
#define _EXTFUNCT_
#include "dsubtraction_ninj.h"

C  
C COLOR DATA
C  
      DATA Denom(1)/            1/                                       
      DATA(CF(i,1),i=1,1) /     4/                                  
C               T[ 5, 2, 1]                                                
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))        
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))        
      CALL OXXXXX(P(0,3),MNI,NHEL(3),+1*IC(3),W(1,3))         
      CALL OXXXXX(P(0,4),MNJ,NHEL(4),+1*IC(4),W(1,4))         
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1*IC(5),W(1,5))   
      
      ! diagram 1
      CALL HIOXXX(W(1,2),W(1,3),GDLNIM,MDL,WDL,W(1, 6))                                                          
      CALL FSOCXX(W(1,4),W(1,6),GDLNJP,ZERO,ZERO,W(1,7))                                                          
      CALL IOVCXX(W(1,5),W(1,7),W(1,1),GG,AMP(1))            
      ! diagram 2
      CALL HIOXXX(W(1,2),W(1,3),GDRNIM,MDR,WDR,W(1, 8))                                                          
      CALL FSOCXX(W(1,4),W(1,8),GDRNJP,ZERO,ZERO,W(1,9))                                                          
      CALL IOVCXX(W(1,5),W(1,9),W(1,1),GG,AMP(2))         
      
      ! diagram 3 <- resonant
      CALL HVSXXX(W(1,1),W(1,6),-GC,MDL,WDLR,W(1,10))    
      CALL IOSCXX(W(1,5),W(1,4),W(1,10),GDLNJP,AMP(3))     
      ! diagram 4 <- resonant
      CALL HVSXXX(W(1,1),W(1,8),-GC,MDR,WDRR,W(1,11))    
      CALL IOSCXX(W(1,5),W(1,4),W(1,11),GDRNJP,AMP(4))    
      
      ! diagram 5 <- resonant
      CALL FVIXXX(W(1,2),W(1,1),GG,ZERO,ZERO,W(1,12))     
      CALL HIOXXX(W(1,12),W(1,3),GDLNIM,MDL,WDLR,W(1, 13))                                                          
      CALL IOSCXX(W(1,5),W(1,4),W(1,13),GDLNJP,AMP(5))       
      ! diagram 6 <- resonant
      CALL HIOXXX(W(1,12),W(1,3),GDRNIM,MDR,WDRR,W(1, 14))                                                          
      CALL IOSCXX(W(1,5),W(1,4),W(1,14),GDRNJP,AMP(6))      
      
      ! diagram 7
      CALL HIOXXX(W(1,2),W(1,4),GDLNJM,MDL,WDL,W(1, 15))                                                          
      CALL FVICXX(W(1,5),W(1,1),GG,ZERO,ZERO,W(1,16))    
      CALL IOSCXX(W(1,16),W(1,3),W(1,15),GDLNIP,AMP(7))      
      ! diagram 8
      CALL HIOXXX(W(1,2),W(1,4),GDRNJM,MDR,WDR,W(1, 17))                                                          
      CALL IOSCXX(W(1,16),W(1,3),W(1,17),GDRNIP,AMP(8))      
      
      ! diagram 9 <- resonant
      CALL HIOCXX(W(1,5),W(1,3),GDLNIP,MDL,WDLR,W(1,18))                                                          
      CALL VSSXXX(W(1,1),W(1,18),W(1,15),GC,AMP(9))            
      ! diagram 10 <- resonant
      CALL HIOCXX(W(1,5),W(1,3),GDRNIP,MDR,WDRR,W(1,19))                                                          
      CALL VSSXXX(W(1,1),W(1,19),W(1,17),GC,AMP(10))            
      
      ! diagram 11 <- resonant
      CALL HIOXXX(W(1,12),W(1,4),GDLNJM,MDL,WDLR,W(1, 20))                                                          
      CALL IOSCXX(W(1,5),W(1,3),W(1,20),GDLNIP,AMP(11))        
      ! diagram 12 <- resonant
      CALL HIOXXX(W(1,12),W(1,4),GDRNJM,MDR,WDRR,W(1, 21))                                                          
      CALL IOSCXX(W(1,5),W(1,3),W(1,21),GDRNIP,AMP(12))        
      
      ! diagram 13
      CALL IXXXXX(P(0,4),MNJ,NHEL(4),-1*IC(4),W(1,22))         
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,23))        
      CALL JIOCXX(W(1,22),W(1,3),GZNIJ,ZMASS,ZWIDTH,W(1, 24))                                                          
      CALL FVOXXX(W(1,23),W(1,1),GG,ZERO,ZERO,W(1,25))     
      CALL IOVXXX(W(1,2),W(1,25),W(1,24),GZD,AMP(13))           
      ! diagram 14
      CALL IOVXXX(W(1,12),W(1,23),W(1,24),GZD,AMP(14))
      
      ! S35 = MDL^2
      if(CHAN.eq.0) then
        JAMP(1) = AMP(9)+AMP(11)
      ! S35 = MDR^2
      else if (CHAN.eq.1) then
        JAMP(1) = AMP(10)+AMP(12)
      ! S45 = MDL^2
      else if (CHAN.eq.2) then
        JAMP(1) = -AMP(3)-AMP(5)
      ! S45 = MDR^2
      else if (CHAN.eq.3) then
        JAMP(1) = -AMP(4)-AMP(6)
      else
        print*,"error in r_gd_ninjd_res.f"
        stop
      endif

      MATRIX_GD_NINJD_RES = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP =(0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          MATRIX_GD_NINJD_RES =MATRIX_GD_NINJD_RES
     &                       +ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO

      END
       
       
