      REAL*8 FUNCTION MATRIX_GUX_NINJUX_RES(P,NHEL,IC,CHAN)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g u~ -> ni nj u~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER(NGRAPHS=  14,NEIGEN=  1) 
      include "genps.inc"
      include "nexternal.inc"
      include "maxamps_ninj.inc"
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER(NWAVEFUNCS=  24, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER(ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C
      include "coupl.inc"
C
C VARIABLES TO APPLY THE DIAGRAM SUBTRACTION SCHEMES 
C
#define _EXTFUNCT_
#include "dsubtraction_ninj.h"  
C  
C COLOR DATA
C  
      DATA Denom(1)/            1/                                       
      DATA(CF(i,1),i=1,1) /     4/                                  
C               T[ 2, 5, 1]                                                
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))        
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))        
      CALL OXXXXX(P(0,3),MNI,NHEL(3),+1*IC(3),W(1,3))         
      CALL IXXXXX(P(0,4),MNJ,NHEL(4),-1*IC(4),W(1,4))         
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1*IC(5),W(1,5))      
      
      ! diagram 1
      CALL HIOXXX(W(1,4),W(1,2),GULNJP,MUL,WUL,W(1, 6))                                                          
      CALL FVIXXX(W(1,5),W(1,1),GG,ZERO,ZERO,W(1,7))     
      CALL IOSXXX(W(1,7),W(1,3),W(1,6),GULNIM,AMP(1))      
      ! diagram 2
      CALL HIOXXX(W(1,4),W(1,2),GURNJP,MUR,WUR,W(1, 8))                                                          
      CALL IOSXXX(W(1,7),W(1,3),W(1,8),GURNIM,AMP(2))      
      
      ! diagram 3 <- resonant
      CALL HIOXXX(W(1,5),W(1,3),GULNIM,MUL,WULR,W(1, 9))                                                          
      CALL VSSXXX(W(1,1),W(1,6),W(1,9),GC,AMP(3))             
      ! diagram 4 <- resonant
      CALL HIOXXX(W(1,5),W(1,3),GURNIM,MUR,WURR,W(1, 10))                                                          
      CALL VSSXXX(W(1,1),W(1,8),W(1,10),GC,AMP(4))             
      
      ! diagram 5 <- resonant
      CALL FVOXXX(W(1,2),W(1,1),GG,ZERO,ZERO,W(1,11))     
      CALL HIOXXX(W(1,4),W(1,11),GULNJP,MUL,WULR,W(1, 12))                                                          
      CALL IOSXXX(W(1,5),W(1,3),W(1,12),GULNIM,AMP(5))         
      ! diagram 6 <- resonant
      CALL HIOXXX(W(1,4),W(1,11),GURNJP,MUR,WURR,W(1, 13))                                                          
      CALL IOSXXX(W(1,5),W(1,3),W(1,13),GURNIM,AMP(6))         
      
      ! diagram 7
      CALL JIOCXX(W(1,4),W(1,3),GZNIJ,ZMASS,ZWIDTH,W(1, 14))                                                          
      CALL IOVXXX(W(1,7),W(1,2),W(1,14),GZU,AMP(7))            
      ! diagram 8
      CALL IOVXXX(W(1,5),W(1,11),W(1,14),GZU,AMP(8))            
      
      ! diagram 9
      CALL IXXXXX(P(0,3),MNI,NHEL(3),-1*IC(3),W(1,15))         
      CALL OXXXXX(P(0,4),MNJ,NHEL(4),+1*IC(4),W(1,16))         
      CALL HIOXXX(W(1,15),W(1,2),GULNIP,MUL,WUL,W(1, 17))                                                          
      CALL FSOXXX(W(1,16),W(1,17),GULNJM,ZERO,ZERO,W(1, 18))                                                          
      CALL IOVXXX(W(1,5),W(1,18),W(1,1),GG,AMP(9))             
      ! diagram 10
      CALL HIOXXX(W(1,15),W(1,2),GURNIP,MUR,WUR,W(1, 19))                                                          
      CALL FSOXXX(W(1,16),W(1,19),GURNJM,ZERO,ZERO,W(1, 20))                                                          
      CALL IOVXXX(W(1,5),W(1,20),W(1,1),GG,AMP(10))            
      
      ! diagram 11 <- resonant
      CALL HVSXXX(W(1,1),W(1,17),GC,MUL,WULR,W(1,21))     
      CALL IOSXXX(W(1,5),W(1,16),W(1,21),GULNJM,AMP(11))       
      ! diagram 12 <- resonant
      CALL HVSXXX(W(1,1),W(1,19),GC,MUR,WURR,W(1,22))     
      CALL IOSXXX(W(1,5),W(1,16),W(1,22),GURNJM,AMP(12))        
      
      ! diagram 13 <- resonant
      CALL HIOXXX(W(1,15),W(1,11),GULNIP,MUL,WULR,W(1, 23))                                                          
      CALL IOSXXX(W(1,5),W(1,16),W(1,23),GULNJM,AMP(13))         
      ! diagram 14 <- resonant
      CALL HIOXXX(W(1,15),W(1,11),GURNIP,MUR,WURR,W(1, 24))                                                          
      CALL IOSXXX(W(1,5),W(1,16),W(1,24),GURNJM,AMP(14))       
      
      ! S35 = MUL^2
      if(CHAN.eq.0) then
        JAMP(1) = -AMP(3)-AMP(5)
      ! S35 = MUR^2
      else if (CHAN.eq.1) then
        JAMP(1) = -AMP(4)-AMP(6)
      ! S45 = MUL^2
      else if (CHAN.eq.2) then
        JAMP(1) = +AMP(11)+AMP(13)
      ! S45 = MUR^2
      else if (CHAN.eq.3) then
        JAMP(1) = +AMP(12)+AMP(14)
      else
        print*,"error in r_gux_ninjux_res.f"
        stop
      endif

      
      MATRIX_GUX_NINJUX_RES = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP =(0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          MATRIX_GUX_NINJUX_RES =MATRIX_GUX_NINJUX_RES
     &                       +ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO

      END
       
       
