      REAL*8 FUNCTION MATRIX_UG_NINJU_RES(P,NHEL,IC,CHAN)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : u g -> ni nj u  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER(NGRAPHS=  14,NEIGEN=  1) 
      include "genps.inc"
      include "nexternal.inc"
      include "maxamps_ninj.inc"
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER(NWAVEFUNCS=  25, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER(ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C
      include "coupl.inc"
C
C VARIABLES TO APPLY THE DIAGRAM SUBTRACTION SCHEMES 
C
#define _EXTFUNCT_
#include "dsubtraction_ninj.h" 
C  
C COLOR DATA
C  
      DATA Denom(1)/            1/                                       
      DATA(CF(i,1),i=1,1) /     4/                                  
C               T[ 5, 1, 2]                                                
C ----------
C BEGIN CODE
C ----------
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1*IC(1),W(1,1))        
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))        
      CALL OXXXXX(P(0,3),MNI,NHEL(3),+1*IC(3),W(1,3))         
      CALL OXXXXX(P(0,4),MNJ,NHEL(4),+1*IC(4),W(1,4))         
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1*IC(5),W(1,5))  
      
      ! diagram 1
      CALL HIOXXX(W(1,1),W(1,4),GULNJM,MUL,WUL,W(1, 6))                                                          
      CALL FVICXX(W(1,5),W(1,2),GG,ZERO,ZERO,W(1,7))    
      CALL IOSCXX(W(1,7),W(1,3),W(1,6),GULNIP,AMP(1))        
      ! diagram 2
      CALL HIOXXX(W(1,1),W(1,4),GURNJM,MUR,WUR,W(1, 8))                                                          
      CALL IOSCXX(W(1,7),W(1,3),W(1,8),GURNIP,AMP(2))      
      
      ! diagram 3 <- resonant
      CALL HIOCXX(W(1,5),W(1,3),GULNIP,MUL,WULR,W(1,9))                                                          
      CALL VSSXXX(W(1,2),W(1,9),W(1,6),GC,AMP(3))             
      ! diagram 4 <- resonant
      CALL HIOCXX(W(1,5),W(1,3),GURNIP,MUR,WURR,W(1,10))                                                          
      CALL VSSXXX(W(1,2),W(1,10),W(1,8),GC,AMP(4))             
      
      ! diagram 5 <- resonant
      CALL FVIXXX(W(1,1),W(1,2),GG,ZERO,ZERO,W(1,11))     
      CALL HIOXXX(W(1,11),W(1,4),GULNJM,MUL,WULR,W(1, 12))                                                          
      CALL IOSCXX(W(1,5),W(1,3),W(1,12),GULNIP,AMP(5))        
      ! diagram 6 <- resonant
      CALL HIOXXX(W(1,11),W(1,4),GURNJM,MUR,WURR,W(1, 13))                                                          
      CALL IOSCXX(W(1,5),W(1,3),W(1,13),GURNIP,AMP(6))        
      
      ! diagram 7
      CALL HIOXXX(W(1,1),W(1,3),GULNIM,MUL,WUL,W(1, 14))                                                          
      CALL FSOCXX(W(1,4),W(1,14),GULNJP,ZERO,ZERO,W(1,15))                                                          
      CALL IOVCXX(W(1,5),W(1,15),W(1,2),GG,AMP(7))            
      ! diagram 8
      CALL HIOXXX(W(1,1),W(1,3),GURNIM,MUR,WUR,W(1, 16))                                                          
      CALL FSOCXX(W(1,4),W(1,16),GURNJP,ZERO,ZERO,W(1,17))                                                          
      CALL IOVCXX(W(1,5),W(1,17),W(1,2),GG,AMP(8))            
      
      ! diagram 9 <- resonant
      CALL HVSXXX(W(1,2),W(1,14),-GC,MUL,WULR,W(1,18))    
      CALL IOSCXX(W(1,5),W(1,4),W(1,18),GULNJP,AMP(9))        
      ! diagram 10 <- resonant
      CALL HVSXXX(W(1,2),W(1,16),-GC,MUR,WURR,W(1,19))    
      CALL IOSCXX(W(1,5),W(1,4),W(1,19),GURNJP,AMP(10))        
      
      ! diagram 11 <- resonant
      CALL HIOXXX(W(1,11),W(1,3),GULNIM,MUL,WULR,W(1, 20))                                                          
      CALL IOSCXX(W(1,5),W(1,4),W(1,20),GULNJP,AMP(11))        
      ! diagram 12 <- resonant
      CALL HIOXXX(W(1,11),W(1,3),GURNIM,MUR,WURR,W(1, 21))                                                          
      CALL IOSCXX(W(1,5),W(1,4),W(1,21),GURNJP,AMP(12))        
      
      ! diagram 13
      CALL IXXXXX(P(0,4),MNJ,NHEL(4),-1*IC(4),W(1,22))         
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,23))        
      CALL JIOCXX(W(1,22),W(1,3),GZNIJ,ZMASS,ZWIDTH,W(1, 24))                                                          
      CALL FVOXXX(W(1,23),W(1,2),GG,ZERO,ZERO,W(1,25))     
      CALL IOVXXX(W(1,1),W(1,25),W(1,24),GZU,AMP(13))            
      ! diagram 14
      CALL IOVXXX(W(1,11),W(1,23),W(1,24),GZU,AMP(14))            
      
      ! S35 = MUL^2
      if(CHAN.eq.0) then
        JAMP(1) = AMP(3)+AMP(5)
      ! S35 = MUR^2
      else if (CHAN.eq.1) then
        JAMP(1) = AMP(4)+AMP(6)
      ! S45 = MUL^2
      else if (CHAN.eq.2) then
        JAMP(1) = -AMP(9)-AMP(11)
      ! S45 = MUR^2
      else if (CHAN.eq.3) then
        JAMP(1) = -AMP(10)-AMP(12)
      else
        print*,"error in r_ug_ninju_res.f"
        stop
      endif
      
      MATRIX_UG_NINJU_RES = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP =(0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          MATRIX_UG_NINJU_RES =MATRIX_UG_NINJU_RES
     &                       +ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO

      END
       
       
