#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 8-Jun-2015 15:49
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub2, Sub8, Sub1(2), Sub5(2), Sub3(2)
	ComplexType Sub6(2)
	ComplexType Sub34, Sub121, Sub122, Sub74, Sub89, Sub33, Sub44
	ComplexType Sub75, Sub90, Sub58, Sub48, Sub49, Sub88, Sub86
	ComplexType Sub73, Sub68, Sub70, Sub37, Sub38, Sub50, Sub54
	ComplexType Sub60, Sub46, Sub61, Sub62, Sub59, Sub41, Sub42
	ComplexType Sub52, Sub51, Sub78, Sub79, Sub80, Sub43(2)
	ComplexType Sub65(2), Sub84(2), Sub67(2), Sub72(2), Sub47(2)
	ComplexType Sub69(2), Sub71(2), Sub76(2), Sub83(2), Sub55(2)
	ComplexType Sub56(2), Sub91(2), Sub63(2), Sub87(2), Sub93(2)
	ComplexType Sub64(2), Sub57(2), Sub40(2), Sub85(2), Sub95(2)
	ComplexType Sub77(2), Sub94(2), Sub103(2), Sub14(2)
	ComplexType Sub106(2), Sub15(2), Sub9(2,2), Sub204(2,2)
	ComplexType Sub23(2,2), Sub101(2,2), Sub104(2,2)
	ComplexType Sub114(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub31(2,2,2), Sub35, Sub221, Sub36, Sub10(2,2)
	ComplexType Sub81, Sub32, Sub53, Sub39, Sub45, Sub92, Sub82
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave16(Ncc,2,2), pave17, pave18(Ncc,2)
	common /varXs/ Sub4, Sub2, Sub8, Sub1, Sub5, Sub3, Sub6
	common /varXs/ Sub34, Sub121, Sub122, Sub74, Sub89, Sub33
	common /varXs/ Sub44, Sub75, Sub90, Sub58, Sub48, Sub49
	common /varXs/ Sub88, Sub86, Sub73, Sub68, Sub70, Sub37
	common /varXs/ Sub38, Sub50, Sub54, Sub60, Sub46, Sub61
	common /varXs/ Sub62, Sub59, Sub41, Sub42, Sub52, Sub51
	common /varXs/ Sub78, Sub79, Sub80, Sub43, Sub65, Sub84
	common /varXs/ Sub67, Sub72, Sub47, Sub69, Sub71, Sub76
	common /varXs/ Sub83, Sub55, Sub56, Sub91, Sub63, Sub87
	common /varXs/ Sub93, Sub64, Sub57, Sub40, Sub85, Sub95
	common /varXs/ Sub77, Sub94, Sub103, Sub14, Sub106, Sub15
	common /varXs/ Sub9, Sub204, Sub23, Sub101, Sub104, Sub114
	common /varXs/ Sub24, Sub25, Sub31, Sub35, Sub221, Sub36
	common /varXs/ Sub10, Sub81, Sub32, Sub53, Sub39, Sub45
	common /varXs/ Sub92, Sub82, pave1, pave2, pave3, pave16
	common /varXs/ pave17, pave18

	ComplexType Sub225(2), Sub222(2), Sub226(2), Sub223(2)
	ComplexType Sub208(2), Sub209(2), Sub215(2), Sub218(2)
	ComplexType Sub214(2), Sub217(2), Sub229(2,2), Sub234(2,2)
	ComplexType Sub210(2,2), Sub211(2,2), Sub239(2), Sub240(2)
	ComplexType Sub158, pave4(Ndd,2,2), pave5(Ndd,2,2)
	ComplexType pave6(Ndd,2), pave7(Ndd,2), pave8(Nbb,2)
	ComplexType pave9(Ncc,2), pave10(Nbb,2), pave11(Ncc,2)
	ComplexType pave12(Ncc,2), pave13(Ncc,2), pave14(Nbb)
	ComplexType pave15(Nbb)
	RealType S, T, U
	common /varXa/ Sub225, Sub222, Sub226, Sub223, Sub208, Sub209
	common /varXa/ Sub215, Sub218, Sub214, Sub217, Sub229
	common /varXa/ Sub234, Sub210, Sub211, Sub239, Sub240
	common /varXa/ Sub158, pave4, pave5, pave6, pave7, pave8
	common /varXa/ pave9, pave10, pave11, pave12, pave13, pave14
	common /varXa/ pave15, S, T, U

	HelType F1, F5, F10, F7, F6, F3, F12, F2, F9, F8, F4, F11
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F20, F19, F25, F22, F14
	HelType F15, F36, F41, F39, F37, F26, F35, F42, F40, F38
	HelType F28, F29, F33, F31, F34, F17, F30, F18, F32, Sub152
	HelType Sub149, Sub143, Sub140, Sub123, Sub173, Sub171
	HelType Sub172, Sub170, Sub162, Sub160, Sub161, Sub159
	HelType Sub165, Sub151, Sub167, Sub168, Sub154, Sub164
	HelType Sub178, Sub176, Sub142, Sub179, Sub145, Sub175
	HelType Sub144, Sub153, Sub137(HelDim(2)), Sub138(HelDim(2))
	HelType Sub131(HelDim(2)), Sub132(HelDim(2))
	HelType Sub134(HelDim(2)), Sub135(HelDim(2))
	HelType Sub166(HelDim(2)), Sub177(HelDim(2))
	HelType Sub180(HelDim(2)), Sub155(HelDim(2))
	HelType Sub146(HelDim(2)), Sub133(HelDim(2))
	HelType Sub136(HelDim(2)), Sub139(HelDim(2))
	HelType Sub147(HelDim(2)), Sub156(HelDim(2))
	HelType Sub181(HelDim(2)), Sub157(HelDim(2))
	HelType Sub148(HelDim(2)), Sub163(HelDim(2))
	HelType Sub169(HelDim(2)), Sub174(HelDim(2))
	HelType Sub186(HelDim(2)), Sub191(HelDim(2))
	HelType Sub224(HelDim(2)), Sub241(HelDim(2))
	HelType Sub98(HelDim(2)), Sub66(HelDim(2)), Sub99(HelDim(2))
	HelType Sub96(HelDim(2)), Sub227(HelDim(2))
	HelType Sub117(HelDim(2),2), Sub118(HelDim(2),2)
	HelType Sub128(HelDim(2),2), Sub129(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub213(HelDim(2),2)
	HelType Sub216(HelDim(2),2), Sub219(HelDim(2),2)
	HelType Sub220(HelDim(2),2), Sub230(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub203(HelDim(2),2)
	HelType Sub207(HelDim(2),2), Sub202(HelDim(2),2)
	HelType Sub198(HelDim(2),2), Sub197(HelDim(2),2)
	HelType Sub201(HelDim(2),2), Sub200(HelDim(2),2)
	HelType Sub199(HelDim(2),2), Sub195(HelDim(2),2)
	HelType Sub194(HelDim(2),2), Sub126(HelDim(2),2)
	HelType Sub115(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub124(HelDim(2),2)
	HelType Sub112(HelDim(2),2), Sub109(HelDim(2),2)
	HelType Sub105(HelDim(2),2), Sub120(HelDim(2),2)
	HelType Sub192(HelDim(2),2), Sub196(HelDim(2),2)
	HelType Sub193(HelDim(2),2), Sub102(HelDim(2),2)
	HelType Sub110(HelDim(2),2), Sub107(HelDim(2),2)
	HelType Sub127(HelDim(2),2), Sub116(HelDim(2),2), Sub119
	HelType Sub130, Sub183, Sub184, Sub182, Sub185, Sub188
	HelType Sub190, Sub187, Sub189, Sub141, Sub150
	HelType Sub97(HelDim(2)), Sub100(HelDim(2))
	HelType Sub212(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub111(HelDim(2),2)
	HelType Sub206(HelDim(2),2), Sub205(HelDim(2),2)
	HelType Sub238(HelDim(2)), Sub237(HelDim(2))
	HelType Sub228(HelDim(2),2)
	common /varXh/ F1, F5, F10, F7, F6, F3, F12, F2, F9, F8, F4
	common /varXh/ F11, Sub7, F16, F21, F13, F24, F27, F23, F20
	common /varXh/ F19, F25, F22, F14, F15, F36, F41, F39, F37
	common /varXh/ F26, F35, F42, F40, F38, F28, F29, F33, F31
	common /varXh/ F34, F17, F30, F18, F32, Sub152, Sub149
	common /varXh/ Sub143, Sub140, Sub123, Sub173, Sub171
	common /varXh/ Sub172, Sub170, Sub162, Sub160, Sub161
	common /varXh/ Sub159, Sub165, Sub151, Sub167, Sub168
	common /varXh/ Sub154, Sub164, Sub178, Sub176, Sub142
	common /varXh/ Sub179, Sub145, Sub175, Sub144, Sub153
	common /varXh/ Sub137, Sub138, Sub131, Sub132, Sub134
	common /varXh/ Sub135, Sub166, Sub177, Sub180, Sub155
	common /varXh/ Sub146, Sub133, Sub136, Sub139, Sub147
	common /varXh/ Sub156, Sub181, Sub157, Sub148, Sub163
	common /varXh/ Sub169, Sub174, Sub186, Sub191, Sub224
	common /varXh/ Sub241, Sub98, Sub66, Sub99, Sub96, Sub227
	common /varXh/ Sub117, Sub118, Sub128, Sub129, Sub232
	common /varXh/ Sub213, Sub216, Sub219, Sub220, Sub230
	common /varXh/ Sub231, Sub233, Sub236, Sub203, Sub207
	common /varXh/ Sub202, Sub198, Sub197, Sub201, Sub200
	common /varXh/ Sub199, Sub195, Sub194, Sub126, Sub115
	common /varXh/ Sub125, Sub113, Sub124, Sub112, Sub109
	common /varXh/ Sub105, Sub120, Sub192, Sub196, Sub193
	common /varXh/ Sub102, Sub110, Sub107, Sub127, Sub116
	common /varXh/ Sub119, Sub130, Sub183, Sub184, Sub182
	common /varXh/ Sub185, Sub188, Sub190, Sub187, Sub189
	common /varXh/ Sub141, Sub150, Sub97, Sub100, Sub212, Sub235
	common /varXh/ Sub108, Sub111, Sub206, Sub205, Sub238
	common /varXh/ Sub237, Sub228

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n2n2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
