#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:57
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub2, Sub8, Sub1(2), Sub5(2), Sub3(2)
	ComplexType Sub6(2)
	ComplexType Sub34, Sub127, Sub128, Sub74, Sub89, Sub33, Sub41
	ComplexType Sub75, Sub90, Sub58, Sub48, Sub49, Sub88, Sub86
	ComplexType Sub73, Sub68, Sub70, Sub39, Sub37, Sub50, Sub51
	ComplexType Sub52, Sub54, Sub60, Sub43, Sub61, Sub62, Sub59
	ComplexType Sub44, Sub45, Sub78, Sub79, Sub80, Sub46(2)
	ComplexType Sub65(2), Sub84(2), Sub67(2), Sub72(2), Sub47(2)
	ComplexType Sub69(2), Sub71(2), Sub76(2), Sub83(2), Sub55(2)
	ComplexType Sub56(2), Sub91(2), Sub63(2), Sub87(2), Sub93(2)
	ComplexType Sub64(2), Sub57(2), Sub40(2), Sub85(2), Sub95(2)
	ComplexType Sub77(2), Sub94(2), Sub101(2), Sub14(2)
	ComplexType Sub104(2), Sub15(2), Sub9(2,2), Sub204(2,2)
	ComplexType Sub23(2,2), Sub107(2,2), Sub102(2,2)
	ComplexType Sub114(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub31(2,2,2), Sub35, Sub219, Sub36, Sub10(2,2)
	ComplexType Sub81, Sub32, Sub53, Sub38, Sub42, Sub92, Sub82
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave16(Ncc,2,2), pave17, pave18(Ncc,2)
	common /varXs/ Sub4, Sub2, Sub8, Sub1, Sub5, Sub3, Sub6
	common /varXs/ Sub34, Sub127, Sub128, Sub74, Sub89, Sub33
	common /varXs/ Sub41, Sub75, Sub90, Sub58, Sub48, Sub49
	common /varXs/ Sub88, Sub86, Sub73, Sub68, Sub70, Sub39
	common /varXs/ Sub37, Sub50, Sub51, Sub52, Sub54, Sub60
	common /varXs/ Sub43, Sub61, Sub62, Sub59, Sub44, Sub45
	common /varXs/ Sub78, Sub79, Sub80, Sub46, Sub65, Sub84
	common /varXs/ Sub67, Sub72, Sub47, Sub69, Sub71, Sub76
	common /varXs/ Sub83, Sub55, Sub56, Sub91, Sub63, Sub87
	common /varXs/ Sub93, Sub64, Sub57, Sub40, Sub85, Sub95
	common /varXs/ Sub77, Sub94, Sub101, Sub14, Sub104, Sub15
	common /varXs/ Sub9, Sub204, Sub23, Sub107, Sub102, Sub114
	common /varXs/ Sub24, Sub25, Sub31, Sub35, Sub219, Sub36
	common /varXs/ Sub10, Sub81, Sub32, Sub53, Sub38, Sub42
	common /varXs/ Sub92, Sub82, pave1, pave2, pave3, pave16
	common /varXs/ pave17, pave18

	ComplexType Sub223(2), Sub220(2), Sub224(2), Sub221(2)
	ComplexType Sub207(2), Sub206(2), Sub211(2), Sub214(2)
	ComplexType Sub210(2), Sub213(2), Sub231(2,2), Sub208(2,2)
	ComplexType Sub209(2,2), Sub238(2), Sub235(2), Sub163
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave7(Ndd,2), pave8(Nbb,2), pave9(Ncc,2)
	ComplexType pave10(Nbb,2), pave11(Ncc,2), pave12(Ncc,2)
	ComplexType pave13(Ncc,2), pave14(Nbb), pave15(Nbb)
	RealType S, T, U
	common /varXa/ Sub223, Sub220, Sub224, Sub221, Sub207, Sub206
	common /varXa/ Sub211, Sub214, Sub210, Sub213, Sub231
	common /varXa/ Sub208, Sub209, Sub238, Sub235, Sub163, pave4
	common /varXa/ pave5, pave6, pave7, pave8, pave9, pave10
	common /varXa/ pave11, pave12, pave13, pave14, pave15, S, T
	common /varXa/ U

	HelType F3, F5, F7, F9, F6, F1, F11, F4, F10, F12, F2, F8
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F19, F20, F25, F22, F14
	HelType F15, F34, F41, F38, F37, F26, F32, F42, F40, F39
	HelType F28, F31, F35, F29, F36, F17, F30, F18, F33, Sub144
	HelType Sub149, Sub152, Sub141, Sub129, Sub174, Sub164
	HelType Sub165, Sub176, Sub175, Sub177, Sub167, Sub166
	HelType Sub186, Sub154, Sub185, Sub184, Sub151, Sub187
	HelType Sub146, Sub179, Sub143, Sub180, Sub182, Sub181
	HelType Sub145, Sub153, Sub131(HelDim(2)), Sub137(HelDim(2))
	HelType Sub138(HelDim(2)), Sub134(HelDim(2))
	HelType Sub132(HelDim(2)), Sub135(HelDim(2))
	HelType Sub188(HelDim(2)), Sub155(HelDim(2))
	HelType Sub147(HelDim(2)), Sub133(HelDim(2))
	HelType Sub136(HelDim(2)), Sub139(HelDim(2))
	HelType Sub148(HelDim(2)), Sub156(HelDim(2))
	HelType Sub189(HelDim(2)), Sub140(HelDim(2))
	HelType Sub157(HelDim(2)), Sub162(HelDim(2))
	HelType Sub168(HelDim(2)), Sub173(HelDim(2))
	HelType Sub178(HelDim(2)), Sub183(HelDim(2))
	HelType Sub222(HelDim(2)), Sub236(HelDim(2))
	HelType Sub239(HelDim(2)), Sub66(HelDim(2))
	HelType Sub98(HelDim(2)), Sub96(HelDim(2)), Sub99(HelDim(2))
	HelType Sub225(HelDim(2)), Sub117(HelDim(2),2)
	HelType Sub118(HelDim(2),2), Sub123(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub212(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub216(HelDim(2),2), Sub218(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub229(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub201(HelDim(2),2), Sub203(HelDim(2),2)
	HelType Sub197(HelDim(2),2), Sub196(HelDim(2),2)
	HelType Sub195(HelDim(2),2), Sub198(HelDim(2),2)
	HelType Sub199(HelDim(2),2), Sub200(HelDim(2),2)
	HelType Sub193(HelDim(2),2), Sub192(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub115(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub120(HelDim(2),2)
	HelType Sub112(HelDim(2),2), Sub119(HelDim(2),2)
	HelType Sub103(HelDim(2),2), Sub109(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub190(HelDim(2),2)
	HelType Sub194(HelDim(2),2), Sub191(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub105(HelDim(2),2)
	HelType Sub110(HelDim(2),2), Sub116(HelDim(2),2)
	HelType Sub122(HelDim(2),2), Sub125, Sub130, Sub159, Sub158
	HelType Sub169, Sub171, Sub170, Sub172, Sub160, Sub161
	HelType Sub142, Sub150, Sub97(HelDim(2)), Sub100(HelDim(2))
	HelType Sub217(HelDim(2),2), Sub111(HelDim(2),2)
	HelType Sub106(HelDim(2),2), Sub205(HelDim(2),2)
	HelType Sub202(HelDim(2),2), Sub237(HelDim(2))
	HelType Sub240(HelDim(2)), Sub226(HelDim(2),2)
	common /varXh/ F3, F5, F7, F9, F6, F1, F11, F4, F10, F12, F2
	common /varXh/ F8, Sub7, F16, F21, F13, F24, F27, F23, F19
	common /varXh/ F20, F25, F22, F14, F15, F34, F41, F38, F37
	common /varXh/ F26, F32, F42, F40, F39, F28, F31, F35, F29
	common /varXh/ F36, F17, F30, F18, F33, Sub144, Sub149
	common /varXh/ Sub152, Sub141, Sub129, Sub174, Sub164
	common /varXh/ Sub165, Sub176, Sub175, Sub177, Sub167
	common /varXh/ Sub166, Sub186, Sub154, Sub185, Sub184
	common /varXh/ Sub151, Sub187, Sub146, Sub179, Sub143
	common /varXh/ Sub180, Sub182, Sub181, Sub145, Sub153
	common /varXh/ Sub131, Sub137, Sub138, Sub134, Sub132
	common /varXh/ Sub135, Sub188, Sub155, Sub147, Sub133
	common /varXh/ Sub136, Sub139, Sub148, Sub156, Sub189
	common /varXh/ Sub140, Sub157, Sub162, Sub168, Sub173
	common /varXh/ Sub178, Sub183, Sub222, Sub236, Sub239, Sub66
	common /varXh/ Sub98, Sub96, Sub99, Sub225, Sub117, Sub118
	common /varXh/ Sub123, Sub124, Sub228, Sub230, Sub233
	common /varXh/ Sub212, Sub215, Sub216, Sub218, Sub227
	common /varXh/ Sub229, Sub232, Sub234, Sub201, Sub203
	common /varXh/ Sub197, Sub196, Sub195, Sub198, Sub199
	common /varXh/ Sub200, Sub193, Sub192, Sub121, Sub115
	common /varXh/ Sub113, Sub120, Sub112, Sub119, Sub103
	common /varXh/ Sub109, Sub126, Sub190, Sub194, Sub191
	common /varXh/ Sub108, Sub105, Sub110, Sub116, Sub122
	common /varXh/ Sub125, Sub130, Sub159, Sub158, Sub169
	common /varXh/ Sub171, Sub170, Sub172, Sub160, Sub161
	common /varXh/ Sub142, Sub150, Sub97, Sub100, Sub217, Sub111
	common /varXh/ Sub106, Sub205, Sub202, Sub237, Sub240, Sub226

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n4n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
