#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:13
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7(2)
	ComplexType Sub2(2), Sub4(2), Sub11(2), Sub9(2), Sub3(2)
	ComplexType Sub6(2), Sub12(2)
	ComplexType Sub43, Sub164, Sub165, Sub83, Sub97, Sub42, Sub53
	ComplexType Sub84, Sub98, Sub66, Sub57, Sub58, Sub96, Sub94
	ComplexType Sub82, Sub77, Sub79, Sub46, Sub47, Sub115
	ComplexType Sub118, Sub55, Sub119, Sub120, Sub117, Sub50
	ComplexType Sub51, Sub59, Sub62, Sub69, Sub112, Sub70, Sub71
	ComplexType Sub68, Sub109, Sub110, Sub60, Sub87, Sub88
	ComplexType Sub111(2), Sub52(2), Sub132(2), Sub123(2)
	ComplexType Sub74(2), Sub92(2), Sub76(2), Sub81(2)
	ComplexType Sub113(2), Sub56(2), Sub78(2), Sub80(2)
	ComplexType Sub131(2), Sub85(2), Sub91(2), Sub63(2)
	ComplexType Sub64(2), Sub99(2), Sub121(2), Sub72(2)
	ComplexType Sub95(2), Sub102(2), Sub126(2), Sub122(2)
	ComplexType Sub116(2), Sub49(2), Sub73(2), Sub65(2)
	ComplexType Sub108(2), Sub93(2), Sub128(2), Sub86(2)
	ComplexType Sub127(2), Sub133(2), Sub104(2), Sub129(2)
	ComplexType Sub103(2), Sub145(2), Sub30(2), Sub137(2)
	ComplexType Sub21(2), Sub147(2), Sub31(2), Sub138(2)
	ComplexType Sub22(2), Sub17(2,2), Sub32(2,2), Sub153(2,2)
	ComplexType Sub146(2,2), Sub140(2,2), Sub141(2,2)
	ComplexType Sub148(2,2), Sub33(2,2), Sub34(2,2)
	ComplexType Sub40(2,2,2), Sub44, Sub273, Sub45, Sub16(2,2)
	ComplexType Sub89, Sub130, Sub41, Sub114, Sub61, Sub48
	ComplexType Sub107, Sub54, Sub67, Sub125, Sub100, Sub90
	ComplexType Sub101, pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave12(Ncc,2), pave13(Ncc,2), pave20(Ncc,2,2)
	ComplexType pave23
	common /varXs/ Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7
	common /varXs/ Sub2, Sub4, Sub11, Sub9, Sub3, Sub6, Sub12
	common /varXs/ Sub43, Sub164, Sub165, Sub83, Sub97, Sub42
	common /varXs/ Sub53, Sub84, Sub98, Sub66, Sub57, Sub58
	common /varXs/ Sub96, Sub94, Sub82, Sub77, Sub79, Sub46
	common /varXs/ Sub47, Sub115, Sub118, Sub55, Sub119, Sub120
	common /varXs/ Sub117, Sub50, Sub51, Sub59, Sub62, Sub69
	common /varXs/ Sub112, Sub70, Sub71, Sub68, Sub109, Sub110
	common /varXs/ Sub60, Sub87, Sub88, Sub111, Sub52, Sub132
	common /varXs/ Sub123, Sub74, Sub92, Sub76, Sub81, Sub113
	common /varXs/ Sub56, Sub78, Sub80, Sub131, Sub85, Sub91
	common /varXs/ Sub63, Sub64, Sub99, Sub121, Sub72, Sub95
	common /varXs/ Sub102, Sub126, Sub122, Sub116, Sub49, Sub73
	common /varXs/ Sub65, Sub108, Sub93, Sub128, Sub86, Sub127
	common /varXs/ Sub133, Sub104, Sub129, Sub103, Sub145, Sub30
	common /varXs/ Sub137, Sub21, Sub147, Sub31, Sub138, Sub22
	common /varXs/ Sub17, Sub32, Sub153, Sub146, Sub140, Sub141
	common /varXs/ Sub148, Sub33, Sub34, Sub40, Sub44, Sub273
	common /varXs/ Sub45, Sub16, Sub89, Sub130, Sub41, Sub114
	common /varXs/ Sub61, Sub48, Sub107, Sub54, Sub67, Sub125
	common /varXs/ Sub100, Sub90, Sub101, pave1, pave2, pave3
	common /varXs/ pave12, pave13, pave20, pave23

	ComplexType Sub279(2), Sub275(2), Sub294(2), Sub292(2)
	ComplexType Sub295(2), Sub293(2), Sub278(2), Sub274(2)
	ComplexType Sub254(2), Sub253(2), Sub266(2), Sub268(2)
	ComplexType Sub262(2), Sub260(2), Sub256(2,2), Sub255(2,2)
	ComplexType Sub209, Sub197, Sub276(2), Sub280(2)
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave7(Ndd,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ncc,2), pave11(Ncc,2), pave14(Nbb,2)
	ComplexType pave15(Nbb,2), pave16(Ncc,2), pave17(Ncc,2)
	ComplexType pave18(Ncc,2), pave19(Ncc,2), pave21(Nbb)
	ComplexType pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub279, Sub275, Sub294, Sub292, Sub295, Sub293
	common /varXa/ Sub278, Sub274, Sub254, Sub253, Sub266
	common /varXa/ Sub268, Sub262, Sub260, Sub256, Sub255
	common /varXa/ Sub209, Sub197, Sub276, Sub280, pave4, pave5
	common /varXa/ pave6, pave7, pave8, pave9, pave10, pave11
	common /varXa/ pave14, pave15, pave16, pave17, pave18
	common /varXa/ pave19, pave21, pave22, S, T, U

	HelType F1, F4, F7, F9, F5, F2, F11, F6, F10, F12, F3, F8
	HelType Sub15
	HelType F16, F21, F13, F24, F27, F20, F23, F19, F25, F22, F14
	HelType F15, F34, F32, F40, F38, F26, F29, F33, F42, F39
	HelType F28, F41, F30, F36, F31, F17, F37, F18, F35, Sub166
	HelType Sub220, Sub216, Sub228, Sub230, Sub232, Sub231
	HelType Sub219, Sub218, Sub204, Sub205, Sub206, Sub207
	HelType Sub199, Sub198, Sub201, Sub189, Sub191, Sub183
	HelType Sub185, Sub224, Sub222, Sub227, Sub229, Sub193
	HelType Sub190, Sub210, Sub212, Sub217, Sub215
	HelType Sub176(HelDim(2)), Sub289(HelDim(2))
	HelType Sub196(HelDim(2)), Sub226(HelDim(2))
	HelType Sub177(HelDim(2)), Sub178(HelDim(2))
	HelType Sub184(HelDim(2)), Sub187(HelDim(2))
	HelType Sub200(HelDim(2)), Sub202(HelDim(2))
	HelType Sub211(HelDim(2)), Sub213(HelDim(2))
	HelType Sub124(HelDim(2)), Sub134(HelDim(2))
	HelType Sub179(HelDim(2)), Sub188(HelDim(2))
	HelType Sub214(HelDim(2)), Sub181(HelDim(2))
	HelType Sub203(HelDim(2)), Sub221(HelDim(2))
	HelType Sub277(HelDim(2)), Sub175(HelDim(2))
	HelType Sub174(HelDim(2)), Sub192(HelDim(2))
	HelType Sub223(HelDim(2)), Sub194(HelDim(2))
	HelType Sub225(HelDim(2)), Sub195(HelDim(2))
	HelType Sub180(HelDim(2)), Sub75(HelDim(2))
	HelType Sub105(HelDim(2)), Sub281(HelDim(2))
	HelType Sub208(HelDim(2)), Sub233(HelDim(2))
	HelType Sub257(HelDim(2),2), Sub142(HelDim(2),2)
	HelType Sub144(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub240(HelDim(2),2), Sub237(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub149(HelDim(2),2)
	HelType Sub152(HelDim(2),2), Sub156(HelDim(2),2)
	HelType Sub235(HelDim(2),2), Sub159(HelDim(2),2)
	HelType Sub161(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub282(HelDim(2),2)
	HelType Sub286(HelDim(2),2), Sub284(HelDim(2),2)
	HelType Sub258(HelDim(2),2), Sub259(HelDim(2),2)
	HelType Sub261(HelDim(2),2), Sub263(HelDim(2),2)
	HelType Sub265(HelDim(2),2), Sub267(HelDim(2),2)
	HelType Sub269(HelDim(2),2), Sub271(HelDim(2),2)
	HelType Sub272(HelDim(2),2), Sub287(HelDim(2),2)
	HelType Sub242(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub238(HelDim(2),2), Sub239(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub241(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub264(HelDim(2),2)
	HelType Sub270(HelDim(2),2), Sub151(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub136(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub160(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub236(HelDim(2),2)
	HelType Sub154(HelDim(2),2), Sub155(HelDim(2),2)
	HelType Sub139(HelDim(2),2), Sub150(HelDim(2),2)
	HelType Sub143(HelDim(2),2), Sub158(HelDim(2),2)
	HelType Sub162(HelDim(2),2), Sub244, Sub170, Sub173, Sub243
	HelType Sub169, Sub172, Sub290(HelDim(2)), Sub135(HelDim(2))
	HelType Sub106(HelDim(2)), Sub288(HelDim(2),2)
	HelType Sub285(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub182, Sub186
	HelType Sub291(HelDim(2)), Sub283(HelDim(2),2)
	common /varXh/ F1, F4, F7, F9, F5, F2, F11, F6, F10, F12, F3
	common /varXh/ F8, Sub15, F16, F21, F13, F24, F27, F20, F23
	common /varXh/ F19, F25, F22, F14, F15, F34, F32, F40, F38
	common /varXh/ F26, F29, F33, F42, F39, F28, F41, F30, F36
	common /varXh/ F31, F17, F37, F18, F35, Sub166, Sub220
	common /varXh/ Sub216, Sub228, Sub230, Sub232, Sub231
	common /varXh/ Sub219, Sub218, Sub204, Sub205, Sub206
	common /varXh/ Sub207, Sub199, Sub198, Sub201, Sub189
	common /varXh/ Sub191, Sub183, Sub185, Sub224, Sub222
	common /varXh/ Sub227, Sub229, Sub193, Sub190, Sub210
	common /varXh/ Sub212, Sub217, Sub215, Sub176, Sub289
	common /varXh/ Sub196, Sub226, Sub177, Sub178, Sub184
	common /varXh/ Sub187, Sub200, Sub202, Sub211, Sub213
	common /varXh/ Sub124, Sub134, Sub179, Sub188, Sub214
	common /varXh/ Sub181, Sub203, Sub221, Sub277, Sub175
	common /varXh/ Sub174, Sub192, Sub223, Sub194, Sub225
	common /varXh/ Sub195, Sub180, Sub75, Sub105, Sub281, Sub208
	common /varXh/ Sub233, Sub257, Sub142, Sub144, Sub250
	common /varXh/ Sub248, Sub245, Sub240, Sub237, Sub246
	common /varXh/ Sub149, Sub152, Sub156, Sub235, Sub159
	common /varXh/ Sub161, Sub163, Sub168, Sub282, Sub286
	common /varXh/ Sub284, Sub258, Sub259, Sub261, Sub263
	common /varXh/ Sub265, Sub267, Sub269, Sub271, Sub272
	common /varXh/ Sub287, Sub242, Sub247, Sub238, Sub239
	common /varXh/ Sub249, Sub241, Sub234, Sub264, Sub270
	common /varXh/ Sub151, Sub157, Sub136, Sub167, Sub160
	common /varXh/ Sub171, Sub236, Sub154, Sub155, Sub139
	common /varXh/ Sub150, Sub143, Sub158, Sub162, Sub244
	common /varXh/ Sub170, Sub173, Sub243, Sub169, Sub172
	common /varXh/ Sub290, Sub135, Sub106, Sub288, Sub285
	common /varXh/ Sub251, Sub252, Sub182, Sub186, Sub291, Sub283

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n1n3_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
