#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 5-Mar-2015 14:01
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub2, Sub8, Sub1(2), Sub5(2), Sub3(2)
	ComplexType Sub6(2)
	ComplexType Sub36, Sub121, Sub122, Sub76, Sub91, Sub35, Sub46
	ComplexType Sub77, Sub92, Sub60, Sub50, Sub51, Sub90, Sub88
	ComplexType Sub75, Sub70, Sub72, Sub39, Sub40, Sub56, Sub62
	ComplexType Sub48, Sub63, Sub64, Sub61, Sub43, Sub44, Sub52
	ComplexType Sub54, Sub53, Sub80, Sub81, Sub82, Sub45(2)
	ComplexType Sub67(2), Sub86(2), Sub69(2), Sub74(2), Sub49(2)
	ComplexType Sub71(2), Sub73(2), Sub78(2), Sub85(2), Sub57(2)
	ComplexType Sub58(2), Sub93(2), Sub65(2), Sub89(2), Sub95(2)
	ComplexType Sub66(2), Sub59(2), Sub42(2), Sub87(2), Sub97(2)
	ComplexType Sub79(2), Sub96(2), Sub105(2), Sub14(2)
	ComplexType Sub108(2), Sub15(2), Sub10(2,2), Sub205(2,2)
	ComplexType Sub23(2,2), Sub103(2,2), Sub106(2,2)
	ComplexType Sub116(2,2), Sub26(2,2), Sub27(2,2)
	ComplexType Sub33(2,2,2), Sub37, Sub222, Sub38, Sub9(2,2)
	ComplexType Sub83, Sub34, Sub55, Sub41, Sub47, Sub94, Sub84
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave16(Ncc,2,2), pave17, pave18(Ncc,2)
	common /varXs/ Sub4, Sub2, Sub8, Sub1, Sub5, Sub3, Sub6
	common /varXs/ Sub36, Sub121, Sub122, Sub76, Sub91, Sub35
	common /varXs/ Sub46, Sub77, Sub92, Sub60, Sub50, Sub51
	common /varXs/ Sub90, Sub88, Sub75, Sub70, Sub72, Sub39
	common /varXs/ Sub40, Sub56, Sub62, Sub48, Sub63, Sub64
	common /varXs/ Sub61, Sub43, Sub44, Sub52, Sub54, Sub53
	common /varXs/ Sub80, Sub81, Sub82, Sub45, Sub67, Sub86
	common /varXs/ Sub69, Sub74, Sub49, Sub71, Sub73, Sub78
	common /varXs/ Sub85, Sub57, Sub58, Sub93, Sub65, Sub89
	common /varXs/ Sub95, Sub66, Sub59, Sub42, Sub87, Sub97
	common /varXs/ Sub79, Sub96, Sub105, Sub14, Sub108, Sub15
	common /varXs/ Sub10, Sub205, Sub23, Sub103, Sub106, Sub116
	common /varXs/ Sub26, Sub27, Sub33, Sub37, Sub222, Sub38
	common /varXs/ Sub9, Sub83, Sub34, Sub55, Sub41, Sub47
	common /varXs/ Sub94, Sub84, pave1, pave2, pave3, pave16
	common /varXs/ pave17, pave18

	ComplexType Sub226(2), Sub223(2), Sub227(2), Sub224(2)
	ComplexType Sub210(2), Sub209(2), Sub217(2), Sub214(2)
	ComplexType Sub216(2), Sub213(2), Sub230(2,2), Sub231(2,2)
	ComplexType Sub211(2,2), Sub212(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub242(2), Sub240(2), Sub177, pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Ndd,2), pave7(Ndd,2)
	ComplexType pave8(Nbb,2), pave9(Ncc,2), pave10(Nbb,2)
	ComplexType pave11(Ncc,2), pave12(Ncc,2), pave13(Ncc,2)
	ComplexType pave14(Nbb), pave15(Nbb)
	RealType S, T, U
	common /varXa/ Sub226, Sub223, Sub227, Sub224, Sub210, Sub209
	common /varXa/ Sub217, Sub214, Sub216, Sub213, Sub230
	common /varXa/ Sub231, Sub211, Sub212, Sub24, Sub25, Sub242
	common /varXa/ Sub240, Sub177, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave14, pave15, S, T, U

	HelType F4, F6, F3, F9, F7, F1, F12, F8, F10, F11, F2, F5
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F20, F19, F25, F22, F14
	HelType F15, F39, F41, F37, F35, F26, F38, F42, F40, F36
	HelType F28, F32, F33, F29, F34, F17, F30, F18, F31, Sub147
	HelType Sub152, Sub155, Sub144, Sub123, Sub178, Sub180
	HelType Sub188, Sub189, Sub179, Sub181, Sub191, Sub190
	HelType Sub173, Sub157, Sub171, Sub170, Sub154, Sub174
	HelType Sub149, Sub146, Sub165, Sub166, Sub168, Sub167
	HelType Sub148, Sub156, Sub238(HelDim(2)), Sub133(HelDim(2))
	HelType Sub139(HelDim(2)), Sub136(HelDim(2))
	HelType Sub140(HelDim(2)), Sub134(HelDim(2))
	HelType Sub137(HelDim(2)), Sub172(HelDim(2))
	HelType Sub175(HelDim(2)), Sub158(HelDim(2))
	HelType Sub150(HelDim(2)), Sub135(HelDim(2))
	HelType Sub138(HelDim(2)), Sub141(HelDim(2))
	HelType Sub151(HelDim(2)), Sub159(HelDim(2))
	HelType Sub176(HelDim(2)), Sub142(HelDim(2))
	HelType Sub143(HelDim(2)), Sub164(HelDim(2))
	HelType Sub169(HelDim(2)), Sub182(HelDim(2))
	HelType Sub187(HelDim(2)), Sub192(HelDim(2))
	HelType Sub225(HelDim(2)), Sub241(HelDim(2))
	HelType Sub243(HelDim(2)), Sub68(HelDim(2))
	HelType Sub100(HelDim(2)), Sub98(HelDim(2))
	HelType Sub101(HelDim(2)), Sub228(HelDim(2))
	HelType Sub119(HelDim(2),2), Sub120(HelDim(2),2)
	HelType Sub128(HelDim(2),2), Sub129(HelDim(2),2)
	HelType Sub235(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub218(HelDim(2),2)
	HelType Sub219(HelDim(2),2), Sub221(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub236(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub204(HelDim(2),2)
	HelType Sub206(HelDim(2),2), Sub201(HelDim(2),2)
	HelType Sub199(HelDim(2),2), Sub198(HelDim(2),2)
	HelType Sub200(HelDim(2),2), Sub202(HelDim(2),2)
	HelType Sub203(HelDim(2),2), Sub196(HelDim(2),2)
	HelType Sub195(HelDim(2),2), Sub117(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub115(HelDim(2),2), Sub124(HelDim(2),2)
	HelType Sub114(HelDim(2),2), Sub107(HelDim(2),2)
	HelType Sub111(HelDim(2),2), Sub130(HelDim(2),2)
	HelType Sub194(HelDim(2),2), Sub197(HelDim(2),2)
	HelType Sub193(HelDim(2),2), Sub104(HelDim(2),2)
	HelType Sub109(HelDim(2),2), Sub112(HelDim(2),2)
	HelType Sub127(HelDim(2),2), Sub118(HelDim(2),2), Sub131
	HelType Sub132, Sub161, Sub160, Sub185, Sub184, Sub186
	HelType Sub183, Sub162, Sub163, Sub145, Sub153
	HelType Sub102(HelDim(2)), Sub99(HelDim(2))
	HelType Sub220(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub110(HelDim(2),2)
	HelType Sub208(HelDim(2),2), Sub207(HelDim(2),2)
	HelType Sub239(HelDim(2)), Sub229(HelDim(2),2)
	common /varXh/ F4, F6, F3, F9, F7, F1, F12, F8, F10, F11, F2
	common /varXh/ F5, Sub7, F16, F21, F13, F24, F27, F23, F20
	common /varXh/ F19, F25, F22, F14, F15, F39, F41, F37, F35
	common /varXh/ F26, F38, F42, F40, F36, F28, F32, F33, F29
	common /varXh/ F34, F17, F30, F18, F31, Sub147, Sub152
	common /varXh/ Sub155, Sub144, Sub123, Sub178, Sub180
	common /varXh/ Sub188, Sub189, Sub179, Sub181, Sub191
	common /varXh/ Sub190, Sub173, Sub157, Sub171, Sub170
	common /varXh/ Sub154, Sub174, Sub149, Sub146, Sub165
	common /varXh/ Sub166, Sub168, Sub167, Sub148, Sub156
	common /varXh/ Sub238, Sub133, Sub139, Sub136, Sub140
	common /varXh/ Sub134, Sub137, Sub172, Sub175, Sub158
	common /varXh/ Sub150, Sub135, Sub138, Sub141, Sub151
	common /varXh/ Sub159, Sub176, Sub142, Sub143, Sub164
	common /varXh/ Sub169, Sub182, Sub187, Sub192, Sub225
	common /varXh/ Sub241, Sub243, Sub68, Sub100, Sub98, Sub101
	common /varXh/ Sub228, Sub119, Sub120, Sub128, Sub129
	common /varXh/ Sub235, Sub234, Sub215, Sub218, Sub219
	common /varXh/ Sub221, Sub233, Sub236, Sub237, Sub204
	common /varXh/ Sub206, Sub201, Sub199, Sub198, Sub200
	common /varXh/ Sub202, Sub203, Sub196, Sub195, Sub117
	common /varXh/ Sub126, Sub125, Sub115, Sub124, Sub114
	common /varXh/ Sub107, Sub111, Sub130, Sub194, Sub197
	common /varXh/ Sub193, Sub104, Sub109, Sub112, Sub127
	common /varXh/ Sub118, Sub131, Sub132, Sub161, Sub160
	common /varXh/ Sub185, Sub184, Sub186, Sub183, Sub162
	common /varXh/ Sub163, Sub145, Sub153, Sub102, Sub99, Sub220
	common /varXh/ Sub232, Sub113, Sub110, Sub208, Sub207
	common /varXh/ Sub239, Sub229

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n1n1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
