#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:54
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7(2)
	ComplexType Sub2(2), Sub4(2), Sub11(2), Sub9(2), Sub3(2)
	ComplexType Sub6(2), Sub12(2)
	ComplexType Sub43, Sub166, Sub167, Sub83, Sub97, Sub42, Sub53
	ComplexType Sub84, Sub98, Sub66, Sub57, Sub58, Sub96, Sub94
	ComplexType Sub82, Sub77, Sub79, Sub46, Sub47, Sub59, Sub60
	ComplexType Sub115, Sub118, Sub55, Sub119, Sub120, Sub117
	ComplexType Sub50, Sub51, Sub62, Sub69, Sub109, Sub70, Sub71
	ComplexType Sub68, Sub110, Sub111, Sub87, Sub88, Sub112(2)
	ComplexType Sub52(2), Sub132(2), Sub123(2), Sub74(2)
	ComplexType Sub92(2), Sub76(2), Sub81(2), Sub113(2)
	ComplexType Sub56(2), Sub78(2), Sub80(2), Sub131(2)
	ComplexType Sub85(2), Sub91(2), Sub63(2), Sub64(2), Sub99(2)
	ComplexType Sub121(2), Sub72(2), Sub95(2), Sub102(2)
	ComplexType Sub126(2), Sub122(2), Sub116(2), Sub49(2)
	ComplexType Sub73(2), Sub65(2), Sub108(2), Sub93(2)
	ComplexType Sub128(2), Sub86(2), Sub127(2), Sub133(2)
	ComplexType Sub104(2), Sub129(2), Sub103(2), Sub150(2)
	ComplexType Sub30(2), Sub140(2), Sub20(2), Sub152(2)
	ComplexType Sub31(2), Sub141(2), Sub21(2), Sub17(2,2)
	ComplexType Sub32(2,2), Sub136(2,2), Sub151(2,2)
	ComplexType Sub145(2,2), Sub146(2,2), Sub153(2,2)
	ComplexType Sub33(2,2), Sub34(2,2), Sub40(2,2,2), Sub44
	ComplexType Sub273, Sub45, Sub16(2,2), Sub89, Sub130, Sub41
	ComplexType Sub114, Sub61, Sub48, Sub107, Sub54, Sub67
	ComplexType Sub125, Sub100, Sub90, Sub101, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave12(Ncc,2)
	ComplexType pave13(Ncc,2), pave20(Ncc,2,2), pave23
	common /varXs/ Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7
	common /varXs/ Sub2, Sub4, Sub11, Sub9, Sub3, Sub6, Sub12
	common /varXs/ Sub43, Sub166, Sub167, Sub83, Sub97, Sub42
	common /varXs/ Sub53, Sub84, Sub98, Sub66, Sub57, Sub58
	common /varXs/ Sub96, Sub94, Sub82, Sub77, Sub79, Sub46
	common /varXs/ Sub47, Sub59, Sub60, Sub115, Sub118, Sub55
	common /varXs/ Sub119, Sub120, Sub117, Sub50, Sub51, Sub62
	common /varXs/ Sub69, Sub109, Sub70, Sub71, Sub68, Sub110
	common /varXs/ Sub111, Sub87, Sub88, Sub112, Sub52, Sub132
	common /varXs/ Sub123, Sub74, Sub92, Sub76, Sub81, Sub113
	common /varXs/ Sub56, Sub78, Sub80, Sub131, Sub85, Sub91
	common /varXs/ Sub63, Sub64, Sub99, Sub121, Sub72, Sub95
	common /varXs/ Sub102, Sub126, Sub122, Sub116, Sub49, Sub73
	common /varXs/ Sub65, Sub108, Sub93, Sub128, Sub86, Sub127
	common /varXs/ Sub133, Sub104, Sub129, Sub103, Sub150, Sub30
	common /varXs/ Sub140, Sub20, Sub152, Sub31, Sub141, Sub21
	common /varXs/ Sub17, Sub32, Sub136, Sub151, Sub145, Sub146
	common /varXs/ Sub153, Sub33, Sub34, Sub40, Sub44, Sub273
	common /varXs/ Sub45, Sub16, Sub89, Sub130, Sub41, Sub114
	common /varXs/ Sub61, Sub48, Sub107, Sub54, Sub67, Sub125
	common /varXs/ Sub100, Sub90, Sub101, pave1, pave2, pave3
	common /varXs/ pave12, pave13, pave20, pave23

	ComplexType Sub279(2), Sub275(2), Sub292(2), Sub290(2)
	ComplexType Sub293(2), Sub291(2), Sub278(2), Sub274(2)
	ComplexType Sub254(2), Sub253(2), Sub266(2), Sub268(2)
	ComplexType Sub262(2), Sub260(2), Sub256(2,2), Sub255(2,2)
	ComplexType Sub216, Sub197, Sub276(2), Sub280(2)
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave7(Ndd,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ncc,2), pave11(Ncc,2), pave14(Nbb,2)
	ComplexType pave15(Nbb,2), pave16(Ncc,2), pave17(Ncc,2)
	ComplexType pave18(Ncc,2), pave19(Ncc,2), pave21(Nbb)
	ComplexType pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub279, Sub275, Sub292, Sub290, Sub293, Sub291
	common /varXa/ Sub278, Sub274, Sub254, Sub253, Sub266
	common /varXa/ Sub268, Sub262, Sub260, Sub256, Sub255
	common /varXa/ Sub216, Sub197, Sub276, Sub280, pave4, pave5
	common /varXa/ pave6, pave7, pave8, pave9, pave10, pave11
	common /varXa/ pave14, pave15, pave16, pave17, pave18
	common /varXa/ pave19, pave21, pave22, S, T, U

	HelType F5, F3, F7, F9, F4, F1, F11, F6, F10, F12, F2, F8
	HelType Sub15
	HelType F16, F20, F13, F23, F25, F26, F27, F19, F24, F21, F14
	HelType F15, F34, F31, F40, F38, F22, F33, F32, F41, F39
	HelType F28, F42, F29, F36, F30, F17, F37, F18, F35, Sub168
	HelType Sub214, Sub210, Sub228, Sub230, Sub231, Sub232
	HelType Sub213, Sub212, Sub222, Sub223, Sub224, Sub225
	HelType Sub199, Sub198, Sub201, Sub189, Sub191, Sub183
	HelType Sub185, Sub206, Sub204, Sub227, Sub229, Sub193
	HelType Sub190, Sub217, Sub219, Sub211, Sub209
	HelType Sub179(HelDim(2)), Sub287(HelDim(2))
	HelType Sub196(HelDim(2)), Sub208(HelDim(2))
	HelType Sub174(HelDim(2)), Sub175(HelDim(2))
	HelType Sub184(HelDim(2)), Sub187(HelDim(2))
	HelType Sub200(HelDim(2)), Sub202(HelDim(2))
	HelType Sub218(HelDim(2)), Sub220(HelDim(2))
	HelType Sub124(HelDim(2)), Sub134(HelDim(2))
	HelType Sub176(HelDim(2)), Sub188(HelDim(2))
	HelType Sub221(HelDim(2)), Sub180(HelDim(2))
	HelType Sub203(HelDim(2)), Sub215(HelDim(2))
	HelType Sub277(HelDim(2)), Sub178(HelDim(2))
	HelType Sub177(HelDim(2)), Sub192(HelDim(2))
	HelType Sub205(HelDim(2)), Sub194(HelDim(2))
	HelType Sub207(HelDim(2)), Sub195(HelDim(2))
	HelType Sub181(HelDim(2)), Sub75(HelDim(2))
	HelType Sub105(HelDim(2)), Sub281(HelDim(2))
	HelType Sub226(HelDim(2)), Sub233(HelDim(2))
	HelType Sub257(HelDim(2),2), Sub139(HelDim(2),2)
	HelType Sub147(HelDim(2),2), Sub149(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub242(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub154(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub159(HelDim(2),2)
	HelType Sub161(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub165(HelDim(2),2), Sub284(HelDim(2),2)
	HelType Sub258(HelDim(2),2), Sub259(HelDim(2),2)
	HelType Sub261(HelDim(2),2), Sub263(HelDim(2),2)
	HelType Sub265(HelDim(2),2), Sub267(HelDim(2),2)
	HelType Sub269(HelDim(2),2), Sub271(HelDim(2),2)
	HelType Sub272(HelDim(2),2), Sub285(HelDim(2),2)
	HelType Sub239(HelDim(2),2), Sub241(HelDim(2),2)
	HelType Sub238(HelDim(2),2), Sub240(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub235(HelDim(2),2), Sub264(HelDim(2),2)
	HelType Sub270(HelDim(2),2), Sub156(HelDim(2),2)
	HelType Sub144(HelDim(2),2), Sub143(HelDim(2),2)
	HelType Sub164(HelDim(2),2), Sub160(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub137(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub138(HelDim(2),2)
	HelType Sub142(HelDim(2),2), Sub155(HelDim(2),2)
	HelType Sub148(HelDim(2),2), Sub158(HelDim(2),2)
	HelType Sub162(HelDim(2),2), Sub244, Sub170, Sub173, Sub243
	HelType Sub169, Sub172, Sub288(HelDim(2)), Sub135(HelDim(2))
	HelType Sub106(HelDim(2)), Sub286(HelDim(2),2)
	HelType Sub283(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub182, Sub186
	HelType Sub289(HelDim(2)), Sub282(HelDim(2),2)
	common /varXh/ F5, F3, F7, F9, F4, F1, F11, F6, F10, F12, F2
	common /varXh/ F8, Sub15, F16, F20, F13, F23, F25, F26, F27
	common /varXh/ F19, F24, F21, F14, F15, F34, F31, F40, F38
	common /varXh/ F22, F33, F32, F41, F39, F28, F42, F29, F36
	common /varXh/ F30, F17, F37, F18, F35, Sub168, Sub214
	common /varXh/ Sub210, Sub228, Sub230, Sub231, Sub232
	common /varXh/ Sub213, Sub212, Sub222, Sub223, Sub224
	common /varXh/ Sub225, Sub199, Sub198, Sub201, Sub189
	common /varXh/ Sub191, Sub183, Sub185, Sub206, Sub204
	common /varXh/ Sub227, Sub229, Sub193, Sub190, Sub217
	common /varXh/ Sub219, Sub211, Sub209, Sub179, Sub287
	common /varXh/ Sub196, Sub208, Sub174, Sub175, Sub184
	common /varXh/ Sub187, Sub200, Sub202, Sub218, Sub220
	common /varXh/ Sub124, Sub134, Sub176, Sub188, Sub221
	common /varXh/ Sub180, Sub203, Sub215, Sub277, Sub178
	common /varXh/ Sub177, Sub192, Sub205, Sub194, Sub207
	common /varXh/ Sub195, Sub181, Sub75, Sub105, Sub281, Sub226
	common /varXh/ Sub233, Sub257, Sub139, Sub147, Sub149
	common /varXh/ Sub249, Sub247, Sub245, Sub242, Sub237
	common /varXh/ Sub250, Sub234, Sub154, Sub157, Sub159
	common /varXh/ Sub161, Sub163, Sub165, Sub284, Sub258
	common /varXh/ Sub259, Sub261, Sub263, Sub265, Sub267
	common /varXh/ Sub269, Sub271, Sub272, Sub285, Sub239
	common /varXh/ Sub241, Sub238, Sub240, Sub248, Sub246
	common /varXh/ Sub235, Sub264, Sub270, Sub156, Sub144
	common /varXh/ Sub143, Sub164, Sub160, Sub171, Sub137
	common /varXh/ Sub236, Sub138, Sub142, Sub155, Sub148
	common /varXh/ Sub158, Sub162, Sub244, Sub170, Sub173
	common /varXh/ Sub243, Sub169, Sub172, Sub288, Sub135
	common /varXh/ Sub106, Sub286, Sub283, Sub251, Sub252
	common /varXh/ Sub182, Sub186, Sub289, Sub282

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n3n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
