#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:52
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub2, Sub8, Sub1(2), Sub5(2), Sub3(2)
	ComplexType Sub6(2)
	ComplexType Sub36, Sub127, Sub128, Sub76, Sub91, Sub35, Sub46
	ComplexType Sub77, Sub92, Sub60, Sub50, Sub51, Sub90, Sub88
	ComplexType Sub75, Sub70, Sub72, Sub39, Sub40, Sub52, Sub53
	ComplexType Sub56, Sub62, Sub48, Sub63, Sub64, Sub61, Sub43
	ComplexType Sub44, Sub54, Sub80, Sub81, Sub82, Sub45(2)
	ComplexType Sub67(2), Sub86(2), Sub69(2), Sub74(2), Sub49(2)
	ComplexType Sub71(2), Sub73(2), Sub78(2), Sub85(2), Sub57(2)
	ComplexType Sub58(2), Sub93(2), Sub65(2), Sub89(2), Sub95(2)
	ComplexType Sub66(2), Sub59(2), Sub42(2), Sub87(2), Sub97(2)
	ComplexType Sub79(2), Sub96(2), Sub103(2), Sub14(2)
	ComplexType Sub106(2), Sub15(2), Sub10(2,2), Sub204(2,2)
	ComplexType Sub23(2,2), Sub109(2,2), Sub104(2,2)
	ComplexType Sub116(2,2), Sub26(2,2), Sub27(2,2)
	ComplexType Sub33(2,2,2), Sub37, Sub221, Sub38, Sub9(2,2)
	ComplexType Sub83, Sub34, Sub55, Sub41, Sub47, Sub94, Sub84
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave16(Ncc,2,2), pave17, pave18(Ncc,2)
	common /varXs/ Sub4, Sub2, Sub8, Sub1, Sub5, Sub3, Sub6
	common /varXs/ Sub36, Sub127, Sub128, Sub76, Sub91, Sub35
	common /varXs/ Sub46, Sub77, Sub92, Sub60, Sub50, Sub51
	common /varXs/ Sub90, Sub88, Sub75, Sub70, Sub72, Sub39
	common /varXs/ Sub40, Sub52, Sub53, Sub56, Sub62, Sub48
	common /varXs/ Sub63, Sub64, Sub61, Sub43, Sub44, Sub54
	common /varXs/ Sub80, Sub81, Sub82, Sub45, Sub67, Sub86
	common /varXs/ Sub69, Sub74, Sub49, Sub71, Sub73, Sub78
	common /varXs/ Sub85, Sub57, Sub58, Sub93, Sub65, Sub89
	common /varXs/ Sub95, Sub66, Sub59, Sub42, Sub87, Sub97
	common /varXs/ Sub79, Sub96, Sub103, Sub14, Sub106, Sub15
	common /varXs/ Sub10, Sub204, Sub23, Sub109, Sub104, Sub116
	common /varXs/ Sub26, Sub27, Sub33, Sub37, Sub221, Sub38
	common /varXs/ Sub9, Sub83, Sub34, Sub55, Sub41, Sub47
	common /varXs/ Sub94, Sub84, pave1, pave2, pave3, pave16
	common /varXs/ pave17, pave18

	ComplexType Sub225(2), Sub222(2), Sub226(2), Sub223(2)
	ComplexType Sub208(2), Sub209(2), Sub213(2), Sub216(2)
	ComplexType Sub212(2), Sub215(2), Sub231(2,2), Sub210(2,2)
	ComplexType Sub211(2,2), Sub24(2,2), Sub25(2,2), Sub240(2)
	ComplexType Sub241(2), Sub152, pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Ndd,2), pave7(Ndd,2)
	ComplexType pave8(Nbb,2), pave9(Ncc,2), pave10(Nbb,2)
	ComplexType pave11(Ncc,2), pave12(Ncc,2), pave13(Ncc,2)
	ComplexType pave14(Nbb), pave15(Nbb)
	RealType S, T, U
	common /varXa/ Sub225, Sub222, Sub226, Sub223, Sub208, Sub209
	common /varXa/ Sub213, Sub216, Sub212, Sub215, Sub231
	common /varXa/ Sub210, Sub211, Sub24, Sub25, Sub240, Sub241
	common /varXa/ Sub152, pave4, pave5, pave6, pave7, pave8
	common /varXa/ pave9, pave10, pave11, pave12, pave13, pave14
	common /varXa/ pave15, S, T, U

	HelType F1, F5, F7, F9, F6, F2, F11, F4, F12, F10, F3, F8
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F19, F20, F25, F22, F14
	HelType F15, F33, F41, F35, F39, F26, F32, F42, F36, F40
	HelType F28, F30, F37, F29, F38, F17, F31, F18, F34, Sub146
	HelType Sub158, Sub161, Sub143, Sub129, Sub181, Sub154
	HelType Sub153, Sub183, Sub182, Sub184, Sub156, Sub155
	HelType Sub188, Sub163, Sub187, Sub186, Sub160, Sub189
	HelType Sub145, Sub176, Sub177, Sub148, Sub179, Sub178
	HelType Sub147, Sub162, Sub136(HelDim(2)), Sub139(HelDim(2))
	HelType Sub140(HelDim(2)), Sub133(HelDim(2))
	HelType Sub137(HelDim(2)), Sub134(HelDim(2))
	HelType Sub190(HelDim(2)), Sub164(HelDim(2))
	HelType Sub149(HelDim(2)), Sub135(HelDim(2))
	HelType Sub138(HelDim(2)), Sub141(HelDim(2))
	HelType Sub150(HelDim(2)), Sub165(HelDim(2))
	HelType Sub191(HelDim(2)), Sub142(HelDim(2))
	HelType Sub151(HelDim(2)), Sub157(HelDim(2))
	HelType Sub170(HelDim(2)), Sub175(HelDim(2))
	HelType Sub180(HelDim(2)), Sub185(HelDim(2))
	HelType Sub224(HelDim(2)), Sub242(HelDim(2))
	HelType Sub68(HelDim(2)), Sub100(HelDim(2))
	HelType Sub98(HelDim(2)), Sub101(HelDim(2))
	HelType Sub227(HelDim(2)), Sub119(HelDim(2),2)
	HelType Sub120(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub236(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub217(HelDim(2),2), Sub218(HelDim(2),2)
	HelType Sub220(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub202(HelDim(2),2)
	HelType Sub205(HelDim(2),2), Sub199(HelDim(2),2)
	HelType Sub198(HelDim(2),2), Sub197(HelDim(2),2)
	HelType Sub200(HelDim(2),2), Sub201(HelDim(2),2)
	HelType Sub203(HelDim(2),2), Sub195(HelDim(2),2)
	HelType Sub194(HelDim(2),2), Sub123(HelDim(2),2)
	HelType Sub117(HelDim(2),2), Sub115(HelDim(2),2)
	HelType Sub122(HelDim(2),2), Sub114(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub105(HelDim(2),2)
	HelType Sub111(HelDim(2),2), Sub131(HelDim(2),2)
	HelType Sub196(HelDim(2),2), Sub193(HelDim(2),2)
	HelType Sub192(HelDim(2),2), Sub110(HelDim(2),2)
	HelType Sub107(HelDim(2),2), Sub112(HelDim(2),2)
	HelType Sub118(HelDim(2),2), Sub124(HelDim(2),2), Sub130
	HelType Sub132, Sub167, Sub166, Sub171, Sub173, Sub172
	HelType Sub174, Sub169, Sub168, Sub144, Sub159
	HelType Sub102(HelDim(2)), Sub99(HelDim(2))
	HelType Sub219(HelDim(2),2), Sub108(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub206(HelDim(2),2)
	HelType Sub207(HelDim(2),2), Sub239(HelDim(2))
	HelType Sub238(HelDim(2)), Sub229(HelDim(2),2)
	common /varXh/ F1, F5, F7, F9, F6, F2, F11, F4, F12, F10, F3
	common /varXh/ F8, Sub7, F16, F21, F13, F24, F27, F23, F19
	common /varXh/ F20, F25, F22, F14, F15, F33, F41, F35, F39
	common /varXh/ F26, F32, F42, F36, F40, F28, F30, F37, F29
	common /varXh/ F38, F17, F31, F18, F34, Sub146, Sub158
	common /varXh/ Sub161, Sub143, Sub129, Sub181, Sub154
	common /varXh/ Sub153, Sub183, Sub182, Sub184, Sub156
	common /varXh/ Sub155, Sub188, Sub163, Sub187, Sub186
	common /varXh/ Sub160, Sub189, Sub145, Sub176, Sub177
	common /varXh/ Sub148, Sub179, Sub178, Sub147, Sub162
	common /varXh/ Sub136, Sub139, Sub140, Sub133, Sub137
	common /varXh/ Sub134, Sub190, Sub164, Sub149, Sub135
	common /varXh/ Sub138, Sub141, Sub150, Sub165, Sub191
	common /varXh/ Sub142, Sub151, Sub157, Sub170, Sub175
	common /varXh/ Sub180, Sub185, Sub224, Sub242, Sub68, Sub100
	common /varXh/ Sub98, Sub101, Sub227, Sub119, Sub120, Sub125
	common /varXh/ Sub126, Sub228, Sub230, Sub236, Sub234
	common /varXh/ Sub214, Sub217, Sub218, Sub220, Sub232
	common /varXh/ Sub233, Sub235, Sub237, Sub202, Sub205
	common /varXh/ Sub199, Sub198, Sub197, Sub200, Sub201
	common /varXh/ Sub203, Sub195, Sub194, Sub123, Sub117
	common /varXh/ Sub115, Sub122, Sub114, Sub121, Sub105
	common /varXh/ Sub111, Sub131, Sub196, Sub193, Sub192
	common /varXh/ Sub110, Sub107, Sub112, Sub118, Sub124
	common /varXh/ Sub130, Sub132, Sub167, Sub166, Sub171
	common /varXh/ Sub173, Sub172, Sub174, Sub169, Sub168
	common /varXh/ Sub144, Sub159, Sub102, Sub99, Sub219, Sub108
	common /varXh/ Sub113, Sub206, Sub207, Sub239, Sub238, Sub229

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n3n3_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
