#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 10-Jun-2015 12:08
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub10, Sub4, Sub2, Sub7, Sub14, Sub8, Sub1(2)
	ComplexType Sub11(2), Sub13(2), Sub5(2), Sub3(2), Sub12(2)
	ComplexType Sub15(2), Sub6(2)
	ComplexType Sub43, Sub164, Sub165, Sub83, Sub97, Sub42, Sub53
	ComplexType Sub84, Sub98, Sub66, Sub57, Sub58, Sub96, Sub94
	ComplexType Sub82, Sub77, Sub79, Sub46, Sub47, Sub115
	ComplexType Sub118, Sub55, Sub119, Sub120, Sub117, Sub50
	ComplexType Sub51, Sub62, Sub69, Sub112, Sub70, Sub71, Sub68
	ComplexType Sub109, Sub110, Sub60, Sub59, Sub87, Sub88
	ComplexType Sub111(2), Sub52(2), Sub123(2), Sub132(2)
	ComplexType Sub74(2), Sub92(2), Sub76(2), Sub81(2)
	ComplexType Sub113(2), Sub56(2), Sub78(2), Sub80(2)
	ComplexType Sub131(2), Sub85(2), Sub91(2), Sub63(2)
	ComplexType Sub64(2), Sub99(2), Sub121(2), Sub72(2)
	ComplexType Sub95(2), Sub102(2), Sub126(2), Sub122(2)
	ComplexType Sub116(2), Sub49(2), Sub73(2), Sub65(2)
	ComplexType Sub108(2), Sub93(2), Sub128(2), Sub86(2)
	ComplexType Sub127(2), Sub133(2), Sub104(2), Sub129(2)
	ComplexType Sub103(2), Sub149(2), Sub25(2), Sub141(2)
	ComplexType Sub21(2), Sub151(2), Sub26(2), Sub142(2)
	ComplexType Sub22(2), Sub17(2,2), Sub32(2,2), Sub136(2,2)
	ComplexType Sub144(2,2), Sub150(2,2), Sub145(2,2)
	ComplexType Sub152(2,2), Sub33(2,2), Sub34(2,2)
	ComplexType Sub40(2,2,2), Sub44, Sub273, Sub45, Sub16(2,2)
	ComplexType Sub89, Sub130, Sub41, Sub114, Sub61, Sub48
	ComplexType Sub107, Sub54, Sub67, Sub125, Sub100, Sub90
	ComplexType Sub101, pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave12(Ncc,2), pave19(Ncc,2,2), pave22
	ComplexType pave23(Ncc,2)
	common /varXs/ Sub10, Sub4, Sub2, Sub7, Sub14, Sub8, Sub1
	common /varXs/ Sub11, Sub13, Sub5, Sub3, Sub12, Sub15, Sub6
	common /varXs/ Sub43, Sub164, Sub165, Sub83, Sub97, Sub42
	common /varXs/ Sub53, Sub84, Sub98, Sub66, Sub57, Sub58
	common /varXs/ Sub96, Sub94, Sub82, Sub77, Sub79, Sub46
	common /varXs/ Sub47, Sub115, Sub118, Sub55, Sub119, Sub120
	common /varXs/ Sub117, Sub50, Sub51, Sub62, Sub69, Sub112
	common /varXs/ Sub70, Sub71, Sub68, Sub109, Sub110, Sub60
	common /varXs/ Sub59, Sub87, Sub88, Sub111, Sub52, Sub123
	common /varXs/ Sub132, Sub74, Sub92, Sub76, Sub81, Sub113
	common /varXs/ Sub56, Sub78, Sub80, Sub131, Sub85, Sub91
	common /varXs/ Sub63, Sub64, Sub99, Sub121, Sub72, Sub95
	common /varXs/ Sub102, Sub126, Sub122, Sub116, Sub49, Sub73
	common /varXs/ Sub65, Sub108, Sub93, Sub128, Sub86, Sub127
	common /varXs/ Sub133, Sub104, Sub129, Sub103, Sub149, Sub25
	common /varXs/ Sub141, Sub21, Sub151, Sub26, Sub142, Sub22
	common /varXs/ Sub17, Sub32, Sub136, Sub144, Sub150, Sub145
	common /varXs/ Sub152, Sub33, Sub34, Sub40, Sub44, Sub273
	common /varXs/ Sub45, Sub16, Sub89, Sub130, Sub41, Sub114
	common /varXs/ Sub61, Sub48, Sub107, Sub54, Sub67, Sub125
	common /varXs/ Sub100, Sub90, Sub101, pave1, pave2, pave3
	common /varXs/ pave12, pave19, pave22, pave23

	ComplexType Sub279(2), Sub275(2), Sub291(2), Sub287(2)
	ComplexType Sub288(2), Sub278(2), Sub274(2), Sub254(2)
	ComplexType Sub253(2), Sub292(2), Sub268(2), Sub266(2)
	ComplexType Sub262(2), Sub260(2), Sub255(2,2), Sub256(2,2)
	ComplexType Sub209, Sub189, Sub276(2), Sub280(2)
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave7(Ndd,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ncc,2), pave11(Ncc,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave18(Ncc,2), pave20(Nbb)
	ComplexType pave21(Nbb)
	RealType S, T, U
	common /varXa/ Sub279, Sub275, Sub291, Sub287, Sub288, Sub278
	common /varXa/ Sub274, Sub254, Sub253, Sub292, Sub268
	common /varXa/ Sub266, Sub262, Sub260, Sub255, Sub256
	common /varXa/ Sub209, Sub189, Sub276, Sub280, pave4, pave5
	common /varXa/ pave6, pave7, pave8, pave9, pave10, pave11
	common /varXa/ pave13, pave14, pave15, pave16, pave17
	common /varXa/ pave18, pave20, pave21, S, T, U

	HelType F1, F7, F5, F9, F8, F2, F11, F4, F10, F12, F3, F6
	HelType Sub9
	HelType F16, F20, F13, F23, F27, F22, F25, F19, F24, F21, F14
	HelType F15, F33, F31, F37, F40, F26, F34, F32, F36, F41
	HelType F28, F42, F29, F38, F30, F17, F39, F18, F35, Sub166
	HelType Sub220, Sub216, Sub229, Sub231, Sub232, Sub233
	HelType Sub218, Sub219, Sub206, Sub207, Sub204, Sub205
	HelType Sub199, Sub198, Sub201, Sub190, Sub192, Sub181
	HelType Sub183, Sub224, Sub222, Sub228, Sub230, Sub194
	HelType Sub191, Sub210, Sub212, Sub217, Sub215
	HelType Sub177(HelDim(2)), Sub178(HelDim(2))
	HelType Sub182(HelDim(2)), Sub185(HelDim(2))
	HelType Sub200(HelDim(2)), Sub202(HelDim(2))
	HelType Sub211(HelDim(2)), Sub213(HelDim(2))
	HelType Sub124(HelDim(2)), Sub188(HelDim(2))
	HelType Sub221(HelDim(2)), Sub134(HelDim(2))
	HelType Sub179(HelDim(2)), Sub186(HelDim(2))
	HelType Sub289(HelDim(2)), Sub203(HelDim(2))
	HelType Sub214(HelDim(2)), Sub277(HelDim(2))
	HelType Sub175(HelDim(2)), Sub174(HelDim(2))
	HelType Sub193(HelDim(2)), Sub223(HelDim(2))
	HelType Sub195(HelDim(2)), Sub225(HelDim(2))
	HelType Sub196(HelDim(2)), Sub176(HelDim(2))
	HelType Sub197(HelDim(2)), Sub226(HelDim(2))
	HelType Sub187(HelDim(2)), Sub208(HelDim(2))
	HelType Sub234(HelDim(2)), Sub105(HelDim(2))
	HelType Sub281(HelDim(2)), Sub75(HelDim(2))
	HelType Sub257(HelDim(2),2), Sub139(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub244(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub146(HelDim(2),2)
	HelType Sub148(HelDim(2),2), Sub153(HelDim(2),2)
	HelType Sub156(HelDim(2),2), Sub159(HelDim(2),2)
	HelType Sub161(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub282(HelDim(2),2)
	HelType Sub283(HelDim(2),2), Sub286(HelDim(2),2)
	HelType Sub258(HelDim(2),2), Sub259(HelDim(2),2)
	HelType Sub261(HelDim(2),2), Sub263(HelDim(2),2)
	HelType Sub264(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub272(HelDim(2),2)
	HelType Sub240(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub243(HelDim(2),2), Sub239(HelDim(2),2)
	HelType Sub238(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub235(HelDim(2),2), Sub270(HelDim(2),2)
	HelType Sub155(HelDim(2),2), Sub157(HelDim(2),2)
	HelType Sub140(HelDim(2),2), Sub162(HelDim(2),2)
	HelType Sub158(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub137(HelDim(2),2)
	HelType Sub138(HelDim(2),2), Sub143(HelDim(2),2)
	HelType Sub154(HelDim(2),2), Sub147(HelDim(2),2)
	HelType Sub160(HelDim(2),2), Sub167(HelDim(2),2), Sub242
	HelType Sub173, Sub171, Sub241, Sub172, Sub170
	HelType Sub135(HelDim(2)), Sub106(HelDim(2))
	HelType Sub284(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub180, Sub184
	HelType Sub290(HelDim(2)), Sub293(HelDim(2))
	HelType Sub285(HelDim(2),2)
	common /varXh/ F1, F7, F5, F9, F8, F2, F11, F4, F10, F12, F3
	common /varXh/ F6, Sub9, F16, F20, F13, F23, F27, F22, F25
	common /varXh/ F19, F24, F21, F14, F15, F33, F31, F37, F40
	common /varXh/ F26, F34, F32, F36, F41, F28, F42, F29, F38
	common /varXh/ F30, F17, F39, F18, F35, Sub166, Sub220
	common /varXh/ Sub216, Sub229, Sub231, Sub232, Sub233
	common /varXh/ Sub218, Sub219, Sub206, Sub207, Sub204
	common /varXh/ Sub205, Sub199, Sub198, Sub201, Sub190
	common /varXh/ Sub192, Sub181, Sub183, Sub224, Sub222
	common /varXh/ Sub228, Sub230, Sub194, Sub191, Sub210
	common /varXh/ Sub212, Sub217, Sub215, Sub177, Sub178
	common /varXh/ Sub182, Sub185, Sub200, Sub202, Sub211
	common /varXh/ Sub213, Sub124, Sub188, Sub221, Sub134
	common /varXh/ Sub179, Sub186, Sub289, Sub203, Sub214
	common /varXh/ Sub277, Sub175, Sub174, Sub193, Sub223
	common /varXh/ Sub195, Sub225, Sub196, Sub176, Sub197
	common /varXh/ Sub226, Sub187, Sub208, Sub234, Sub105
	common /varXh/ Sub281, Sub75, Sub257, Sub139, Sub248, Sub247
	common /varXh/ Sub237, Sub244, Sub245, Sub246, Sub227
	common /varXh/ Sub146, Sub148, Sub153, Sub156, Sub159
	common /varXh/ Sub161, Sub163, Sub168, Sub282, Sub283
	common /varXh/ Sub286, Sub258, Sub259, Sub261, Sub263
	common /varXh/ Sub264, Sub265, Sub267, Sub269, Sub271
	common /varXh/ Sub272, Sub240, Sub250, Sub243, Sub239
	common /varXh/ Sub238, Sub252, Sub235, Sub270, Sub155
	common /varXh/ Sub157, Sub140, Sub162, Sub158, Sub169
	common /varXh/ Sub236, Sub137, Sub138, Sub143, Sub154
	common /varXh/ Sub147, Sub160, Sub167, Sub242, Sub173
	common /varXh/ Sub171, Sub241, Sub172, Sub170, Sub135
	common /varXh/ Sub106, Sub284, Sub249, Sub251, Sub180
	common /varXh/ Sub184, Sub290, Sub293, Sub285

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n1n2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
