#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:40
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub7, Sub4, Sub2, Sub13, Sub11, Sub14, Sub1(2)
	ComplexType Sub8(2), Sub10(2), Sub5(2), Sub3(2), Sub9(2)
	ComplexType Sub12(2), Sub6(2)
	ComplexType Sub45, Sub168, Sub169, Sub85, Sub99, Sub44, Sub55
	ComplexType Sub86, Sub100, Sub68, Sub59, Sub60, Sub98, Sub96
	ComplexType Sub84, Sub79, Sub81, Sub48, Sub49, Sub61, Sub117
	ComplexType Sub120, Sub57, Sub121, Sub122, Sub119, Sub52
	ComplexType Sub53, Sub64, Sub71, Sub114, Sub72, Sub73, Sub70
	ComplexType Sub111, Sub112, Sub62, Sub89, Sub90, Sub113(2)
	ComplexType Sub54(2), Sub134(2), Sub76(2), Sub125(2)
	ComplexType Sub94(2), Sub78(2), Sub83(2), Sub115(2)
	ComplexType Sub58(2), Sub80(2), Sub82(2), Sub133(2)
	ComplexType Sub87(2), Sub93(2), Sub65(2), Sub66(2)
	ComplexType Sub101(2), Sub123(2), Sub74(2), Sub97(2)
	ComplexType Sub104(2), Sub128(2), Sub124(2), Sub118(2)
	ComplexType Sub51(2), Sub75(2), Sub67(2), Sub110(2)
	ComplexType Sub95(2), Sub130(2), Sub129(2), Sub88(2)
	ComplexType Sub135(2), Sub106(2), Sub105(2), Sub131(2)
	ComplexType Sub152(2), Sub28(2), Sub142(2), Sub21(2)
	ComplexType Sub154(2), Sub29(2), Sub146(2), Sub22(2)
	ComplexType Sub16(2,2), Sub32(2,2), Sub138(2,2), Sub143(2,2)
	ComplexType Sub153(2,2), Sub144(2,2), Sub155(2,2)
	ComplexType Sub35(2,2), Sub36(2,2), Sub42(2,2,2), Sub46
	ComplexType Sub275, Sub47, Sub17(2,2), Sub91, Sub132, Sub43
	ComplexType Sub116, Sub63, Sub50, Sub109, Sub56, Sub69
	ComplexType Sub127, Sub102, Sub92, Sub103, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave12(Ncc,2)
	ComplexType pave19(Ncc,2,2), pave22, pave23(Ncc,2)
	common /varXs/ Sub7, Sub4, Sub2, Sub13, Sub11, Sub14, Sub1
	common /varXs/ Sub8, Sub10, Sub5, Sub3, Sub9, Sub12, Sub6
	common /varXs/ Sub45, Sub168, Sub169, Sub85, Sub99, Sub44
	common /varXs/ Sub55, Sub86, Sub100, Sub68, Sub59, Sub60
	common /varXs/ Sub98, Sub96, Sub84, Sub79, Sub81, Sub48
	common /varXs/ Sub49, Sub61, Sub117, Sub120, Sub57, Sub121
	common /varXs/ Sub122, Sub119, Sub52, Sub53, Sub64, Sub71
	common /varXs/ Sub114, Sub72, Sub73, Sub70, Sub111, Sub112
	common /varXs/ Sub62, Sub89, Sub90, Sub113, Sub54, Sub134
	common /varXs/ Sub76, Sub125, Sub94, Sub78, Sub83, Sub115
	common /varXs/ Sub58, Sub80, Sub82, Sub133, Sub87, Sub93
	common /varXs/ Sub65, Sub66, Sub101, Sub123, Sub74, Sub97
	common /varXs/ Sub104, Sub128, Sub124, Sub118, Sub51, Sub75
	common /varXs/ Sub67, Sub110, Sub95, Sub130, Sub129, Sub88
	common /varXs/ Sub135, Sub106, Sub105, Sub131, Sub152, Sub28
	common /varXs/ Sub142, Sub21, Sub154, Sub29, Sub146, Sub22
	common /varXs/ Sub16, Sub32, Sub138, Sub143, Sub153, Sub144
	common /varXs/ Sub155, Sub35, Sub36, Sub42, Sub46, Sub275
	common /varXs/ Sub47, Sub17, Sub91, Sub132, Sub43, Sub116
	common /varXs/ Sub63, Sub50, Sub109, Sub56, Sub69, Sub127
	common /varXs/ Sub102, Sub92, Sub103, pave1, pave2, pave3
	common /varXs/ pave12, pave19, pave22, pave23

	ComplexType Sub277(2), Sub281(2), Sub291(2), Sub294(2)
	ComplexType Sub295(2), Sub276(2), Sub280(2), Sub255(2)
	ComplexType Sub256(2), Sub292(2), Sub264(2), Sub262(2)
	ComplexType Sub268(2), Sub270(2), Sub33(2,2), Sub34(2,2)
	ComplexType Sub257(2,2), Sub258(2,2), Sub211, Sub199
	ComplexType Sub278(2), Sub282(2), pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Ndd,2), pave7(Ndd,2)
	ComplexType pave8(Ncc,2), pave9(Ncc,2), pave10(Ncc,2)
	ComplexType pave11(Ncc,2), pave13(Nbb,2), pave14(Nbb,2)
	ComplexType pave15(Ncc,2), pave16(Ncc,2), pave17(Ncc,2)
	ComplexType pave18(Ncc,2), pave20(Nbb), pave21(Nbb)
	RealType S, T, U
	common /varXa/ Sub277, Sub281, Sub291, Sub294, Sub295, Sub276
	common /varXa/ Sub280, Sub255, Sub256, Sub292, Sub264
	common /varXa/ Sub262, Sub268, Sub270, Sub33, Sub34, Sub257
	common /varXa/ Sub258, Sub211, Sub199, Sub278, Sub282, pave4
	common /varXa/ pave5, pave6, pave7, pave8, pave9, pave10
	common /varXa/ pave11, pave13, pave14, pave15, pave16
	common /varXa/ pave17, pave18, pave20, pave21, S, T, U

	HelType F1, F7, F3, F9, F8, F5, F11, F2, F10, F12, F6, F4
	HelType Sub15
	HelType F16, F22, F13, F24, F26, F20, F21, F19, F25, F23, F14
	HelType F15, F34, F32, F39, F40, F27, F29, F33, F38, F41
	HelType F28, F42, F30, F36, F31, F17, F37, F18, F35, Sub170
	HelType Sub222, Sub218, Sub233, Sub237, Sub235, Sub236
	HelType Sub220, Sub221, Sub227, Sub228, Sub225, Sub226
	HelType Sub200, Sub201, Sub203, Sub183, Sub185, Sub195
	HelType Sub193, Sub208, Sub206, Sub232, Sub234, Sub187
	HelType Sub184, Sub214, Sub212, Sub217, Sub219
	HelType Sub178(HelDim(2)), Sub198(HelDim(2))
	HelType Sub216(HelDim(2)), Sub180(HelDim(2))
	HelType Sub179(HelDim(2)), Sub186(HelDim(2))
	HelType Sub207(HelDim(2)), Sub188(HelDim(2))
	HelType Sub209(HelDim(2)), Sub189(HelDim(2))
	HelType Sub181(HelDim(2)), Sub190(HelDim(2))
	HelType Sub210(HelDim(2)), Sub191(HelDim(2))
	HelType Sub229(HelDim(2)), Sub238(HelDim(2))
	HelType Sub107(HelDim(2)), Sub279(HelDim(2))
	HelType Sub77(HelDim(2)), Sub177(HelDim(2))
	HelType Sub176(HelDim(2)), Sub194(HelDim(2))
	HelType Sub197(HelDim(2)), Sub202(HelDim(2))
	HelType Sub204(HelDim(2)), Sub215(HelDim(2))
	HelType Sub213(HelDim(2)), Sub126(HelDim(2))
	HelType Sub182(HelDim(2)), Sub136(HelDim(2))
	HelType Sub283(HelDim(2)), Sub205(HelDim(2))
	HelType Sub223(HelDim(2)), Sub259(HelDim(2),2)
	HelType Sub141(HelDim(2),2), Sub145(HelDim(2),2)
	HelType Sub149(HelDim(2),2), Sub156(HelDim(2),2)
	HelType Sub159(HelDim(2),2), Sub161(HelDim(2),2)
	HelType Sub163(HelDim(2),2), Sub165(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub287(HelDim(2),2)
	HelType Sub286(HelDim(2),2), Sub288(HelDim(2),2)
	HelType Sub260(HelDim(2),2), Sub261(HelDim(2),2)
	HelType Sub263(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub273(HelDim(2),2)
	HelType Sub274(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub243(HelDim(2),2)
	HelType Sub239(HelDim(2),2), Sub240(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub266(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub231(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub253(HelDim(2),2)
	HelType Sub244(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub272(HelDim(2),2), Sub158(HelDim(2),2)
	HelType Sub151(HelDim(2),2), Sub147(HelDim(2),2)
	HelType Sub162(HelDim(2),2), Sub164(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub140(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub139(HelDim(2),2)
	HelType Sub150(HelDim(2),2), Sub157(HelDim(2),2)
	HelType Sub148(HelDim(2),2), Sub160(HelDim(2),2)
	HelType Sub166(HelDim(2),2), Sub242, Sub175, Sub172, Sub241
	HelType Sub174, Sub171, Sub137(HelDim(2)), Sub108(HelDim(2))
	HelType Sub284(HelDim(2),2), Sub254(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub196, Sub192
	HelType Sub290(HelDim(2)), Sub289(HelDim(2),2)
	HelType Sub293(HelDim(2)), Sub285(HelDim(2),2)
	common /varXh/ F1, F7, F3, F9, F8, F5, F11, F2, F10, F12, F6
	common /varXh/ F4, Sub15, F16, F22, F13, F24, F26, F20, F21
	common /varXh/ F19, F25, F23, F14, F15, F34, F32, F39, F40
	common /varXh/ F27, F29, F33, F38, F41, F28, F42, F30, F36
	common /varXh/ F31, F17, F37, F18, F35, Sub170, Sub222
	common /varXh/ Sub218, Sub233, Sub237, Sub235, Sub236
	common /varXh/ Sub220, Sub221, Sub227, Sub228, Sub225
	common /varXh/ Sub226, Sub200, Sub201, Sub203, Sub183
	common /varXh/ Sub185, Sub195, Sub193, Sub208, Sub206
	common /varXh/ Sub232, Sub234, Sub187, Sub184, Sub214
	common /varXh/ Sub212, Sub217, Sub219, Sub178, Sub198
	common /varXh/ Sub216, Sub180, Sub179, Sub186, Sub207
	common /varXh/ Sub188, Sub209, Sub189, Sub181, Sub190
	common /varXh/ Sub210, Sub191, Sub229, Sub238, Sub107
	common /varXh/ Sub279, Sub77, Sub177, Sub176, Sub194, Sub197
	common /varXh/ Sub202, Sub204, Sub215, Sub213, Sub126
	common /varXh/ Sub182, Sub136, Sub283, Sub205, Sub223
	common /varXh/ Sub259, Sub141, Sub145, Sub149, Sub156
	common /varXh/ Sub159, Sub161, Sub163, Sub165, Sub167
	common /varXh/ Sub287, Sub286, Sub288, Sub260, Sub261
	common /varXh/ Sub263, Sub265, Sub267, Sub269, Sub271
	common /varXh/ Sub273, Sub274, Sub245, Sub249, Sub243
	common /varXh/ Sub239, Sub240, Sub248, Sub224, Sub266
	common /varXh/ Sub252, Sub247, Sub231, Sub250, Sub253
	common /varXh/ Sub244, Sub246, Sub272, Sub158, Sub151
	common /varXh/ Sub147, Sub162, Sub164, Sub173, Sub140
	common /varXh/ Sub230, Sub139, Sub150, Sub157, Sub148
	common /varXh/ Sub160, Sub166, Sub242, Sub175, Sub172
	common /varXh/ Sub241, Sub174, Sub171, Sub137, Sub108
	common /varXh/ Sub284, Sub254, Sub251, Sub196, Sub192
	common /varXh/ Sub290, Sub289, Sub293, Sub285

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n2n3_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
