#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:33
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7(2)
	ComplexType Sub2(2), Sub4(2), Sub11(2), Sub9(2), Sub3(2)
	ComplexType Sub6(2), Sub12(2)
	ComplexType Sub45, Sub168, Sub169, Sub85, Sub99, Sub44, Sub55
	ComplexType Sub86, Sub100, Sub68, Sub59, Sub60, Sub98, Sub96
	ComplexType Sub84, Sub79, Sub81, Sub48, Sub49, Sub117
	ComplexType Sub120, Sub57, Sub121, Sub122, Sub119, Sub52
	ComplexType Sub53, Sub61, Sub62, Sub64, Sub71, Sub111, Sub72
	ComplexType Sub73, Sub70, Sub112, Sub113, Sub89, Sub90
	ComplexType Sub114(2), Sub54(2), Sub134(2), Sub125(2)
	ComplexType Sub76(2), Sub94(2), Sub78(2), Sub83(2)
	ComplexType Sub115(2), Sub58(2), Sub80(2), Sub82(2)
	ComplexType Sub133(2), Sub87(2), Sub93(2), Sub65(2)
	ComplexType Sub66(2), Sub101(2), Sub123(2), Sub74(2)
	ComplexType Sub97(2), Sub104(2), Sub128(2), Sub124(2)
	ComplexType Sub118(2), Sub51(2), Sub75(2), Sub67(2)
	ComplexType Sub110(2), Sub95(2), Sub130(2), Sub129(2)
	ComplexType Sub88(2), Sub135(2), Sub106(2), Sub105(2)
	ComplexType Sub131(2), Sub151(2), Sub30(2), Sub143(2)
	ComplexType Sub21(2), Sub153(2), Sub31(2), Sub144(2)
	ComplexType Sub22(2), Sub16(2,2), Sub32(2,2), Sub138(2,2)
	ComplexType Sub152(2,2), Sub146(2,2), Sub147(2,2)
	ComplexType Sub154(2,2), Sub35(2,2), Sub36(2,2)
	ComplexType Sub42(2,2,2), Sub46, Sub275, Sub47, Sub17(2,2)
	ComplexType Sub91, Sub132, Sub43, Sub116, Sub63, Sub50
	ComplexType Sub109, Sub56, Sub69, Sub127, Sub102, Sub92
	ComplexType Sub103, pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave12(Ncc,2), pave13(Ncc,2), pave20(Ncc,2,2)
	ComplexType pave23
	common /varXs/ Sub1, Sub10, Sub8, Sub13, Sub5, Sub14, Sub7
	common /varXs/ Sub2, Sub4, Sub11, Sub9, Sub3, Sub6, Sub12
	common /varXs/ Sub45, Sub168, Sub169, Sub85, Sub99, Sub44
	common /varXs/ Sub55, Sub86, Sub100, Sub68, Sub59, Sub60
	common /varXs/ Sub98, Sub96, Sub84, Sub79, Sub81, Sub48
	common /varXs/ Sub49, Sub117, Sub120, Sub57, Sub121, Sub122
	common /varXs/ Sub119, Sub52, Sub53, Sub61, Sub62, Sub64
	common /varXs/ Sub71, Sub111, Sub72, Sub73, Sub70, Sub112
	common /varXs/ Sub113, Sub89, Sub90, Sub114, Sub54, Sub134
	common /varXs/ Sub125, Sub76, Sub94, Sub78, Sub83, Sub115
	common /varXs/ Sub58, Sub80, Sub82, Sub133, Sub87, Sub93
	common /varXs/ Sub65, Sub66, Sub101, Sub123, Sub74, Sub97
	common /varXs/ Sub104, Sub128, Sub124, Sub118, Sub51, Sub75
	common /varXs/ Sub67, Sub110, Sub95, Sub130, Sub129, Sub88
	common /varXs/ Sub135, Sub106, Sub105, Sub131, Sub151, Sub30
	common /varXs/ Sub143, Sub21, Sub153, Sub31, Sub144, Sub22
	common /varXs/ Sub16, Sub32, Sub138, Sub152, Sub146, Sub147
	common /varXs/ Sub154, Sub35, Sub36, Sub42, Sub46, Sub275
	common /varXs/ Sub47, Sub17, Sub91, Sub132, Sub43, Sub116
	common /varXs/ Sub63, Sub50, Sub109, Sub56, Sub69, Sub127
	common /varXs/ Sub102, Sub92, Sub103, pave1, pave2, pave3
	common /varXs/ pave12, pave13, pave20, pave23

	ComplexType Sub281(2), Sub277(2), Sub294(2), Sub292(2)
	ComplexType Sub295(2), Sub293(2), Sub280(2), Sub276(2)
	ComplexType Sub256(2), Sub255(2), Sub268(2), Sub270(2)
	ComplexType Sub264(2), Sub262(2), Sub33(2,2), Sub34(2,2)
	ComplexType Sub258(2,2), Sub257(2,2), Sub206, Sub199
	ComplexType Sub278(2), Sub282(2), pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Ndd,2), pave7(Ndd,2)
	ComplexType pave8(Ncc,2), pave9(Ncc,2), pave10(Ncc,2)
	ComplexType pave11(Ncc,2), pave14(Nbb,2), pave15(Nbb,2)
	ComplexType pave16(Ncc,2), pave17(Ncc,2), pave18(Ncc,2)
	ComplexType pave19(Ncc,2), pave21(Nbb), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub281, Sub277, Sub294, Sub292, Sub295, Sub293
	common /varXa/ Sub280, Sub276, Sub256, Sub255, Sub268
	common /varXa/ Sub270, Sub264, Sub262, Sub33, Sub34, Sub258
	common /varXa/ Sub257, Sub206, Sub199, Sub278, Sub282, pave4
	common /varXa/ pave5, pave6, pave7, pave8, pave9, pave10
	common /varXa/ pave11, pave14, pave15, pave16, pave17
	common /varXa/ pave18, pave19, pave21, pave22, S, T, U

	HelType F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4, F8
	HelType Sub15
	HelType F16, F21, F13, F24, F27, F20, F23, F19, F25, F22, F14
	HelType F15, F34, F32, F41, F38, F26, F31, F33, F42, F39
	HelType F28, F40, F29, F36, F30, F17, F37, F18, F35, Sub170
	HelType Sub222, Sub218, Sub233, Sub235, Sub237, Sub236
	HelType Sub220, Sub221, Sub225, Sub224, Sub227, Sub226
	HelType Sub201, Sub200, Sub203, Sub193, Sub191, Sub185
	HelType Sub187, Sub214, Sub212, Sub234, Sub232, Sub195
	HelType Sub192, Sub207, Sub209, Sub219, Sub217
	HelType Sub181(HelDim(2)), Sub289(HelDim(2))
	HelType Sub198(HelDim(2)), Sub216(HelDim(2))
	HelType Sub177(HelDim(2)), Sub176(HelDim(2))
	HelType Sub186(HelDim(2)), Sub189(HelDim(2))
	HelType Sub202(HelDim(2)), Sub204(HelDim(2))
	HelType Sub208(HelDim(2)), Sub210(HelDim(2))
	HelType Sub126(HelDim(2)), Sub136(HelDim(2))
	HelType Sub178(HelDim(2)), Sub190(HelDim(2))
	HelType Sub211(HelDim(2)), Sub183(HelDim(2))
	HelType Sub205(HelDim(2)), Sub223(HelDim(2))
	HelType Sub279(HelDim(2)), Sub180(HelDim(2))
	HelType Sub179(HelDim(2)), Sub194(HelDim(2))
	HelType Sub213(HelDim(2)), Sub196(HelDim(2))
	HelType Sub215(HelDim(2)), Sub197(HelDim(2))
	HelType Sub182(HelDim(2)), Sub77(HelDim(2))
	HelType Sub107(HelDim(2)), Sub283(HelDim(2))
	HelType Sub228(HelDim(2)), Sub238(HelDim(2))
	HelType Sub259(HelDim(2),2), Sub141(HelDim(2),2)
	HelType Sub148(HelDim(2),2), Sub150(HelDim(2),2)
	HelType Sub253(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub243(HelDim(2),2), Sub240(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub155(HelDim(2),2)
	HelType Sub158(HelDim(2),2), Sub161(HelDim(2),2)
	HelType Sub163(HelDim(2),2), Sub165(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub286(HelDim(2),2)
	HelType Sub285(HelDim(2),2), Sub287(HelDim(2),2)
	HelType Sub260(HelDim(2),2), Sub261(HelDim(2),2)
	HelType Sub263(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub273(HelDim(2),2)
	HelType Sub274(HelDim(2),2), Sub244(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub239(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub229(HelDim(2),2)
	HelType Sub266(HelDim(2),2), Sub272(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub159(HelDim(2),2)
	HelType Sub142(HelDim(2),2), Sub166(HelDim(2),2)
	HelType Sub162(HelDim(2),2), Sub173(HelDim(2),2)
	HelType Sub140(HelDim(2),2), Sub230(HelDim(2),2)
	HelType Sub139(HelDim(2),2), Sub145(HelDim(2),2)
	HelType Sub156(HelDim(2),2), Sub149(HelDim(2),2)
	HelType Sub160(HelDim(2),2), Sub164(HelDim(2),2), Sub242
	HelType Sub175, Sub172, Sub241, Sub174, Sub171
	HelType Sub290(HelDim(2)), Sub137(HelDim(2))
	HelType Sub108(HelDim(2)), Sub288(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub254(HelDim(2),2), Sub184
	HelType Sub188, Sub291(HelDim(2)), Sub284(HelDim(2),2)
	common /varXh/ F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4
	common /varXh/ F8, Sub15, F16, F21, F13, F24, F27, F20, F23
	common /varXh/ F19, F25, F22, F14, F15, F34, F32, F41, F38
	common /varXh/ F26, F31, F33, F42, F39, F28, F40, F29, F36
	common /varXh/ F30, F17, F37, F18, F35, Sub170, Sub222
	common /varXh/ Sub218, Sub233, Sub235, Sub237, Sub236
	common /varXh/ Sub220, Sub221, Sub225, Sub224, Sub227
	common /varXh/ Sub226, Sub201, Sub200, Sub203, Sub193
	common /varXh/ Sub191, Sub185, Sub187, Sub214, Sub212
	common /varXh/ Sub234, Sub232, Sub195, Sub192, Sub207
	common /varXh/ Sub209, Sub219, Sub217, Sub181, Sub289
	common /varXh/ Sub198, Sub216, Sub177, Sub176, Sub186
	common /varXh/ Sub189, Sub202, Sub204, Sub208, Sub210
	common /varXh/ Sub126, Sub136, Sub178, Sub190, Sub211
	common /varXh/ Sub183, Sub205, Sub223, Sub279, Sub180
	common /varXh/ Sub179, Sub194, Sub213, Sub196, Sub215
	common /varXh/ Sub197, Sub182, Sub77, Sub107, Sub283, Sub228
	common /varXh/ Sub238, Sub259, Sub141, Sub148, Sub150
	common /varXh/ Sub253, Sub246, Sub243, Sub240, Sub231
	common /varXh/ Sub251, Sub245, Sub155, Sub158, Sub161
	common /varXh/ Sub163, Sub165, Sub167, Sub286, Sub285
	common /varXh/ Sub287, Sub260, Sub261, Sub263, Sub265
	common /varXh/ Sub267, Sub269, Sub271, Sub273, Sub274
	common /varXh/ Sub244, Sub250, Sub248, Sub239, Sub247
	common /varXh/ Sub249, Sub229, Sub266, Sub272, Sub157
	common /varXh/ Sub159, Sub142, Sub166, Sub162, Sub173
	common /varXh/ Sub140, Sub230, Sub139, Sub145, Sub156
	common /varXh/ Sub149, Sub160, Sub164, Sub242, Sub175
	common /varXh/ Sub172, Sub241, Sub174, Sub171, Sub290
	common /varXh/ Sub137, Sub108, Sub288, Sub252, Sub254
	common /varXh/ Sub184, Sub188, Sub291, Sub284

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n1n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
