#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:42
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub7, Sub4, Sub2, Sub13, Sub11, Sub14, Sub1(2)
	ComplexType Sub8(2), Sub10(2), Sub5(2), Sub3(2), Sub9(2)
	ComplexType Sub12(2), Sub6(2)
	ComplexType Sub43, Sub167, Sub168, Sub83, Sub97, Sub42, Sub53
	ComplexType Sub84, Sub98, Sub66, Sub57, Sub58, Sub96, Sub94
	ComplexType Sub82, Sub77, Sub79, Sub46, Sub47, Sub59, Sub115
	ComplexType Sub118, Sub55, Sub119, Sub120, Sub117, Sub50
	ComplexType Sub51, Sub60, Sub62, Sub69, Sub109, Sub70, Sub71
	ComplexType Sub68, Sub110, Sub111, Sub87, Sub88, Sub112(2)
	ComplexType Sub52(2), Sub132(2), Sub74(2), Sub123(2)
	ComplexType Sub92(2), Sub76(2), Sub81(2), Sub113(2)
	ComplexType Sub56(2), Sub78(2), Sub80(2), Sub131(2)
	ComplexType Sub85(2), Sub91(2), Sub63(2), Sub64(2), Sub99(2)
	ComplexType Sub121(2), Sub72(2), Sub95(2), Sub102(2)
	ComplexType Sub126(2), Sub122(2), Sub116(2), Sub49(2)
	ComplexType Sub73(2), Sub65(2), Sub108(2), Sub93(2)
	ComplexType Sub128(2), Sub86(2), Sub127(2), Sub133(2)
	ComplexType Sub104(2), Sub129(2), Sub103(2), Sub149(2)
	ComplexType Sub30(2), Sub140(2), Sub21(2), Sub151(2)
	ComplexType Sub31(2), Sub141(2), Sub22(2), Sub17(2,2)
	ComplexType Sub32(2,2), Sub136(2,2), Sub143(2,2)
	ComplexType Sub150(2,2), Sub144(2,2), Sub152(2,2)
	ComplexType Sub33(2,2), Sub34(2,2), Sub40(2,2,2), Sub44
	ComplexType Sub273, Sub45, Sub16(2,2), Sub89, Sub130, Sub41
	ComplexType Sub114, Sub61, Sub48, Sub107, Sub54, Sub67
	ComplexType Sub125, Sub100, Sub90, Sub101, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave12(Ncc,2)
	ComplexType pave19(Ncc,2,2), pave22, pave23(Ncc,2)
	common /varXs/ Sub7, Sub4, Sub2, Sub13, Sub11, Sub14, Sub1
	common /varXs/ Sub8, Sub10, Sub5, Sub3, Sub9, Sub12, Sub6
	common /varXs/ Sub43, Sub167, Sub168, Sub83, Sub97, Sub42
	common /varXs/ Sub53, Sub84, Sub98, Sub66, Sub57, Sub58
	common /varXs/ Sub96, Sub94, Sub82, Sub77, Sub79, Sub46
	common /varXs/ Sub47, Sub59, Sub115, Sub118, Sub55, Sub119
	common /varXs/ Sub120, Sub117, Sub50, Sub51, Sub60, Sub62
	common /varXs/ Sub69, Sub109, Sub70, Sub71, Sub68, Sub110
	common /varXs/ Sub111, Sub87, Sub88, Sub112, Sub52, Sub132
	common /varXs/ Sub74, Sub123, Sub92, Sub76, Sub81, Sub113
	common /varXs/ Sub56, Sub78, Sub80, Sub131, Sub85, Sub91
	common /varXs/ Sub63, Sub64, Sub99, Sub121, Sub72, Sub95
	common /varXs/ Sub102, Sub126, Sub122, Sub116, Sub49, Sub73
	common /varXs/ Sub65, Sub108, Sub93, Sub128, Sub86, Sub127
	common /varXs/ Sub133, Sub104, Sub129, Sub103, Sub149, Sub30
	common /varXs/ Sub140, Sub21, Sub151, Sub31, Sub141, Sub22
	common /varXs/ Sub17, Sub32, Sub136, Sub143, Sub150, Sub144
	common /varXs/ Sub152, Sub33, Sub34, Sub40, Sub44, Sub273
	common /varXs/ Sub45, Sub16, Sub89, Sub130, Sub41, Sub114
	common /varXs/ Sub61, Sub48, Sub107, Sub54, Sub67, Sub125
	common /varXs/ Sub100, Sub90, Sub101, pave1, pave2, pave3
	common /varXs/ pave12, pave19, pave22, pave23

	ComplexType Sub275(2), Sub279(2), Sub289(2), Sub292(2)
	ComplexType Sub293(2), Sub274(2), Sub278(2), Sub253(2)
	ComplexType Sub254(2), Sub290(2), Sub262(2), Sub260(2)
	ComplexType Sub266(2), Sub268(2), Sub255(2,2), Sub256(2,2)
	ComplexType Sub214, Sub203, Sub276(2), Sub280(2)
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Ndd,2)
	ComplexType pave7(Ndd,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ncc,2), pave11(Ncc,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave18(Ncc,2), pave20(Nbb)
	ComplexType pave21(Nbb)
	RealType S, T, U
	common /varXa/ Sub275, Sub279, Sub289, Sub292, Sub293, Sub274
	common /varXa/ Sub278, Sub253, Sub254, Sub290, Sub262
	common /varXa/ Sub260, Sub266, Sub268, Sub255, Sub256
	common /varXa/ Sub214, Sub203, Sub276, Sub280, pave4, pave5
	common /varXa/ pave6, pave7, pave8, pave9, pave10, pave11
	common /varXa/ pave13, pave14, pave15, pave16, pave17
	common /varXa/ pave18, pave20, pave21, S, T, U

	HelType F1, F3, F11, F7, F4, F5, F10, F2, F8, F9, F6, F12
	HelType Sub15
	HelType F16, F20, F13, F24, F26, F23, F27, F19, F25, F21, F14
	HelType F15, F33, F31, F40, F41, F22, F34, F32, F39, F42
	HelType F28, F36, F29, F38, F30, F17, F37, F18, F35, Sub169
	HelType Sub232, Sub228, Sub221, Sub223, Sub224, Sub230
	HelType Sub225, Sub231, Sub206, Sub207, Sub204, Sub205
	HelType Sub182, Sub183, Sub185, Sub188, Sub190, Sub199
	HelType Sub197, Sub211, Sub209, Sub220, Sub222, Sub192
	HelType Sub189, Sub217, Sub215, Sub227, Sub229
	HelType Sub179(HelDim(2)), Sub287(HelDim(2))
	HelType Sub202(HelDim(2)), Sub219(HelDim(2))
	HelType Sub175(HelDim(2)), Sub174(HelDim(2))
	HelType Sub191(HelDim(2)), Sub210(HelDim(2))
	HelType Sub193(HelDim(2)), Sub212(HelDim(2))
	HelType Sub194(HelDim(2)), Sub176(HelDim(2))
	HelType Sub195(HelDim(2)), Sub213(HelDim(2))
	HelType Sub181(HelDim(2)), Sub208(HelDim(2))
	HelType Sub226(HelDim(2)), Sub105(HelDim(2))
	HelType Sub277(HelDim(2)), Sub75(HelDim(2))
	HelType Sub178(HelDim(2)), Sub177(HelDim(2))
	HelType Sub184(HelDim(2)), Sub198(HelDim(2))
	HelType Sub201(HelDim(2)), Sub186(HelDim(2))
	HelType Sub218(HelDim(2)), Sub216(HelDim(2))
	HelType Sub124(HelDim(2)), Sub180(HelDim(2))
	HelType Sub134(HelDim(2)), Sub281(HelDim(2))
	HelType Sub187(HelDim(2)), Sub233(HelDim(2))
	HelType Sub257(HelDim(2),2), Sub139(HelDim(2),2)
	HelType Sub145(HelDim(2),2), Sub148(HelDim(2),2)
	HelType Sub153(HelDim(2),2), Sub156(HelDim(2),2)
	HelType Sub159(HelDim(2),2), Sub161(HelDim(2),2)
	HelType Sub163(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub282(HelDim(2),2), Sub258(HelDim(2),2)
	HelType Sub259(HelDim(2),2), Sub261(HelDim(2),2)
	HelType Sub263(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub272(HelDim(2),2)
	HelType Sub283(HelDim(2),2), Sub239(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub242(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub238(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub264(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub237(HelDim(2),2)
	HelType Sub243(HelDim(2),2), Sub244(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub270(HelDim(2),2), Sub155(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub146(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub160(HelDim(2),2)
	HelType Sub166(HelDim(2),2), Sub138(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub137(HelDim(2),2)
	HelType Sub142(HelDim(2),2), Sub154(HelDim(2),2)
	HelType Sub147(HelDim(2),2), Sub158(HelDim(2),2)
	HelType Sub162(HelDim(2),2), Sub241, Sub173, Sub165, Sub240
	HelType Sub172, Sub164, Sub135(HelDim(2)), Sub288(HelDim(2))
	HelType Sub106(HelDim(2)), Sub284(HelDim(2),2)
	HelType Sub286(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub200, Sub196
	HelType Sub291(HelDim(2)), Sub285(HelDim(2),2)
	common /varXh/ F1, F3, F11, F7, F4, F5, F10, F2, F8, F9, F6
	common /varXh/ F12, Sub15, F16, F20, F13, F24, F26, F23, F27
	common /varXh/ F19, F25, F21, F14, F15, F33, F31, F40, F41
	common /varXh/ F22, F34, F32, F39, F42, F28, F36, F29, F38
	common /varXh/ F30, F17, F37, F18, F35, Sub169, Sub232
	common /varXh/ Sub228, Sub221, Sub223, Sub224, Sub230
	common /varXh/ Sub225, Sub231, Sub206, Sub207, Sub204
	common /varXh/ Sub205, Sub182, Sub183, Sub185, Sub188
	common /varXh/ Sub190, Sub199, Sub197, Sub211, Sub209
	common /varXh/ Sub220, Sub222, Sub192, Sub189, Sub217
	common /varXh/ Sub215, Sub227, Sub229, Sub179, Sub287
	common /varXh/ Sub202, Sub219, Sub175, Sub174, Sub191
	common /varXh/ Sub210, Sub193, Sub212, Sub194, Sub176
	common /varXh/ Sub195, Sub213, Sub181, Sub208, Sub226
	common /varXh/ Sub105, Sub277, Sub75, Sub178, Sub177, Sub184
	common /varXh/ Sub198, Sub201, Sub186, Sub218, Sub216
	common /varXh/ Sub124, Sub180, Sub134, Sub281, Sub187
	common /varXh/ Sub233, Sub257, Sub139, Sub145, Sub148
	common /varXh/ Sub153, Sub156, Sub159, Sub161, Sub163
	common /varXh/ Sub171, Sub282, Sub258, Sub259, Sub261
	common /varXh/ Sub263, Sub265, Sub267, Sub269, Sub271
	common /varXh/ Sub272, Sub283, Sub239, Sub248, Sub242
	common /varXh/ Sub246, Sub238, Sub250, Sub235, Sub264
	common /varXh/ Sub245, Sub251, Sub237, Sub243, Sub244
	common /varXh/ Sub247, Sub234, Sub270, Sub155, Sub157
	common /varXh/ Sub146, Sub170, Sub160, Sub166, Sub138
	common /varXh/ Sub236, Sub137, Sub142, Sub154, Sub147
	common /varXh/ Sub158, Sub162, Sub241, Sub173, Sub165
	common /varXh/ Sub240, Sub172, Sub164, Sub135, Sub288
	common /varXh/ Sub106, Sub284, Sub286, Sub249, Sub252
	common /varXh/ Sub200, Sub196, Sub291, Sub285

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n2n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
