#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 11-Jun-2015 10:57
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub11, Sub1, Sub7, Sub8, Sub3(2), Sub12(2)
	ComplexType Sub10(2), Sub2(2), Sub5(2), Sub4(2), Sub13(2)
	ComplexType Sub15(2), Sub14(2), Sub6(2)
	ComplexType Sub45, Sub180, Sub181, Sub102, Sub85, Sub44
	ComplexType Sub55, Sub103, Sub86, Sub60, Sub69, Sub61, Sub99
	ComplexType Sub101, Sub79, Sub84, Sub81, Sub51, Sub54
	ComplexType Sub120, Sub123, Sub57, Sub124, Sub58, Sub125
	ComplexType Sub122, Sub48, Sub49, Sub65, Sub72, Sub116
	ComplexType Sub73, Sub117, Sub74, Sub71, Sub111, Sub112
	ComplexType Sub63, Sub62, Sub89, Sub90, Sub91, Sub92
	ComplexType Sub113(2), Sub50(2), Sub128(2), Sub133(2)
	ComplexType Sub137(2), Sub77(2), Sub96(2), Sub78(2)
	ComplexType Sub83(2), Sub118(2), Sub59(2), Sub80(2)
	ComplexType Sub82(2), Sub136(2), Sub87(2), Sub95(2)
	ComplexType Sub66(2), Sub67(2), Sub104(2), Sub126(2)
	ComplexType Sub75(2), Sub100(2), Sub107(2), Sub130(2)
	ComplexType Sub53(2), Sub127(2), Sub121(2), Sub115(2)
	ComplexType Sub76(2), Sub68(2), Sub132(2), Sub97(2)
	ComplexType Sub131(2), Sub88(2), Sub109(2), Sub138(2)
	ComplexType Sub108(2), Sub134(2), Sub145(2), Sub28(2)
	ComplexType Sub154(2), Sub23(2), Sub148(2), Sub147(2)
	ComplexType Sub29(2), Sub160(2), Sub159(2), Sub24(2)
	ComplexType Sub16(2,2), Sub32(2,2), Sub141(2,2), Sub146(2,2)
	ComplexType Sub155(2,2), Sub156(2,2), Sub149(2,2)
	ComplexType Sub35(2,2), Sub36(2,2), Sub42(2,2,2), Sub46
	ComplexType Sub275, Sub47, Sub17(2,2), Sub93, Sub135, Sub43
	ComplexType Sub119, Sub64, Sub52, Sub114, Sub56, Sub70
	ComplexType Sub129, Sub105, Sub94, Sub106, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave14(Ncc,2)
	ComplexType pave17(Ncc,2,2), pave22, pave23(Ncc,2)
	common /varXs/ Sub11, Sub1, Sub7, Sub8, Sub3, Sub12, Sub10
	common /varXs/ Sub2, Sub5, Sub4, Sub13, Sub15, Sub14, Sub6
	common /varXs/ Sub45, Sub180, Sub181, Sub102, Sub85, Sub44
	common /varXs/ Sub55, Sub103, Sub86, Sub60, Sub69, Sub61
	common /varXs/ Sub99, Sub101, Sub79, Sub84, Sub81, Sub51
	common /varXs/ Sub54, Sub120, Sub123, Sub57, Sub124, Sub58
	common /varXs/ Sub125, Sub122, Sub48, Sub49, Sub65, Sub72
	common /varXs/ Sub116, Sub73, Sub117, Sub74, Sub71, Sub111
	common /varXs/ Sub112, Sub63, Sub62, Sub89, Sub90, Sub91
	common /varXs/ Sub92, Sub113, Sub50, Sub128, Sub133, Sub137
	common /varXs/ Sub77, Sub96, Sub78, Sub83, Sub118, Sub59
	common /varXs/ Sub80, Sub82, Sub136, Sub87, Sub95, Sub66
	common /varXs/ Sub67, Sub104, Sub126, Sub75, Sub100, Sub107
	common /varXs/ Sub130, Sub53, Sub127, Sub121, Sub115, Sub76
	common /varXs/ Sub68, Sub132, Sub97, Sub131, Sub88, Sub109
	common /varXs/ Sub138, Sub108, Sub134, Sub145, Sub28, Sub154
	common /varXs/ Sub23, Sub148, Sub147, Sub29, Sub160, Sub159
	common /varXs/ Sub24, Sub16, Sub32, Sub141, Sub146, Sub155
	common /varXs/ Sub156, Sub149, Sub35, Sub36, Sub42, Sub46
	common /varXs/ Sub275, Sub47, Sub17, Sub93, Sub135, Sub43
	common /varXs/ Sub119, Sub64, Sub52, Sub114, Sub56, Sub70
	common /varXs/ Sub129, Sub105, Sub94, Sub106, pave1, pave2
	common /varXs/ pave3, pave14, pave17, pave22, pave23

	ComplexType Sub261, Sub259, Sub281(2), Sub277(2), Sub294(2)
	ComplexType Sub291(2), Sub292(2), Sub280(2), Sub276(2)
	ComplexType Sub258(2), Sub257(2), Sub295(2), Sub33(2,2)
	ComplexType Sub34(2,2), Sub262(2,2), Sub260(2,2), Sub208
	ComplexType Sub198, Sub278(2), Sub282(2), pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Ndd,2), pave7(Ndd,2)
	ComplexType pave8(Nbb), pave9(Nbb), pave10(Ncc,2)
	ComplexType pave11(Ncc,2), pave12(Ncc,2), pave13(Ncc,2)
	ComplexType pave15(Nbb,2), pave16(Nbb,2), pave18(Ncc,2)
	ComplexType pave19(Ncc,2), pave20(Ncc,2), pave21(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub261, Sub259, Sub281, Sub277, Sub294, Sub291
	common /varXa/ Sub292, Sub280, Sub276, Sub258, Sub257
	common /varXa/ Sub295, Sub33, Sub34, Sub262, Sub260, Sub208
	common /varXa/ Sub198, Sub278, Sub282, pave4, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave10, pave11, pave12
	common /varXa/ pave13, pave15, pave16, pave18, pave19
	common /varXa/ pave20, pave21, S, T, U

	HelType F1, F8, F11, F5, F9, F3, F10, F2, F6, F7, F4, F12
	HelType Sub9
	HelType F16, F23, F13, F20, F22, F26, F27, F19, F21, F24, F14
	HelType F15, F31, F33, F40, F42, F25, F32, F34, F41, F39
	HelType F29, F35, F28, F38, F30, F17, F36, F18, F37, Sub182
	HelType Sub221, Sub217, Sub200, Sub241, Sub219, Sub245
	HelType Sub220, Sub212, Sub210, Sub223, Sub224, Sub225
	HelType Sub226, Sub228, Sub229, Sub231, Sub236, Sub234
	HelType Sub216, Sub218, Sub240, Sub244, Sub201, Sub213
	HelType Sub209, Sub196(HelDim(2)), Sub195(HelDim(2))
	HelType Sub211(HelDim(2)), Sub230(HelDim(2))
	HelType Sub192(HelDim(2)), Sub232(HelDim(2))
	HelType Sub214(HelDim(2)), Sub140(HelDim(2))
	HelType Sub199(HelDim(2)), Sub222(HelDim(2))
	HelType Sub139(HelDim(2)), Sub194(HelDim(2))
	HelType Sub197(HelDim(2)), Sub215(HelDim(2))
	HelType Sub233(HelDim(2)), Sub279(HelDim(2))
	HelType Sub186(HelDim(2)), Sub185(HelDim(2))
	HelType Sub203(HelDim(2)), Sub235(HelDim(2))
	HelType Sub206(HelDim(2)), Sub237(HelDim(2))
	HelType Sub187(HelDim(2)), Sub238(HelDim(2))
	HelType Sub188(HelDim(2)), Sub207(HelDim(2))
	HelType Sub227(HelDim(2)), Sub246(HelDim(2))
	HelType Sub110(HelDim(2)), Sub283(HelDim(2))
	HelType Sub263(HelDim(2),2), Sub144(HelDim(2),2)
	HelType Sub150(HelDim(2),2), Sub153(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub253(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub239(HelDim(2),2), Sub162(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub164(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub167(HelDim(2),2)
	HelType Sub270(HelDim(2),2), Sub272(HelDim(2),2)
	HelType Sub176(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub175(HelDim(2),2)
	HelType Sub266(HelDim(2),2), Sub268(HelDim(2),2)
	HelType Sub284(HelDim(2),2), Sub285(HelDim(2),2)
	HelType Sub287(HelDim(2),2), Sub286(HelDim(2),2)
	HelType Sub289(HelDim(2),2), Sub264(HelDim(2),2)
	HelType Sub265(HelDim(2),2), Sub267(HelDim(2),2)
	HelType Sub269(HelDim(2),2), Sub274(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub256(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub273(HelDim(2),2)
	HelType Sub152(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub158(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub163(HelDim(2),2), Sub177(HelDim(2),2)
	HelType Sub143(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub142(HelDim(2),2), Sub151(HelDim(2),2)
	HelType Sub165(HelDim(2),2), Sub161(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub166(HelDim(2),2), Sub184
	HelType Sub179, Sub183, Sub178, Sub205, Sub202, Sub243
	HelType Sub242, Sub204, Sub190, Sub193(HelDim(2))
	HelType Sub98(HelDim(2)), Sub288(HelDim(2),2)
	HelType Sub254(HelDim(2),2), Sub255(HelDim(2),2), Sub191
	HelType Sub189, Sub293(HelDim(2)), Sub290(HelDim(2),2)
	HelType Sub296(HelDim(2))
	common /varXh/ F1, F8, F11, F5, F9, F3, F10, F2, F6, F7, F4
	common /varXh/ F12, Sub9, F16, F23, F13, F20, F22, F26, F27
	common /varXh/ F19, F21, F24, F14, F15, F31, F33, F40, F42
	common /varXh/ F25, F32, F34, F41, F39, F29, F35, F28, F38
	common /varXh/ F30, F17, F36, F18, F37, Sub182, Sub221
	common /varXh/ Sub217, Sub200, Sub241, Sub219, Sub245
	common /varXh/ Sub220, Sub212, Sub210, Sub223, Sub224
	common /varXh/ Sub225, Sub226, Sub228, Sub229, Sub231
	common /varXh/ Sub236, Sub234, Sub216, Sub218, Sub240
	common /varXh/ Sub244, Sub201, Sub213, Sub209, Sub196
	common /varXh/ Sub195, Sub211, Sub230, Sub192, Sub232
	common /varXh/ Sub214, Sub140, Sub199, Sub222, Sub139
	common /varXh/ Sub194, Sub197, Sub215, Sub233, Sub279
	common /varXh/ Sub186, Sub185, Sub203, Sub235, Sub206
	common /varXh/ Sub237, Sub187, Sub238, Sub188, Sub207
	common /varXh/ Sub227, Sub246, Sub110, Sub283, Sub263
	common /varXh/ Sub144, Sub150, Sub153, Sub157, Sub250
	common /varXh/ Sub253, Sub248, Sub239, Sub162, Sub169
	common /varXh/ Sub164, Sub168, Sub167, Sub270, Sub272
	common /varXh/ Sub176, Sub172, Sub174, Sub175, Sub266
	common /varXh/ Sub268, Sub284, Sub285, Sub287, Sub286
	common /varXh/ Sub289, Sub264, Sub265, Sub267, Sub269
	common /varXh/ Sub274, Sub271, Sub252, Sub256, Sub249
	common /varXh/ Sub251, Sub273, Sub152, Sub170, Sub158
	common /varXh/ Sub171, Sub163, Sub177, Sub143, Sub247
	common /varXh/ Sub142, Sub151, Sub165, Sub161, Sub173
	common /varXh/ Sub166, Sub184, Sub179, Sub183, Sub178
	common /varXh/ Sub205, Sub202, Sub243, Sub242, Sub204
	common /varXh/ Sub190, Sub193, Sub98, Sub288, Sub254, Sub255
	common /varXh/ Sub191, Sub189, Sub293, Sub290, Sub296

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n1n2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
