#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 5-Mar-2015 13:58
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub8, Sub1(2), Sub3(2), Sub6(2), Sub5(2)
	ComplexType Sub4(2)
	ComplexType Sub34, Sub129, Sub130, Sub75, Sub92, Sub33, Sub44
	ComplexType Sub76, Sub93, Sub49, Sub59, Sub50, Sub89, Sub91
	ComplexType Sub69, Sub74, Sub71, Sub40, Sub43, Sub55, Sub61
	ComplexType Sub46, Sub62, Sub47, Sub63, Sub60, Sub37, Sub38
	ComplexType Sub51, Sub53, Sub52, Sub79, Sub80, Sub81, Sub82
	ComplexType Sub39(2), Sub66(2), Sub86(2), Sub88(2), Sub68(2)
	ComplexType Sub73(2), Sub48(2), Sub70(2), Sub72(2), Sub77(2)
	ComplexType Sub85(2), Sub56(2), Sub57(2), Sub94(2), Sub64(2)
	ComplexType Sub90(2), Sub96(2), Sub42(2), Sub65(2), Sub58(2)
	ComplexType Sub87(2), Sub98(2), Sub78(2), Sub97(2)
	ComplexType Sub106(2), Sub14(2), Sub110(2), Sub109(2)
	ComplexType Sub15(2), Sub9(2,2), Sub23(2,2), Sub104(2,2)
	ComplexType Sub107(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub31(2,2,2), Sub35, Sub225, Sub36, Sub10(2,2)
	ComplexType Sub83, Sub32, Sub54, Sub41, Sub45, Sub95, Sub84
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave14(Ncc,2,2), pave15, pave18(Ncc,2)
	common /varXs/ Sub2, Sub8, Sub1, Sub3, Sub6, Sub5, Sub4
	common /varXs/ Sub34, Sub129, Sub130, Sub75, Sub92, Sub33
	common /varXs/ Sub44, Sub76, Sub93, Sub49, Sub59, Sub50
	common /varXs/ Sub89, Sub91, Sub69, Sub74, Sub71, Sub40
	common /varXs/ Sub43, Sub55, Sub61, Sub46, Sub62, Sub47
	common /varXs/ Sub63, Sub60, Sub37, Sub38, Sub51, Sub53
	common /varXs/ Sub52, Sub79, Sub80, Sub81, Sub82, Sub39
	common /varXs/ Sub66, Sub86, Sub88, Sub68, Sub73, Sub48
	common /varXs/ Sub70, Sub72, Sub77, Sub85, Sub56, Sub57
	common /varXs/ Sub94, Sub64, Sub90, Sub96, Sub42, Sub65
	common /varXs/ Sub58, Sub87, Sub98, Sub78, Sub97, Sub106
	common /varXs/ Sub14, Sub110, Sub109, Sub15, Sub9, Sub23
	common /varXs/ Sub104, Sub107, Sub24, Sub25, Sub31, Sub35
	common /varXs/ Sub225, Sub36, Sub10, Sub83, Sub32, Sub54
	common /varXs/ Sub41, Sub45, Sub95, Sub84, pave1, pave2
	common /varXs/ pave3, pave14, pave15, pave18

	ComplexType Sub216, Sub218, Sub226(2), Sub229(2), Sub227(2)
	ComplexType Sub230(2), Sub214(2), Sub215(2), Sub217(2,2)
	ComplexType Sub219(2,2), Sub240(2), Sub243(2), Sub172
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Nbb)
	ComplexType pave7(Nbb), pave8(Nbb,2), pave9(Ncc,2)
	ComplexType pave10(Nbb,2), pave11(Ncc,2), pave12(Ndd,2)
	ComplexType pave13(Ndd,2), pave16(Ncc,2), pave17(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub216, Sub218, Sub226, Sub229, Sub227, Sub230
	common /varXa/ Sub214, Sub215, Sub217, Sub219, Sub240
	common /varXa/ Sub243, Sub172, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave16, pave17, S, T, U

	HelType F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4, F8
	HelType Sub7
	HelType F16, F21, F13, F24, F26, F23, F20, F19, F25, F22, F14
	HelType F15, F39, F41, F35, F32, F27, F40, F42, F38, F33
	HelType F28, F34, F30, F36, F31, F17, F37, F18, F29, Sub148
	HelType Sub156, Sub160, Sub144, Sub131, Sub209, Sub174
	HelType Sub181, Sub180, Sub182, Sub183, Sub175, Sub173
	HelType Sub176, Sub186, Sub187, Sub185, Sub188, Sub166
	HelType Sub169, Sub168, Sub165, Sub149, Sub161
	HelType Sub239(HelDim(2)), Sub140(HelDim(2))
	HelType Sub153(HelDim(2)), Sub141(HelDim(2))
	HelType Sub154(HelDim(2)), Sub136(HelDim(2))
	HelType Sub137(HelDim(2)), Sub147(HelDim(2))
	HelType Sub159(HelDim(2)), Sub167(HelDim(2))
	HelType Sub170(HelDim(2)), Sub162(HelDim(2))
	HelType Sub177(HelDim(2)), Sub150(HelDim(2))
	HelType Sub138(HelDim(2)), Sub142(HelDim(2))
	HelType Sub152(HelDim(2)), Sub155(HelDim(2))
	HelType Sub164(HelDim(2)), Sub171(HelDim(2))
	HelType Sub179(HelDim(2)), Sub139(HelDim(2))
	HelType Sub143(HelDim(2)), Sub184(HelDim(2))
	HelType Sub189(HelDim(2)), Sub194(HelDim(2))
	HelType Sub199(HelDim(2)), Sub228(HelDim(2))
	HelType Sub241(HelDim(2)), Sub231(HelDim(2))
	HelType Sub244(HelDim(2)), Sub101(HelDim(2))
	HelType Sub67(HelDim(2)), Sub99(HelDim(2))
	HelType Sub102(HelDim(2)), Sub117(HelDim(2),2)
	HelType Sub118(HelDim(2),2), Sub122(HelDim(2),2)
	HelType Sub127(HelDim(2),2), Sub128(HelDim(2),2)
	HelType Sub132(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub236(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub206(HelDim(2),2), Sub208(HelDim(2),2)
	HelType Sub212(HelDim(2),2), Sub207(HelDim(2),2)
	HelType Sub205(HelDim(2),2), Sub210(HelDim(2),2)
	HelType Sub202(HelDim(2),2), Sub203(HelDim(2),2)
	HelType Sub108(HelDim(2),2), Sub119(HelDim(2),2)
	HelType Sub125(HelDim(2),2), Sub115(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub116(HelDim(2),2)
	HelType Sub120(HelDim(2),2), Sub111(HelDim(2),2)
	HelType Sub134(HelDim(2),2), Sub200(HelDim(2),2)
	HelType Sub204(HelDim(2),2), Sub201(HelDim(2),2)
	HelType Sub105(HelDim(2),2), Sub114(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub113(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub133, Sub135, Sub146, Sub196
	HelType Sub198, Sub158, Sub191, Sub190, Sub193, Sub192
	HelType Sub195, Sub197, Sub145, Sub157, Sub151(HelDim(2))
	HelType Sub163(HelDim(2)), Sub178(HelDim(2))
	HelType Sub103(HelDim(2)), Sub100(HelDim(2))
	HelType Sub223(HelDim(2),2), Sub220(HelDim(2),2)
	HelType Sub221(HelDim(2),2), Sub237(HelDim(2),2)
	HelType Sub211(HelDim(2),2), Sub213(HelDim(2),2)
	HelType Sub112(HelDim(2),2), Sub121(HelDim(2),2)
	HelType Sub245(HelDim(2)), Sub238(HelDim(2),2)
	HelType Sub242(HelDim(2))
	common /varXh/ F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4
	common /varXh/ F8, Sub7, F16, F21, F13, F24, F26, F23, F20
	common /varXh/ F19, F25, F22, F14, F15, F39, F41, F35, F32
	common /varXh/ F27, F40, F42, F38, F33, F28, F34, F30, F36
	common /varXh/ F31, F17, F37, F18, F29, Sub148, Sub156
	common /varXh/ Sub160, Sub144, Sub131, Sub209, Sub174
	common /varXh/ Sub181, Sub180, Sub182, Sub183, Sub175
	common /varXh/ Sub173, Sub176, Sub186, Sub187, Sub185
	common /varXh/ Sub188, Sub166, Sub169, Sub168, Sub165
	common /varXh/ Sub149, Sub161, Sub239, Sub140, Sub153
	common /varXh/ Sub141, Sub154, Sub136, Sub137, Sub147
	common /varXh/ Sub159, Sub167, Sub170, Sub162, Sub177
	common /varXh/ Sub150, Sub138, Sub142, Sub152, Sub155
	common /varXh/ Sub164, Sub171, Sub179, Sub139, Sub143
	common /varXh/ Sub184, Sub189, Sub194, Sub199, Sub228
	common /varXh/ Sub241, Sub231, Sub244, Sub101, Sub67, Sub99
	common /varXh/ Sub102, Sub117, Sub118, Sub122, Sub127
	common /varXh/ Sub128, Sub132, Sub232, Sub233, Sub235
	common /varXh/ Sub234, Sub236, Sub222, Sub224, Sub206
	common /varXh/ Sub208, Sub212, Sub207, Sub205, Sub210
	common /varXh/ Sub202, Sub203, Sub108, Sub119, Sub125
	common /varXh/ Sub115, Sub126, Sub116, Sub120, Sub111
	common /varXh/ Sub134, Sub200, Sub204, Sub201, Sub105
	common /varXh/ Sub114, Sub124, Sub113, Sub123, Sub133
	common /varXh/ Sub135, Sub146, Sub196, Sub198, Sub158
	common /varXh/ Sub191, Sub190, Sub193, Sub192, Sub195
	common /varXh/ Sub197, Sub145, Sub157, Sub151, Sub163
	common /varXh/ Sub178, Sub103, Sub100, Sub223, Sub220
	common /varXh/ Sub221, Sub237, Sub211, Sub213, Sub112
	common /varXh/ Sub121, Sub245, Sub238, Sub242

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n1n1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
