#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:38
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub7, Sub13, Sub14, Sub9(2), Sub3(2)
	ComplexType Sub1(2), Sub8(2), Sub11(2), Sub10(2), Sub4(2)
	ComplexType Sub6(2), Sub5(2), Sub12(2)
	ComplexType Sub43, Sub174, Sub175, Sub53, Sub86, Sub42
	ComplexType Sub102, Sub54, Sub87, Sub66, Sub75, Sub67, Sub83
	ComplexType Sub85, Sub47, Sub52, Sub49, Sub98, Sub101, Sub68
	ComplexType Sub71, Sub78, Sub115, Sub79, Sub116, Sub80
	ComplexType Sub77, Sub110, Sub111, Sub119, Sub122, Sub104
	ComplexType Sub123, Sub105, Sub124, Sub121, Sub95, Sub96
	ComplexType Sub69, Sub57, Sub58, Sub59, Sub60, Sub112(2)
	ComplexType Sub97(2), Sub131(2), Sub64(2), Sub107(2)
	ComplexType Sub127(2), Sub108(2), Sub46(2), Sub51(2)
	ComplexType Sub106(2), Sub117(2), Sub48(2), Sub50(2)
	ComplexType Sub55(2), Sub63(2), Sub130(2), Sub72(2)
	ComplexType Sub73(2), Sub88(2), Sub125(2), Sub81(2)
	ComplexType Sub84(2), Sub135(2), Sub91(2), Sub114(2)
	ComplexType Sub82(2), Sub74(2), Sub100(2), Sub126(2)
	ComplexType Sub120(2), Sub132(2), Sub93(2), Sub128(2)
	ComplexType Sub92(2), Sub65(2), Sub137(2), Sub56(2)
	ComplexType Sub136(2), Sub152(2), Sub28(2), Sub139(2)
	ComplexType Sub23(2), Sub155(2), Sub154(2), Sub29(2)
	ComplexType Sub145(2), Sub144(2), Sub24(2), Sub17(2,2)
	ComplexType Sub32(2,2), Sub148(2,2), Sub141(2,2)
	ComplexType Sub153(2,2), Sub140(2,2), Sub156(2,2)
	ComplexType Sub33(2,2), Sub34(2,2), Sub40(2,2,2), Sub44
	ComplexType Sub273, Sub45, Sub16(2,2), Sub129, Sub61, Sub41
	ComplexType Sub70, Sub118, Sub113, Sub99, Sub76, Sub103
	ComplexType Sub89, Sub134, Sub90, Sub62, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave14(Ncc,2)
	ComplexType pave15(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub2, Sub7, Sub13, Sub14, Sub9, Sub3, Sub1
	common /varXs/ Sub8, Sub11, Sub10, Sub4, Sub6, Sub5, Sub12
	common /varXs/ Sub43, Sub174, Sub175, Sub53, Sub86, Sub42
	common /varXs/ Sub102, Sub54, Sub87, Sub66, Sub75, Sub67
	common /varXs/ Sub83, Sub85, Sub47, Sub52, Sub49, Sub98
	common /varXs/ Sub101, Sub68, Sub71, Sub78, Sub115, Sub79
	common /varXs/ Sub116, Sub80, Sub77, Sub110, Sub111, Sub119
	common /varXs/ Sub122, Sub104, Sub123, Sub105, Sub124
	common /varXs/ Sub121, Sub95, Sub96, Sub69, Sub57, Sub58
	common /varXs/ Sub59, Sub60, Sub112, Sub97, Sub131, Sub64
	common /varXs/ Sub107, Sub127, Sub108, Sub46, Sub51, Sub106
	common /varXs/ Sub117, Sub48, Sub50, Sub55, Sub63, Sub130
	common /varXs/ Sub72, Sub73, Sub88, Sub125, Sub81, Sub84
	common /varXs/ Sub135, Sub91, Sub114, Sub82, Sub74, Sub100
	common /varXs/ Sub126, Sub120, Sub132, Sub93, Sub128, Sub92
	common /varXs/ Sub65, Sub137, Sub56, Sub136, Sub152, Sub28
	common /varXs/ Sub139, Sub23, Sub155, Sub154, Sub29, Sub145
	common /varXs/ Sub144, Sub24, Sub17, Sub32, Sub148, Sub141
	common /varXs/ Sub153, Sub140, Sub156, Sub33, Sub34, Sub40
	common /varXs/ Sub44, Sub273, Sub45, Sub16, Sub129, Sub61
	common /varXs/ Sub41, Sub70, Sub118, Sub113, Sub99, Sub76
	common /varXs/ Sub103, Sub89, Sub134, Sub90, Sub62, pave1
	common /varXs/ pave2, pave3, pave14, pave15, pave18, pave23

	ComplexType Sub259, Sub257, Sub279(2), Sub275(2), Sub294(2)
	ComplexType Sub292(2), Sub295(2), Sub293(2), Sub278(2)
	ComplexType Sub274(2), Sub256(2), Sub255(2), Sub260(2,2)
	ComplexType Sub258(2,2), Sub211, Sub189, Sub276(2)
	ComplexType Sub280(2), pave4(Ndd,2,2), pave5(Ndd,2,2)
	ComplexType pave6(Nbb), pave7(Nbb), pave8(Ncc,2)
	ComplexType pave9(Ncc,2), pave10(Ncc,2), pave11(Ncc,2)
	ComplexType pave12(Ndd,2), pave13(Ndd,2), pave16(Nbb,2)
	ComplexType pave17(Nbb,2), pave19(Ncc,2), pave20(Ncc,2)
	ComplexType pave21(Ncc,2), pave22(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub259, Sub257, Sub279, Sub275, Sub294, Sub292
	common /varXa/ Sub295, Sub293, Sub278, Sub274, Sub256
	common /varXa/ Sub255, Sub260, Sub258, Sub211, Sub189
	common /varXa/ Sub276, Sub280, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave16, pave17, pave19, pave20, pave21
	common /varXa/ pave22, S, T, U

	HelType F1, F11, F5, F7, F12, F3, F10, F2, F8, F9, F4, F6
	HelType Sub15
	HelType F16, F26, F13, F22, F24, F20, F21, F19, F23, F27, F14
	HelType F15, F30, F33, F36, F42, F25, F31, F34, F38, F35
	HelType F28, F37, F29, F41, F32, F17, F39, F18, F40, Sub176
	HelType Sub231, Sub227, Sub203, Sub220, Sub230, Sub224
	HelType Sub229, Sub233, Sub234, Sub235, Sub236, Sub215
	HelType Sub213, Sub239, Sub238, Sub241, Sub200, Sub198
	HelType Sub228, Sub226, Sub219, Sub223, Sub204, Sub212
	HelType Sub216, Sub289(HelDim(2)), Sub184(HelDim(2))
	HelType Sub183(HelDim(2)), Sub214(HelDim(2))
	HelType Sub240(HelDim(2)), Sub194(HelDim(2))
	HelType Sub242(HelDim(2)), Sub217(HelDim(2))
	HelType Sub185(HelDim(2)), Sub196(HelDim(2))
	HelType Sub218(HelDim(2)), Sub197(HelDim(2))
	HelType Sub232(HelDim(2)), Sub243(HelDim(2))
	HelType Sub277(HelDim(2)), Sub188(HelDim(2))
	HelType Sub202(HelDim(2)), Sub210(HelDim(2))
	HelType Sub186(HelDim(2)), Sub187(HelDim(2))
	HelType Sub201(HelDim(2)), Sub206(HelDim(2))
	HelType Sub209(HelDim(2)), Sub199(HelDim(2))
	HelType Sub190(HelDim(2)), Sub138(HelDim(2))
	HelType Sub281(HelDim(2)), Sub225(HelDim(2))
	HelType Sub237(HelDim(2)), Sub94(HelDim(2))
	HelType Sub109(HelDim(2)), Sub261(HelDim(2),2)
	HelType Sub142(HelDim(2),2), Sub147(HelDim(2),2)
	HelType Sub151(HelDim(2),2), Sub157(HelDim(2),2)
	HelType Sub160(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub166(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub165(HelDim(2),2), Sub270(HelDim(2),2)
	HelType Sub177(HelDim(2),2), Sub168(HelDim(2),2)
	HelType Sub268(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub264(HelDim(2),2)
	HelType Sub265(HelDim(2),2), Sub282(HelDim(2),2)
	HelType Sub283(HelDim(2),2), Sub285(HelDim(2),2)
	HelType Sub284(HelDim(2),2), Sub286(HelDim(2),2)
	HelType Sub262(HelDim(2),2), Sub263(HelDim(2),2)
	HelType Sub272(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub244(HelDim(2),2), Sub267(HelDim(2),2)
	HelType Sub266(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub253(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub271(HelDim(2),2), Sub159(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub143(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub164(HelDim(2),2)
	HelType Sub180(HelDim(2),2), Sub150(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub149(HelDim(2),2)
	HelType Sub161(HelDim(2),2), Sub158(HelDim(2),2)
	HelType Sub146(HelDim(2),2), Sub162(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub182, Sub179, Sub181, Sub178
	HelType Sub208, Sub205, Sub222, Sub221, Sub207, Sub192
	HelType Sub195(HelDim(2)), Sub133(HelDim(2))
	HelType Sub287(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub254(HelDim(2),2), Sub193, Sub191
	HelType Sub291(HelDim(2)), Sub288(HelDim(2),2)
	HelType Sub290(HelDim(2))
	common /varXh/ F1, F11, F5, F7, F12, F3, F10, F2, F8, F9, F4
	common /varXh/ F6, Sub15, F16, F26, F13, F22, F24, F20, F21
	common /varXh/ F19, F23, F27, F14, F15, F30, F33, F36, F42
	common /varXh/ F25, F31, F34, F38, F35, F28, F37, F29, F41
	common /varXh/ F32, F17, F39, F18, F40, Sub176, Sub231
	common /varXh/ Sub227, Sub203, Sub220, Sub230, Sub224
	common /varXh/ Sub229, Sub233, Sub234, Sub235, Sub236
	common /varXh/ Sub215, Sub213, Sub239, Sub238, Sub241
	common /varXh/ Sub200, Sub198, Sub228, Sub226, Sub219
	common /varXh/ Sub223, Sub204, Sub212, Sub216, Sub289
	common /varXh/ Sub184, Sub183, Sub214, Sub240, Sub194
	common /varXh/ Sub242, Sub217, Sub185, Sub196, Sub218
	common /varXh/ Sub197, Sub232, Sub243, Sub277, Sub188
	common /varXh/ Sub202, Sub210, Sub186, Sub187, Sub201
	common /varXh/ Sub206, Sub209, Sub199, Sub190, Sub138
	common /varXh/ Sub281, Sub225, Sub237, Sub94, Sub109, Sub261
	common /varXh/ Sub142, Sub147, Sub151, Sub157, Sub160
	common /varXh/ Sub163, Sub166, Sub169, Sub165, Sub270
	common /varXh/ Sub177, Sub168, Sub268, Sub172, Sub173
	common /varXh/ Sub264, Sub265, Sub282, Sub283, Sub285
	common /varXh/ Sub284, Sub286, Sub262, Sub263, Sub272
	common /varXh/ Sub249, Sub251, Sub247, Sub244, Sub267
	common /varXh/ Sub266, Sub250, Sub253, Sub248, Sub245
	common /varXh/ Sub269, Sub271, Sub159, Sub170, Sub143
	common /varXh/ Sub171, Sub164, Sub180, Sub150, Sub246
	common /varXh/ Sub149, Sub161, Sub158, Sub146, Sub162
	common /varXh/ Sub167, Sub182, Sub179, Sub181, Sub178
	common /varXh/ Sub208, Sub205, Sub222, Sub221, Sub207
	common /varXh/ Sub192, Sub195, Sub133, Sub287, Sub252
	common /varXh/ Sub254, Sub193, Sub191, Sub291, Sub288, Sub290

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n2n3_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
