#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:55
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub7, Sub13, Sub14, Sub9(2), Sub3(2)
	ComplexType Sub1(2), Sub8(2), Sub11(2), Sub10(2), Sub4(2)
	ComplexType Sub6(2), Sub5(2), Sub12(2)
	ComplexType Sub43, Sub175, Sub176, Sub83, Sub100, Sub42
	ComplexType Sub53, Sub101, Sub84, Sub58, Sub67, Sub59, Sub97
	ComplexType Sub99, Sub77, Sub82, Sub79, Sub49, Sub52, Sub60
	ComplexType Sub61, Sub115, Sub118, Sub55, Sub119, Sub56
	ComplexType Sub120, Sub117, Sub46, Sub47, Sub63, Sub70
	ComplexType Sub128, Sub71, Sub129, Sub72, Sub69, Sub131
	ComplexType Sub132, Sub87, Sub88, Sub89, Sub90, Sub133(2)
	ComplexType Sub48(2), Sub112(2), Sub136(2), Sub137(2)
	ComplexType Sub75(2), Sub94(2), Sub76(2), Sub81(2)
	ComplexType Sub135(2), Sub57(2), Sub78(2), Sub80(2)
	ComplexType Sub111(2), Sub85(2), Sub93(2), Sub64(2)
	ComplexType Sub65(2), Sub102(2), Sub121(2), Sub73(2)
	ComplexType Sub98(2), Sub105(2), Sub124(2), Sub51(2)
	ComplexType Sub122(2), Sub116(2), Sub134(2), Sub74(2)
	ComplexType Sub66(2), Sub95(2), Sub126(2), Sub125(2)
	ComplexType Sub86(2), Sub113(2), Sub107(2), Sub106(2)
	ComplexType Sub109(2), Sub152(2), Sub28(2), Sub143(2)
	ComplexType Sub23(2), Sub155(2), Sub154(2), Sub29(2)
	ComplexType Sub149(2), Sub148(2), Sub24(2), Sub17(2,2)
	ComplexType Sub32(2,2), Sub139(2,2), Sub145(2,2)
	ComplexType Sub153(2,2), Sub144(2,2), Sub156(2,2)
	ComplexType Sub33(2,2), Sub34(2,2), Sub40(2,2,2), Sub44
	ComplexType Sub273, Sub45, Sub16(2,2), Sub91, Sub110, Sub41
	ComplexType Sub114, Sub62, Sub50, Sub130, Sub54, Sub68
	ComplexType Sub123, Sub103, Sub92, Sub104, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave14(Ncc,2)
	ComplexType pave15(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub2, Sub7, Sub13, Sub14, Sub9, Sub3, Sub1
	common /varXs/ Sub8, Sub11, Sub10, Sub4, Sub6, Sub5, Sub12
	common /varXs/ Sub43, Sub175, Sub176, Sub83, Sub100, Sub42
	common /varXs/ Sub53, Sub101, Sub84, Sub58, Sub67, Sub59
	common /varXs/ Sub97, Sub99, Sub77, Sub82, Sub79, Sub49
	common /varXs/ Sub52, Sub60, Sub61, Sub115, Sub118, Sub55
	common /varXs/ Sub119, Sub56, Sub120, Sub117, Sub46, Sub47
	common /varXs/ Sub63, Sub70, Sub128, Sub71, Sub129, Sub72
	common /varXs/ Sub69, Sub131, Sub132, Sub87, Sub88, Sub89
	common /varXs/ Sub90, Sub133, Sub48, Sub112, Sub136, Sub137
	common /varXs/ Sub75, Sub94, Sub76, Sub81, Sub135, Sub57
	common /varXs/ Sub78, Sub80, Sub111, Sub85, Sub93, Sub64
	common /varXs/ Sub65, Sub102, Sub121, Sub73, Sub98, Sub105
	common /varXs/ Sub124, Sub51, Sub122, Sub116, Sub134, Sub74
	common /varXs/ Sub66, Sub95, Sub126, Sub125, Sub86, Sub113
	common /varXs/ Sub107, Sub106, Sub109, Sub152, Sub28, Sub143
	common /varXs/ Sub23, Sub155, Sub154, Sub29, Sub149, Sub148
	common /varXs/ Sub24, Sub17, Sub32, Sub139, Sub145, Sub153
	common /varXs/ Sub144, Sub156, Sub33, Sub34, Sub40, Sub44
	common /varXs/ Sub273, Sub45, Sub16, Sub91, Sub110, Sub41
	common /varXs/ Sub114, Sub62, Sub50, Sub130, Sub54, Sub68
	common /varXs/ Sub123, Sub103, Sub92, Sub104, pave1, pave2
	common /varXs/ pave3, pave14, pave15, pave18, pave23

	ComplexType Sub259, Sub257, Sub279(2), Sub275(2), Sub293(2)
	ComplexType Sub291(2), Sub294(2), Sub292(2), Sub278(2)
	ComplexType Sub274(2), Sub256(2), Sub255(2), Sub260(2,2)
	ComplexType Sub258(2,2), Sub206, Sub197, Sub276(2)
	ComplexType Sub280(2), pave4(Ndd,2,2), pave5(Ndd,2,2)
	ComplexType pave6(Ndd,2), pave7(Ndd,2), pave8(Nbb)
	ComplexType pave9(Nbb), pave10(Ncc,2), pave11(Ncc,2)
	ComplexType pave12(Ncc,2), pave13(Ncc,2), pave16(Nbb,2)
	ComplexType pave17(Nbb,2), pave19(Ncc,2), pave20(Ncc,2)
	ComplexType pave21(Ncc,2), pave22(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub259, Sub257, Sub279, Sub275, Sub293, Sub291
	common /varXa/ Sub294, Sub292, Sub278, Sub274, Sub256
	common /varXa/ Sub255, Sub260, Sub258, Sub206, Sub197
	common /varXa/ Sub276, Sub280, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave16, pave17, pave19, pave20, pave21
	common /varXa/ pave22, S, T, U

	HelType F1, F3, F8, F5, F4, F11, F10, F2, F6, F7, F12, F9
	HelType Sub15
	HelType F16, F26, F13, F19, F23, F21, F24, F22, F20, F27, F14
	HelType F15, F29, F33, F39, F42, F25, F30, F34, F40, F38
	HelType F32, F35, F28, F41, F31, F17, F36, F18, F37, Sub177
	HelType Sub242, Sub238, Sub198, Sub221, Sub240, Sub225
	HelType Sub241, Sub210, Sub208, Sub232, Sub233, Sub234
	HelType Sub235, Sub215, Sub214, Sub217, Sub229, Sub227
	HelType Sub239, Sub237, Sub220, Sub224, Sub199, Sub207
	HelType Sub211, Sub138(HelDim(2)), Sub187(HelDim(2))
	HelType Sub188(HelDim(2)), Sub209(HelDim(2))
	HelType Sub216(HelDim(2)), Sub193(HelDim(2))
	HelType Sub218(HelDim(2)), Sub212(HelDim(2))
	HelType Sub127(HelDim(2)), Sub189(HelDim(2))
	HelType Sub195(HelDim(2)), Sub213(HelDim(2))
	HelType Sub196(HelDim(2)), Sub219(HelDim(2))
	HelType Sub243(HelDim(2)), Sub277(HelDim(2))
	HelType Sub186(HelDim(2)), Sub205(HelDim(2))
	HelType Sub231(HelDim(2)), Sub184(HelDim(2))
	HelType Sub185(HelDim(2)), Sub201(HelDim(2))
	HelType Sub204(HelDim(2)), Sub230(HelDim(2))
	HelType Sub228(HelDim(2)), Sub183(HelDim(2))
	HelType Sub226(HelDim(2)), Sub236(HelDim(2))
	HelType Sub108(HelDim(2)), Sub281(HelDim(2))
	HelType Sub261(HelDim(2),2), Sub142(HelDim(2),2)
	HelType Sub146(HelDim(2),2), Sub151(HelDim(2),2)
	HelType Sub157(HelDim(2),2), Sub160(HelDim(2),2)
	HelType Sub166(HelDim(2),2), Sub162(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub165(HelDim(2),2)
	HelType Sub268(HelDim(2),2), Sub270(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub264(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub282(HelDim(2),2), Sub283(HelDim(2),2)
	HelType Sub285(HelDim(2),2), Sub284(HelDim(2),2)
	HelType Sub286(HelDim(2),2), Sub262(HelDim(2),2)
	HelType Sub263(HelDim(2),2), Sub272(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub266(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub244(HelDim(2),2)
	HelType Sub269(HelDim(2),2), Sub271(HelDim(2),2)
	HelType Sub159(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub147(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub161(HelDim(2),2), Sub180(HelDim(2),2)
	HelType Sub140(HelDim(2),2), Sub141(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub158(HelDim(2),2), Sub150(HelDim(2),2)
	HelType Sub164(HelDim(2),2), Sub168(HelDim(2),2), Sub182
	HelType Sub179, Sub181, Sub178, Sub203, Sub200, Sub223
	HelType Sub222, Sub191, Sub202, Sub194(HelDim(2))
	HelType Sub96(HelDim(2)), Sub287(HelDim(2),2)
	HelType Sub254(HelDim(2),2), Sub253(HelDim(2),2), Sub192
	HelType Sub190, Sub290(HelDim(2)), Sub288(HelDim(2),2)
	HelType Sub289(HelDim(2))
	common /varXh/ F1, F3, F8, F5, F4, F11, F10, F2, F6, F7, F12
	common /varXh/ F9, Sub15, F16, F26, F13, F19, F23, F21, F24
	common /varXh/ F22, F20, F27, F14, F15, F29, F33, F39, F42
	common /varXh/ F25, F30, F34, F40, F38, F32, F35, F28, F41
	common /varXh/ F31, F17, F36, F18, F37, Sub177, Sub242
	common /varXh/ Sub238, Sub198, Sub221, Sub240, Sub225
	common /varXh/ Sub241, Sub210, Sub208, Sub232, Sub233
	common /varXh/ Sub234, Sub235, Sub215, Sub214, Sub217
	common /varXh/ Sub229, Sub227, Sub239, Sub237, Sub220
	common /varXh/ Sub224, Sub199, Sub207, Sub211, Sub138
	common /varXh/ Sub187, Sub188, Sub209, Sub216, Sub193
	common /varXh/ Sub218, Sub212, Sub127, Sub189, Sub195
	common /varXh/ Sub213, Sub196, Sub219, Sub243, Sub277
	common /varXh/ Sub186, Sub205, Sub231, Sub184, Sub185
	common /varXh/ Sub201, Sub204, Sub230, Sub228, Sub183
	common /varXh/ Sub226, Sub236, Sub108, Sub281, Sub261
	common /varXh/ Sub142, Sub146, Sub151, Sub157, Sub160
	common /varXh/ Sub166, Sub162, Sub167, Sub165, Sub268
	common /varXh/ Sub270, Sub174, Sub169, Sub173, Sub172
	common /varXh/ Sub264, Sub265, Sub282, Sub283, Sub285
	common /varXh/ Sub284, Sub286, Sub262, Sub263, Sub272
	common /varXh/ Sub250, Sub252, Sub248, Sub245, Sub267
	common /varXh/ Sub266, Sub249, Sub251, Sub247, Sub244
	common /varXh/ Sub269, Sub271, Sub159, Sub170, Sub147
	common /varXh/ Sub171, Sub161, Sub180, Sub140, Sub141
	common /varXh/ Sub246, Sub163, Sub158, Sub150, Sub164
	common /varXh/ Sub168, Sub182, Sub179, Sub181, Sub178
	common /varXh/ Sub203, Sub200, Sub223, Sub222, Sub191
	common /varXh/ Sub202, Sub194, Sub96, Sub287, Sub254, Sub253
	common /varXh/ Sub192, Sub190, Sub290, Sub288, Sub289

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n3n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
