#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:50
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub8, Sub1(2), Sub3(2), Sub6(2), Sub5(2)
	ComplexType Sub4(2)
	ComplexType Sub36, Sub131, Sub132, Sub77, Sub94, Sub35, Sub46
	ComplexType Sub78, Sub95, Sub51, Sub61, Sub52, Sub91, Sub93
	ComplexType Sub71, Sub76, Sub73, Sub42, Sub45, Sub53, Sub54
	ComplexType Sub57, Sub63, Sub48, Sub64, Sub49, Sub65, Sub62
	ComplexType Sub39, Sub40, Sub55, Sub81, Sub82, Sub83, Sub84
	ComplexType Sub41(2), Sub68(2), Sub88(2), Sub90(2), Sub70(2)
	ComplexType Sub75(2), Sub50(2), Sub72(2), Sub74(2), Sub79(2)
	ComplexType Sub87(2), Sub58(2), Sub59(2), Sub96(2), Sub66(2)
	ComplexType Sub92(2), Sub98(2), Sub44(2), Sub67(2), Sub60(2)
	ComplexType Sub89(2), Sub100(2), Sub80(2), Sub99(2)
	ComplexType Sub108(2), Sub14(2), Sub112(2), Sub111(2)
	ComplexType Sub15(2), Sub10(2,2), Sub23(2,2), Sub106(2,2)
	ComplexType Sub109(2,2), Sub25(2,2), Sub26(2,2)
	ComplexType Sub32(2,2,2), Sub37, Sub227, Sub38, Sub9(2,2)
	ComplexType Sub85, Sub34, Sub56, Sub43, Sub47, Sub97, Sub86
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave14(Ncc,2,2), pave15, pave18(Ncc,2)
	common /varXs/ Sub2, Sub8, Sub1, Sub3, Sub6, Sub5, Sub4
	common /varXs/ Sub36, Sub131, Sub132, Sub77, Sub94, Sub35
	common /varXs/ Sub46, Sub78, Sub95, Sub51, Sub61, Sub52
	common /varXs/ Sub91, Sub93, Sub71, Sub76, Sub73, Sub42
	common /varXs/ Sub45, Sub53, Sub54, Sub57, Sub63, Sub48
	common /varXs/ Sub64, Sub49, Sub65, Sub62, Sub39, Sub40
	common /varXs/ Sub55, Sub81, Sub82, Sub83, Sub84, Sub41
	common /varXs/ Sub68, Sub88, Sub90, Sub70, Sub75, Sub50
	common /varXs/ Sub72, Sub74, Sub79, Sub87, Sub58, Sub59
	common /varXs/ Sub96, Sub66, Sub92, Sub98, Sub44, Sub67
	common /varXs/ Sub60, Sub89, Sub100, Sub80, Sub99, Sub108
	common /varXs/ Sub14, Sub112, Sub111, Sub15, Sub10, Sub23
	common /varXs/ Sub106, Sub109, Sub25, Sub26, Sub32, Sub37
	common /varXs/ Sub227, Sub38, Sub9, Sub85, Sub34, Sub56
	common /varXs/ Sub43, Sub47, Sub97, Sub86, pave1, pave2
	common /varXs/ pave3, pave14, pave15, pave18

	ComplexType Sub218, Sub220, Sub228(2), Sub231(2), Sub229(2)
	ComplexType Sub232(2), Sub216(2), Sub217(2), Sub219(2,2)
	ComplexType Sub221(2,2), Sub24(2,2), Sub33(2,2), Sub244(2)
	ComplexType Sub245(2), Sub184, pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Nbb), pave7(Nbb)
	ComplexType pave8(Nbb,2), pave9(Ncc,2), pave10(Nbb,2)
	ComplexType pave11(Ncc,2), pave12(Ndd,2), pave13(Ndd,2)
	ComplexType pave16(Ncc,2), pave17(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub218, Sub220, Sub228, Sub231, Sub229, Sub232
	common /varXa/ Sub216, Sub217, Sub219, Sub221, Sub24, Sub33
	common /varXa/ Sub244, Sub245, Sub184, pave4, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave10, pave11, pave12
	common /varXa/ pave13, pave16, pave17, S, T, U

	HelType F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4, F8
	HelType Sub7
	HelType F16, F21, F13, F25, F26, F23, F19, F20, F28, F22, F14
	HelType F15, F33, F41, F39, F36, F24, F34, F42, F40, F37
	HelType F27, F29, F32, F38, F35, F17, F30, F18, F31, Sub165
	HelType Sub170, Sub174, Sub161, Sub133, Sub210, Sub198
	HelType Sub186, Sub197, Sub199, Sub200, Sub187, Sub185
	HelType Sub188, Sub157, Sub158, Sub156, Sub159, Sub149
	HelType Sub152, Sub151, Sub148, Sub166, Sub175
	HelType Sub241(HelDim(2)), Sub138(HelDim(2))
	HelType Sub141(HelDim(2)), Sub139(HelDim(2))
	HelType Sub142(HelDim(2)), Sub144(HelDim(2))
	HelType Sub145(HelDim(2)), Sub150(HelDim(2))
	HelType Sub153(HelDim(2)), Sub164(HelDim(2))
	HelType Sub173(HelDim(2)), Sub176(HelDim(2))
	HelType Sub189(HelDim(2)), Sub167(HelDim(2))
	HelType Sub140(HelDim(2)), Sub143(HelDim(2))
	HelType Sub146(HelDim(2)), Sub154(HelDim(2))
	HelType Sub169(HelDim(2)), Sub178(HelDim(2))
	HelType Sub191(HelDim(2)), Sub155(HelDim(2))
	HelType Sub147(HelDim(2)), Sub160(HelDim(2))
	HelType Sub183(HelDim(2)), Sub196(HelDim(2))
	HelType Sub201(HelDim(2)), Sub230(HelDim(2))
	HelType Sub233(HelDim(2)), Sub246(HelDim(2))
	HelType Sub103(HelDim(2)), Sub69(HelDim(2))
	HelType Sub101(HelDim(2)), Sub104(HelDim(2))
	HelType Sub122(HelDim(2),2), Sub130(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub128(HelDim(2),2)
	HelType Sub129(HelDim(2),2), Sub136(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub240(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub226(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub208(HelDim(2),2), Sub213(HelDim(2),2)
	HelType Sub209(HelDim(2),2), Sub207(HelDim(2),2)
	HelType Sub211(HelDim(2),2), Sub204(HelDim(2),2)
	HelType Sub205(HelDim(2),2), Sub110(HelDim(2),2)
	HelType Sub115(HelDim(2),2), Sub126(HelDim(2),2)
	HelType Sub120(HelDim(2),2), Sub127(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub116(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub135(HelDim(2),2)
	HelType Sub203(HelDim(2),2), Sub206(HelDim(2),2)
	HelType Sub202(HelDim(2),2), Sub107(HelDim(2),2)
	HelType Sub119(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub118(HelDim(2),2), Sub124(HelDim(2),2), Sub134
	HelType Sub137, Sub163, Sub180, Sub182, Sub172, Sub193
	HelType Sub192, Sub195, Sub194, Sub179, Sub181, Sub162
	HelType Sub171, Sub168(HelDim(2)), Sub177(HelDim(2))
	HelType Sub190(HelDim(2)), Sub105(HelDim(2))
	HelType Sub102(HelDim(2)), Sub222(HelDim(2),2)
	HelType Sub224(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub238(HelDim(2),2), Sub212(HelDim(2),2)
	HelType Sub214(HelDim(2),2), Sub114(HelDim(2),2)
	HelType Sub117(HelDim(2),2), Sub243(HelDim(2))
	HelType Sub239(HelDim(2),2), Sub242(HelDim(2))
	common /varXh/ F1, F5, F7, F9, F6, F3, F11, F2, F12, F10, F4
	common /varXh/ F8, Sub7, F16, F21, F13, F25, F26, F23, F19
	common /varXh/ F20, F28, F22, F14, F15, F33, F41, F39, F36
	common /varXh/ F24, F34, F42, F40, F37, F27, F29, F32, F38
	common /varXh/ F35, F17, F30, F18, F31, Sub165, Sub170
	common /varXh/ Sub174, Sub161, Sub133, Sub210, Sub198
	common /varXh/ Sub186, Sub197, Sub199, Sub200, Sub187
	common /varXh/ Sub185, Sub188, Sub157, Sub158, Sub156
	common /varXh/ Sub159, Sub149, Sub152, Sub151, Sub148
	common /varXh/ Sub166, Sub175, Sub241, Sub138, Sub141
	common /varXh/ Sub139, Sub142, Sub144, Sub145, Sub150
	common /varXh/ Sub153, Sub164, Sub173, Sub176, Sub189
	common /varXh/ Sub167, Sub140, Sub143, Sub146, Sub154
	common /varXh/ Sub169, Sub178, Sub191, Sub155, Sub147
	common /varXh/ Sub160, Sub183, Sub196, Sub201, Sub230
	common /varXh/ Sub233, Sub246, Sub103, Sub69, Sub101, Sub104
	common /varXh/ Sub122, Sub130, Sub123, Sub128, Sub129
	common /varXh/ Sub136, Sub234, Sub240, Sub236, Sub235
	common /varXh/ Sub237, Sub223, Sub226, Sub215, Sub208
	common /varXh/ Sub213, Sub209, Sub207, Sub211, Sub204
	common /varXh/ Sub205, Sub110, Sub115, Sub126, Sub120
	common /varXh/ Sub127, Sub121, Sub116, Sub113, Sub135
	common /varXh/ Sub203, Sub206, Sub202, Sub107, Sub119
	common /varXh/ Sub125, Sub118, Sub124, Sub134, Sub137
	common /varXh/ Sub163, Sub180, Sub182, Sub172, Sub193
	common /varXh/ Sub192, Sub195, Sub194, Sub179, Sub181
	common /varXh/ Sub162, Sub171, Sub168, Sub177, Sub190
	common /varXh/ Sub105, Sub102, Sub222, Sub224, Sub225
	common /varXh/ Sub238, Sub212, Sub214, Sub114, Sub117
	common /varXh/ Sub243, Sub239, Sub242

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n3n3_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
