#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:56
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub8, Sub1(2), Sub3(2), Sub6(2), Sub5(2)
	ComplexType Sub4(2)
	ComplexType Sub34, Sub129, Sub130, Sub75, Sub92, Sub33, Sub38
	ComplexType Sub76, Sub93, Sub49, Sub59, Sub50, Sub89, Sub91
	ComplexType Sub69, Sub74, Sub71, Sub42, Sub37, Sub51, Sub52
	ComplexType Sub53, Sub55, Sub61, Sub40, Sub62, Sub41, Sub63
	ComplexType Sub60, Sub44, Sub45, Sub79, Sub80, Sub81, Sub82
	ComplexType Sub46(2), Sub66(2), Sub86(2), Sub88(2), Sub68(2)
	ComplexType Sub73(2), Sub48(2), Sub70(2), Sub72(2), Sub77(2)
	ComplexType Sub85(2), Sub56(2), Sub57(2), Sub94(2), Sub64(2)
	ComplexType Sub90(2), Sub96(2), Sub47(2), Sub65(2), Sub58(2)
	ComplexType Sub87(2), Sub98(2), Sub78(2), Sub97(2)
	ComplexType Sub106(2), Sub16(2), Sub110(2), Sub109(2)
	ComplexType Sub17(2), Sub9(2,2), Sub23(2,2), Sub104(2,2)
	ComplexType Sub107(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub31(2,2,2), Sub35, Sub225, Sub36, Sub10(2,2)
	ComplexType Sub83, Sub32, Sub54, Sub43, Sub39, Sub95, Sub84
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave14(Ncc,2,2), pave15, pave18(Ncc,2)
	common /varXs/ Sub2, Sub8, Sub1, Sub3, Sub6, Sub5, Sub4
	common /varXs/ Sub34, Sub129, Sub130, Sub75, Sub92, Sub33
	common /varXs/ Sub38, Sub76, Sub93, Sub49, Sub59, Sub50
	common /varXs/ Sub89, Sub91, Sub69, Sub74, Sub71, Sub42
	common /varXs/ Sub37, Sub51, Sub52, Sub53, Sub55, Sub61
	common /varXs/ Sub40, Sub62, Sub41, Sub63, Sub60, Sub44
	common /varXs/ Sub45, Sub79, Sub80, Sub81, Sub82, Sub46
	common /varXs/ Sub66, Sub86, Sub88, Sub68, Sub73, Sub48
	common /varXs/ Sub70, Sub72, Sub77, Sub85, Sub56, Sub57
	common /varXs/ Sub94, Sub64, Sub90, Sub96, Sub47, Sub65
	common /varXs/ Sub58, Sub87, Sub98, Sub78, Sub97, Sub106
	common /varXs/ Sub16, Sub110, Sub109, Sub17, Sub9, Sub23
	common /varXs/ Sub104, Sub107, Sub24, Sub25, Sub31, Sub35
	common /varXs/ Sub225, Sub36, Sub10, Sub83, Sub32, Sub54
	common /varXs/ Sub43, Sub39, Sub95, Sub84, pave1, pave2
	common /varXs/ pave3, pave14, pave15, pave18

	ComplexType Sub216, Sub218, Sub226(2), Sub229(2), Sub227(2)
	ComplexType Sub230(2), Sub214(2), Sub215(2), Sub217(2,2)
	ComplexType Sub219(2,2), Sub242(2), Sub243(2), Sub187
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Nbb)
	ComplexType pave7(Nbb), pave8(Nbb,2), pave9(Ncc,2)
	ComplexType pave10(Nbb,2), pave11(Ncc,2), pave12(Ndd,2)
	ComplexType pave13(Ndd,2), pave16(Ncc,2), pave17(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub216, Sub218, Sub226, Sub229, Sub227, Sub230
	common /varXa/ Sub214, Sub215, Sub217, Sub219, Sub242
	common /varXa/ Sub243, Sub187, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave16, pave17, S, T, U

	HelType F1, F5, F7, F9, F6, F3, F11, F2, F10, F12, F4, F8
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F19, F20, F25, F22, F14
	HelType F15, F40, F36, F32, F37, F26, F41, F38, F35, F39
	HelType F28, F42, F30, F33, F31, F17, F34, F18, F29, Sub150
	HelType Sub156, Sub160, Sub146, Sub131, Sub208, Sub189
	HelType Sub196, Sub195, Sub197, Sub198, Sub190, Sub188
	HelType Sub191, Sub183, Sub184, Sub182, Sub185, Sub166
	HelType Sub169, Sub168, Sub165, Sub151, Sub161
	HelType Sub239(HelDim(2)), Sub136(HelDim(2))
	HelType Sub139(HelDim(2)), Sub137(HelDim(2))
	HelType Sub140(HelDim(2)), Sub143(HelDim(2))
	HelType Sub144(HelDim(2)), Sub149(HelDim(2))
	HelType Sub159(HelDim(2)), Sub167(HelDim(2))
	HelType Sub170(HelDim(2)), Sub162(HelDim(2))
	HelType Sub192(HelDim(2)), Sub152(HelDim(2))
	HelType Sub138(HelDim(2)), Sub141(HelDim(2))
	HelType Sub145(HelDim(2)), Sub154(HelDim(2))
	HelType Sub164(HelDim(2)), Sub171(HelDim(2))
	HelType Sub194(HelDim(2)), Sub155(HelDim(2))
	HelType Sub142(HelDim(2)), Sub176(HelDim(2))
	HelType Sub181(HelDim(2)), Sub186(HelDim(2))
	HelType Sub199(HelDim(2)), Sub228(HelDim(2))
	HelType Sub231(HelDim(2)), Sub244(HelDim(2))
	HelType Sub101(HelDim(2)), Sub67(HelDim(2))
	HelType Sub99(HelDim(2)), Sub102(HelDim(2))
	HelType Sub120(HelDim(2),2), Sub134(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub126(HelDim(2),2)
	HelType Sub128(HelDim(2),2), Sub127(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub235(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub236(HelDim(2),2), Sub221(HelDim(2),2)
	HelType Sub224(HelDim(2),2), Sub210(HelDim(2),2)
	HelType Sub207(HelDim(2),2), Sub209(HelDim(2),2)
	HelType Sub205(HelDim(2),2), Sub204(HelDim(2),2)
	HelType Sub211(HelDim(2),2), Sub202(HelDim(2),2)
	HelType Sub206(HelDim(2),2), Sub108(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub124(HelDim(2),2)
	HelType Sub118(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub119(HelDim(2),2), Sub114(HelDim(2),2)
	HelType Sub111(HelDim(2),2), Sub133(HelDim(2),2)
	HelType Sub201(HelDim(2),2), Sub203(HelDim(2),2)
	HelType Sub200(HelDim(2),2), Sub105(HelDim(2),2)
	HelType Sub117(HelDim(2),2), Sub123(HelDim(2),2)
	HelType Sub116(HelDim(2),2), Sub122(HelDim(2),2), Sub132
	HelType Sub135, Sub148, Sub173, Sub175, Sub158, Sub178
	HelType Sub177, Sub180, Sub179, Sub174, Sub172, Sub147
	HelType Sub157, Sub153(HelDim(2)), Sub163(HelDim(2))
	HelType Sub193(HelDim(2)), Sub103(HelDim(2))
	HelType Sub100(HelDim(2)), Sub220(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub237(HelDim(2),2), Sub212(HelDim(2),2)
	HelType Sub213(HelDim(2),2), Sub112(HelDim(2),2)
	HelType Sub115(HelDim(2),2), Sub241(HelDim(2))
	HelType Sub238(HelDim(2),2), Sub240(HelDim(2))
	common /varXh/ F1, F5, F7, F9, F6, F3, F11, F2, F10, F12, F4
	common /varXh/ F8, Sub7, F16, F21, F13, F24, F27, F23, F19
	common /varXh/ F20, F25, F22, F14, F15, F40, F36, F32, F37
	common /varXh/ F26, F41, F38, F35, F39, F28, F42, F30, F33
	common /varXh/ F31, F17, F34, F18, F29, Sub150, Sub156
	common /varXh/ Sub160, Sub146, Sub131, Sub208, Sub189
	common /varXh/ Sub196, Sub195, Sub197, Sub198, Sub190
	common /varXh/ Sub188, Sub191, Sub183, Sub184, Sub182
	common /varXh/ Sub185, Sub166, Sub169, Sub168, Sub165
	common /varXh/ Sub151, Sub161, Sub239, Sub136, Sub139
	common /varXh/ Sub137, Sub140, Sub143, Sub144, Sub149
	common /varXh/ Sub159, Sub167, Sub170, Sub162, Sub192
	common /varXh/ Sub152, Sub138, Sub141, Sub145, Sub154
	common /varXh/ Sub164, Sub171, Sub194, Sub155, Sub142
	common /varXh/ Sub176, Sub181, Sub186, Sub199, Sub228
	common /varXh/ Sub231, Sub244, Sub101, Sub67, Sub99, Sub102
	common /varXh/ Sub120, Sub134, Sub121, Sub126, Sub128
	common /varXh/ Sub127, Sub232, Sub233, Sub235, Sub234
	common /varXh/ Sub236, Sub221, Sub224, Sub210, Sub207
	common /varXh/ Sub209, Sub205, Sub204, Sub211, Sub202
	common /varXh/ Sub206, Sub108, Sub113, Sub124, Sub118
	common /varXh/ Sub125, Sub119, Sub114, Sub111, Sub133
	common /varXh/ Sub201, Sub203, Sub200, Sub105, Sub117
	common /varXh/ Sub123, Sub116, Sub122, Sub132, Sub135
	common /varXh/ Sub148, Sub173, Sub175, Sub158, Sub178
	common /varXh/ Sub177, Sub180, Sub179, Sub174, Sub172
	common /varXh/ Sub147, Sub157, Sub153, Sub163, Sub193
	common /varXh/ Sub103, Sub100, Sub220, Sub222, Sub223
	common /varXh/ Sub237, Sub212, Sub213, Sub112, Sub115
	common /varXh/ Sub241, Sub238, Sub240

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n4n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
