#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Jul-2015 9:34
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub13, Sub14, Sub3(2), Sub9(2)
	ComplexType Sub7(2), Sub2(2), Sub5(2), Sub4(2), Sub10(2)
	ComplexType Sub12(2), Sub11(2), Sub6(2)
	ComplexType Sub45, Sub181, Sub182, Sub53, Sub80, Sub44, Sub68
	ComplexType Sub54, Sub81, Sub94, Sub101, Sub95, Sub49, Sub52
	ComplexType Sub74, Sub79, Sub76, Sub64, Sub67, Sub118
	ComplexType Sub121, Sub70, Sub122, Sub123, Sub71, Sub120
	ComplexType Sub61, Sub62, Sub96, Sub97, Sub99, Sub104
	ComplexType Sub131, Sub105, Sub106, Sub132, Sub103, Sub134
	ComplexType Sub135, Sub84, Sub85, Sub86, Sub87, Sub136(2)
	ComplexType Sub63(2), Sub115(2), Sub140(2), Sub109(2)
	ComplexType Sub139(2), Sub91(2), Sub110(2), Sub73(2)
	ComplexType Sub78(2), Sub138(2), Sub72(2), Sub75(2)
	ComplexType Sub77(2), Sub114(2), Sub82(2), Sub90(2)
	ComplexType Sub51(2), Sub48(2), Sub55(2), Sub107(2)
	ComplexType Sub124(2), Sub50(2), Sub127(2), Sub58(2)
	ComplexType Sub66(2), Sub125(2), Sub119(2), Sub137(2)
	ComplexType Sub108(2), Sub100(2), Sub129(2), Sub92(2)
	ComplexType Sub128(2), Sub83(2), Sub60(2), Sub116(2)
	ComplexType Sub59(2), Sub112(2), Sub155(2), Sub30(2)
	ComplexType Sub146(2), Sub23(2), Sub158(2), Sub157(2)
	ComplexType Sub31(2), Sub152(2), Sub151(2), Sub24(2)
	ComplexType Sub16(2,2), Sub32(2,2), Sub142(2,2), Sub147(2,2)
	ComplexType Sub148(2,2), Sub156(2,2), Sub159(2,2)
	ComplexType Sub35(2,2), Sub36(2,2), Sub42(2,2,2), Sub46
	ComplexType Sub276, Sub47, Sub17(2,2), Sub88, Sub113, Sub43
	ComplexType Sub117, Sub98, Sub65, Sub133, Sub69, Sub102
	ComplexType Sub126, Sub56, Sub89, Sub57, pave1(2)
	ComplexType pave2(Nbb), pave3(Ncc), pave14(Ncc,2)
	ComplexType pave17(Ncc,2,2), pave22, pave23(Ncc,2)
	common /varXs/ Sub8, Sub1, Sub13, Sub14, Sub3, Sub9, Sub7
	common /varXs/ Sub2, Sub5, Sub4, Sub10, Sub12, Sub11, Sub6
	common /varXs/ Sub45, Sub181, Sub182, Sub53, Sub80, Sub44
	common /varXs/ Sub68, Sub54, Sub81, Sub94, Sub101, Sub95
	common /varXs/ Sub49, Sub52, Sub74, Sub79, Sub76, Sub64
	common /varXs/ Sub67, Sub118, Sub121, Sub70, Sub122, Sub123
	common /varXs/ Sub71, Sub120, Sub61, Sub62, Sub96, Sub97
	common /varXs/ Sub99, Sub104, Sub131, Sub105, Sub106, Sub132
	common /varXs/ Sub103, Sub134, Sub135, Sub84, Sub85, Sub86
	common /varXs/ Sub87, Sub136, Sub63, Sub115, Sub140, Sub109
	common /varXs/ Sub139, Sub91, Sub110, Sub73, Sub78, Sub138
	common /varXs/ Sub72, Sub75, Sub77, Sub114, Sub82, Sub90
	common /varXs/ Sub51, Sub48, Sub55, Sub107, Sub124, Sub50
	common /varXs/ Sub127, Sub58, Sub66, Sub125, Sub119, Sub137
	common /varXs/ Sub108, Sub100, Sub129, Sub92, Sub128, Sub83
	common /varXs/ Sub60, Sub116, Sub59, Sub112, Sub155, Sub30
	common /varXs/ Sub146, Sub23, Sub158, Sub157, Sub31, Sub152
	common /varXs/ Sub151, Sub24, Sub16, Sub32, Sub142, Sub147
	common /varXs/ Sub148, Sub156, Sub159, Sub35, Sub36, Sub42
	common /varXs/ Sub46, Sub276, Sub47, Sub17, Sub88, Sub113
	common /varXs/ Sub43, Sub117, Sub98, Sub65, Sub133, Sub69
	common /varXs/ Sub102, Sub126, Sub56, Sub89, Sub57, pave1
	common /varXs/ pave2, pave3, pave14, pave17, pave22, pave23

	ComplexType Sub260, Sub262, Sub278(2), Sub282(2), Sub294(2)
	ComplexType Sub297(2), Sub298(2), Sub277(2), Sub281(2)
	ComplexType Sub258(2), Sub259(2), Sub295(2), Sub33(2,2)
	ComplexType Sub34(2,2), Sub261(2,2), Sub263(2,2), Sub220
	ComplexType Sub208, Sub279(2), Sub283(2), pave4(Ndd,2,2)
	ComplexType pave5(Ndd,2,2), pave6(Nbb), pave7(Nbb)
	ComplexType pave8(Ncc,2), pave9(Ncc,2), pave10(Ncc,2)
	ComplexType pave11(Ncc,2), pave12(Ndd,2), pave13(Ndd,2)
	ComplexType pave15(Nbb,2), pave16(Nbb,2), pave18(Ncc,2)
	ComplexType pave19(Ncc,2), pave20(Ncc,2), pave21(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub260, Sub262, Sub278, Sub282, Sub294, Sub297
	common /varXa/ Sub298, Sub277, Sub281, Sub258, Sub259
	common /varXa/ Sub295, Sub33, Sub34, Sub261, Sub263, Sub220
	common /varXa/ Sub208, Sub279, Sub283, pave4, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave10, pave11, pave12
	common /varXa/ pave13, pave15, pave16, pave18, pave19
	common /varXa/ pave20, pave21, S, T, U

	HelType F1, F7, F5, F9, F8, F3, F12, F2, F11, F10, F4, F6
	HelType Sub15
	HelType F16, F22, F13, F25, F27, F19, F21, F20, F26, F23, F14
	HelType F15, F33, F31, F41, F39, F24, F34, F32, F42, F40
	HelType F30, F35, F28, F38, F29, F17, F36, F18, F37, Sub183
	HelType Sub233, Sub229, Sub200, Sub241, Sub245, Sub231
	HelType Sub232, Sub224, Sub222, Sub236, Sub235, Sub238
	HelType Sub237, Sub215, Sub214, Sub217, Sub211, Sub209
	HelType Sub230, Sub228, Sub244, Sub240, Sub201, Sub221
	HelType Sub225, Sub141(HelDim(2)), Sub292(HelDim(2))
	HelType Sub190(HelDim(2)), Sub189(HelDim(2))
	HelType Sub203(HelDim(2)), Sub210(HelDim(2))
	HelType Sub206(HelDim(2)), Sub212(HelDim(2))
	HelType Sub191(HelDim(2)), Sub213(HelDim(2))
	HelType Sub199(HelDim(2)), Sub207(HelDim(2))
	HelType Sub239(HelDim(2)), Sub246(HelDim(2))
	HelType Sub280(HelDim(2)), Sub188(HelDim(2))
	HelType Sub219(HelDim(2)), Sub227(HelDim(2))
	HelType Sub187(HelDim(2)), Sub186(HelDim(2))
	HelType Sub218(HelDim(2)), Sub226(HelDim(2))
	HelType Sub223(HelDim(2)), Sub216(HelDim(2))
	HelType Sub196(HelDim(2)), Sub192(HelDim(2))
	HelType Sub130(HelDim(2)), Sub284(HelDim(2))
	HelType Sub198(HelDim(2)), Sub234(HelDim(2))
	HelType Sub93(HelDim(2)), Sub111(HelDim(2))
	HelType Sub264(HelDim(2),2), Sub145(HelDim(2),2)
	HelType Sub149(HelDim(2),2), Sub154(HelDim(2),2)
	HelType Sub160(HelDim(2),2), Sub163(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub165(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub168(HelDim(2),2)
	HelType Sub267(HelDim(2),2), Sub269(HelDim(2),2)
	HelType Sub177(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub175(HelDim(2),2), Sub176(HelDim(2),2)
	HelType Sub272(HelDim(2),2), Sub271(HelDim(2),2)
	HelType Sub285(HelDim(2),2), Sub286(HelDim(2),2)
	HelType Sub288(HelDim(2),2), Sub287(HelDim(2),2)
	HelType Sub289(HelDim(2),2), Sub265(HelDim(2),2)
	HelType Sub266(HelDim(2),2), Sub275(HelDim(2),2)
	HelType Sub268(HelDim(2),2), Sub253(HelDim(2),2)
	HelType Sub255(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub270(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub254(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub273(HelDim(2),2), Sub162(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub150(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub164(HelDim(2),2)
	HelType Sub180(HelDim(2),2), Sub144(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub143(HelDim(2),2)
	HelType Sub166(HelDim(2),2), Sub161(HelDim(2),2)
	HelType Sub153(HelDim(2),2), Sub167(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub185, Sub179, Sub184, Sub178
	HelType Sub202, Sub205, Sub243, Sub242, Sub204, Sub194
	HelType Sub197(HelDim(2)), Sub290(HelDim(2),2)
	HelType Sub274(HelDim(2),2), Sub256(HelDim(2),2)
	HelType Sub257(HelDim(2),2), Sub195, Sub193
	HelType Sub291(HelDim(2),2), Sub296(HelDim(2))
	HelType Sub293(HelDim(2))
	common /varXh/ F1, F7, F5, F9, F8, F3, F12, F2, F11, F10, F4
	common /varXh/ F6, Sub15, F16, F22, F13, F25, F27, F19, F21
	common /varXh/ F20, F26, F23, F14, F15, F33, F31, F41, F39
	common /varXh/ F24, F34, F32, F42, F40, F30, F35, F28, F38
	common /varXh/ F29, F17, F36, F18, F37, Sub183, Sub233
	common /varXh/ Sub229, Sub200, Sub241, Sub245, Sub231
	common /varXh/ Sub232, Sub224, Sub222, Sub236, Sub235
	common /varXh/ Sub238, Sub237, Sub215, Sub214, Sub217
	common /varXh/ Sub211, Sub209, Sub230, Sub228, Sub244
	common /varXh/ Sub240, Sub201, Sub221, Sub225, Sub141
	common /varXh/ Sub292, Sub190, Sub189, Sub203, Sub210
	common /varXh/ Sub206, Sub212, Sub191, Sub213, Sub199
	common /varXh/ Sub207, Sub239, Sub246, Sub280, Sub188
	common /varXh/ Sub219, Sub227, Sub187, Sub186, Sub218
	common /varXh/ Sub226, Sub223, Sub216, Sub196, Sub192
	common /varXh/ Sub130, Sub284, Sub198, Sub234, Sub93, Sub111
	common /varXh/ Sub264, Sub145, Sub149, Sub154, Sub160
	common /varXh/ Sub163, Sub170, Sub165, Sub169, Sub168
	common /varXh/ Sub267, Sub269, Sub177, Sub172, Sub175
	common /varXh/ Sub176, Sub272, Sub271, Sub285, Sub286
	common /varXh/ Sub288, Sub287, Sub289, Sub265, Sub266
	common /varXh/ Sub275, Sub268, Sub253, Sub255, Sub251
	common /varXh/ Sub247, Sub270, Sub252, Sub254, Sub250
	common /varXh/ Sub248, Sub273, Sub162, Sub173, Sub150
	common /varXh/ Sub174, Sub164, Sub180, Sub144, Sub249
	common /varXh/ Sub143, Sub166, Sub161, Sub153, Sub167
	common /varXh/ Sub171, Sub185, Sub179, Sub184, Sub178
	common /varXh/ Sub202, Sub205, Sub243, Sub242, Sub204
	common /varXh/ Sub194, Sub197, Sub290, Sub274, Sub256
	common /varXh/ Sub257, Sub195, Sub193, Sub291, Sub296, Sub293

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n1n4_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
