#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 8-Jun-2015 15:45
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2, Sub8, Sub1(2), Sub3(2), Sub6(2), Sub5(2)
	ComplexType Sub4(2)
	ComplexType Sub34, Sub129, Sub130, Sub75, Sub92, Sub33, Sub44
	ComplexType Sub76, Sub93, Sub49, Sub59, Sub50, Sub89, Sub91
	ComplexType Sub69, Sub74, Sub71, Sub40, Sub43, Sub51, Sub55
	ComplexType Sub61, Sub46, Sub62, Sub47, Sub63, Sub60, Sub37
	ComplexType Sub38, Sub52, Sub53, Sub79, Sub80, Sub81, Sub82
	ComplexType Sub39(2), Sub66(2), Sub86(2), Sub88(2), Sub68(2)
	ComplexType Sub73(2), Sub48(2), Sub70(2), Sub72(2), Sub77(2)
	ComplexType Sub85(2), Sub56(2), Sub57(2), Sub94(2), Sub64(2)
	ComplexType Sub90(2), Sub96(2), Sub42(2), Sub65(2), Sub58(2)
	ComplexType Sub87(2), Sub98(2), Sub78(2), Sub97(2)
	ComplexType Sub106(2), Sub16(2), Sub110(2), Sub109(2)
	ComplexType Sub17(2), Sub9(2,2), Sub23(2,2), Sub104(2,2)
	ComplexType Sub107(2,2), Sub24(2,2), Sub25(2,2)
	ComplexType Sub31(2,2,2), Sub35, Sub225, Sub36, Sub10(2,2)
	ComplexType Sub83, Sub32, Sub54, Sub41, Sub45, Sub95, Sub84
	ComplexType pave1(2), pave2(Nbb), pave3(Ncc)
	ComplexType pave14(Ncc,2,2), pave15, pave18(Ncc,2)
	common /varXs/ Sub2, Sub8, Sub1, Sub3, Sub6, Sub5, Sub4
	common /varXs/ Sub34, Sub129, Sub130, Sub75, Sub92, Sub33
	common /varXs/ Sub44, Sub76, Sub93, Sub49, Sub59, Sub50
	common /varXs/ Sub89, Sub91, Sub69, Sub74, Sub71, Sub40
	common /varXs/ Sub43, Sub51, Sub55, Sub61, Sub46, Sub62
	common /varXs/ Sub47, Sub63, Sub60, Sub37, Sub38, Sub52
	common /varXs/ Sub53, Sub79, Sub80, Sub81, Sub82, Sub39
	common /varXs/ Sub66, Sub86, Sub88, Sub68, Sub73, Sub48
	common /varXs/ Sub70, Sub72, Sub77, Sub85, Sub56, Sub57
	common /varXs/ Sub94, Sub64, Sub90, Sub96, Sub42, Sub65
	common /varXs/ Sub58, Sub87, Sub98, Sub78, Sub97, Sub106
	common /varXs/ Sub16, Sub110, Sub109, Sub17, Sub9, Sub23
	common /varXs/ Sub104, Sub107, Sub24, Sub25, Sub31, Sub35
	common /varXs/ Sub225, Sub36, Sub10, Sub83, Sub32, Sub54
	common /varXs/ Sub41, Sub45, Sub95, Sub84, pave1, pave2
	common /varXs/ pave3, pave14, pave15, pave18

	ComplexType Sub216, Sub218, Sub226(2), Sub229(2), Sub227(2)
	ComplexType Sub230(2), Sub214(2), Sub215(2), Sub217(2,2)
	ComplexType Sub219(2,2), Sub240(2), Sub243(2), Sub179
	ComplexType pave4(Ndd,2,2), pave5(Ndd,2,2), pave6(Nbb)
	ComplexType pave7(Nbb), pave8(Nbb,2), pave9(Ncc,2)
	ComplexType pave10(Nbb,2), pave11(Ncc,2), pave12(Ndd,2)
	ComplexType pave13(Ndd,2), pave16(Ncc,2), pave17(Ncc,2)
	RealType S, T, U
	common /varXa/ Sub216, Sub218, Sub226, Sub229, Sub227, Sub230
	common /varXa/ Sub214, Sub215, Sub217, Sub219, Sub240
	common /varXa/ Sub243, Sub179, pave4, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave16, pave17, S, T, U

	HelType F1, F5, F7, F9, F6, F3, F12, F2, F10, F11, F4, F8
	HelType Sub7
	HelType F16, F21, F13, F24, F27, F23, F19, F20, F25, F22, F15
	HelType F14, F39, F40, F37, F35, F26, F41, F42, F38, F36
	HelType F28, F33, F30, F32, F31, F17, F34, F18, F29, Sub169
	HelType Sub156, Sub160, Sub165, Sub131, Sub205, Sub181
	HelType Sub193, Sub192, Sub194, Sub195, Sub182, Sub180
	HelType Sub183, Sub152, Sub153, Sub151, Sub154, Sub145
	HelType Sub148, Sub147, Sub144, Sub161, Sub170
	HelType Sub239(HelDim(2)), Sub136(HelDim(2))
	HelType Sub140(HelDim(2)), Sub137(HelDim(2))
	HelType Sub141(HelDim(2)), Sub211(HelDim(2))
	HelType Sub212(HelDim(2)), Sub146(HelDim(2))
	HelType Sub149(HelDim(2)), Sub159(HelDim(2))
	HelType Sub168(HelDim(2)), Sub162(HelDim(2))
	HelType Sub184(HelDim(2)), Sub171(HelDim(2))
	HelType Sub138(HelDim(2)), Sub142(HelDim(2))
	HelType Sub150(HelDim(2)), Sub164(HelDim(2))
	HelType Sub173(HelDim(2)), Sub186(HelDim(2))
	HelType Sub213(HelDim(2)), Sub143(HelDim(2))
	HelType Sub139(HelDim(2)), Sub155(HelDim(2))
	HelType Sub178(HelDim(2)), Sub191(HelDim(2))
	HelType Sub196(HelDim(2)), Sub228(HelDim(2))
	HelType Sub241(HelDim(2)), Sub231(HelDim(2))
	HelType Sub244(HelDim(2)), Sub101(HelDim(2))
	HelType Sub67(HelDim(2)), Sub99(HelDim(2))
	HelType Sub102(HelDim(2)), Sub120(HelDim(2),2)
	HelType Sub122(HelDim(2),2), Sub121(HelDim(2),2)
	HelType Sub127(HelDim(2),2), Sub132(HelDim(2),2)
	HelType Sub128(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub234(HelDim(2),2), Sub235(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub236(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub209(HelDim(2),2), Sub204(HelDim(2),2)
	HelType Sub206(HelDim(2),2), Sub207(HelDim(2),2)
	HelType Sub202(HelDim(2),2), Sub203(HelDim(2),2)
	HelType Sub199(HelDim(2),2), Sub200(HelDim(2),2)
	HelType Sub113(HelDim(2),2), Sub108(HelDim(2),2)
	HelType Sub125(HelDim(2),2), Sub118(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub119(HelDim(2),2)
	HelType Sub111(HelDim(2),2), Sub114(HelDim(2),2)
	HelType Sub134(HelDim(2),2), Sub198(HelDim(2),2)
	HelType Sub201(HelDim(2),2), Sub197(HelDim(2),2)
	HelType Sub105(HelDim(2),2), Sub117(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub116(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub135, Sub133, Sub167, Sub175
	HelType Sub177, Sub158, Sub188, Sub187, Sub190, Sub189
	HelType Sub176, Sub174, Sub157, Sub166, Sub163(HelDim(2))
	HelType Sub172(HelDim(2)), Sub185(HelDim(2))
	HelType Sub103(HelDim(2)), Sub100(HelDim(2))
	HelType Sub223(HelDim(2),2), Sub220(HelDim(2),2)
	HelType Sub221(HelDim(2),2), Sub237(HelDim(2),2)
	HelType Sub208(HelDim(2),2), Sub210(HelDim(2),2)
	HelType Sub115(HelDim(2),2), Sub112(HelDim(2),2)
	HelType Sub245(HelDim(2)), Sub238(HelDim(2),2)
	HelType Sub242(HelDim(2))
	common /varXh/ F1, F5, F7, F9, F6, F3, F12, F2, F10, F11, F4
	common /varXh/ F8, Sub7, F16, F21, F13, F24, F27, F23, F19
	common /varXh/ F20, F25, F22, F15, F14, F39, F40, F37, F35
	common /varXh/ F26, F41, F42, F38, F36, F28, F33, F30, F32
	common /varXh/ F31, F17, F34, F18, F29, Sub169, Sub156
	common /varXh/ Sub160, Sub165, Sub131, Sub205, Sub181
	common /varXh/ Sub193, Sub192, Sub194, Sub195, Sub182
	common /varXh/ Sub180, Sub183, Sub152, Sub153, Sub151
	common /varXh/ Sub154, Sub145, Sub148, Sub147, Sub144
	common /varXh/ Sub161, Sub170, Sub239, Sub136, Sub140
	common /varXh/ Sub137, Sub141, Sub211, Sub212, Sub146
	common /varXh/ Sub149, Sub159, Sub168, Sub162, Sub184
	common /varXh/ Sub171, Sub138, Sub142, Sub150, Sub164
	common /varXh/ Sub173, Sub186, Sub213, Sub143, Sub139
	common /varXh/ Sub155, Sub178, Sub191, Sub196, Sub228
	common /varXh/ Sub241, Sub231, Sub244, Sub101, Sub67, Sub99
	common /varXh/ Sub102, Sub120, Sub122, Sub121, Sub127
	common /varXh/ Sub132, Sub128, Sub232, Sub234, Sub235
	common /varXh/ Sub233, Sub236, Sub222, Sub224, Sub209
	common /varXh/ Sub204, Sub206, Sub207, Sub202, Sub203
	common /varXh/ Sub199, Sub200, Sub113, Sub108, Sub125
	common /varXh/ Sub118, Sub126, Sub119, Sub111, Sub114
	common /varXh/ Sub134, Sub198, Sub201, Sub197, Sub105
	common /varXh/ Sub117, Sub124, Sub116, Sub123, Sub135
	common /varXh/ Sub133, Sub167, Sub175, Sub177, Sub158
	common /varXh/ Sub188, Sub187, Sub190, Sub189, Sub176
	common /varXh/ Sub174, Sub157, Sub166, Sub163, Sub172
	common /varXh/ Sub185, Sub103, Sub100, Sub223, Sub220
	common /varXh/ Sub221, Sub237, Sub208, Sub210, Sub115
	common /varXh/ Sub112, Sub245, Sub238, Sub242

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_n2n2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
