#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 11:55
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub1, Sub9, Sub2, Sub7(2), Sub3(2), Sub8(2)
	ComplexType Sub5(2), Sub10(2), Sub6(2)
	ComplexType Sub105, Sub76, Sub127, Sub133, Sub82, Sub176
	ComplexType Sub134, Sub83, Sub94, Sub106, Sub128, Sub77
	ComplexType Sub75, Sub141, Sub150, Sub72, Sub158, Sub81
	ComplexType Sub104, Sub99, Sub132, Sub101, Sub87, Sub88
	ComplexType Sub129, Sub79, Sub73, Sub78, Sub137, Sub85
	ComplexType Sub142, Sub143, Sub63, Sub146, Sub96, Sub91
	ComplexType Sub92, Sub153, Sub154, Sub155, Sub152, Sub144
	ComplexType Sub109, Sub110, Sub111, Sub93(2), Sub115(2)
	ComplexType Sub71(2), Sub126(2), Sub98(2), Sub131(2)
	ComplexType Sub103(2), Sub136(2), Sub130(2), Sub102(2)
	ComplexType Sub97(2), Sub100(2), Sub135(2), Sub138(2)
	ComplexType Sub107(2), Sub114(2), Sub147(2), Sub69(2)
	ComplexType Sub148(2), Sub70(2), Sub160(2), Sub84(2)
	ComplexType Sub74(2), Sub156(2), Sub159(2), Sub163(2)
	ComplexType Sub80(2), Sub139(2), Sub140(2), Sub86(2)
	ComplexType Sub157(2), Sub90(2), Sub213(2), Sub149(2)
	ComplexType Sub116(2), Sub165(2), Sub108(2), Sub164(2)
	ComplexType Sub15(2), Sub67(2), Sub64(2), Sub120(2)
	ComplexType Sub28(2), Sub122(2), Sub65(2), Sub121(2)
	ComplexType Sub29(2), Sub14(2,2), Sub12(2,2), Sub38(2,2)
	ComplexType Sub37(2,2), Sub47(2,2), Sub39(2,2), Sub48(2,2)
	ComplexType Sub40(2,2), Sub46(2,2,2), Sub54(2,2,2), Sub233
	ComplexType Sub13(2,2), Sub11(2,2), Sub55, Sub112, Sub145
	ComplexType Sub89, Sub95, Sub151, Sub161, Sub113, Sub162
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave10(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub4, Sub1, Sub9, Sub2, Sub7, Sub3, Sub8, Sub5
	common /varXs/ Sub10, Sub6, Sub105, Sub76, Sub127, Sub133
	common /varXs/ Sub82, Sub176, Sub134, Sub83, Sub94, Sub106
	common /varXs/ Sub128, Sub77, Sub75, Sub141, Sub150, Sub72
	common /varXs/ Sub158, Sub81, Sub104, Sub99, Sub132, Sub101
	common /varXs/ Sub87, Sub88, Sub129, Sub79, Sub73, Sub78
	common /varXs/ Sub137, Sub85, Sub142, Sub143, Sub63, Sub146
	common /varXs/ Sub96, Sub91, Sub92, Sub153, Sub154, Sub155
	common /varXs/ Sub152, Sub144, Sub109, Sub110, Sub111, Sub93
	common /varXs/ Sub115, Sub71, Sub126, Sub98, Sub131, Sub103
	common /varXs/ Sub136, Sub130, Sub102, Sub97, Sub100, Sub135
	common /varXs/ Sub138, Sub107, Sub114, Sub147, Sub69, Sub148
	common /varXs/ Sub70, Sub160, Sub84, Sub74, Sub156, Sub159
	common /varXs/ Sub163, Sub80, Sub139, Sub140, Sub86, Sub157
	common /varXs/ Sub90, Sub213, Sub149, Sub116, Sub165, Sub108
	common /varXs/ Sub164, Sub15, Sub67, Sub64, Sub120, Sub28
	common /varXs/ Sub122, Sub65, Sub121, Sub29, Sub14, Sub12
	common /varXs/ Sub38, Sub37, Sub47, Sub39, Sub48, Sub40
	common /varXs/ Sub46, Sub54, Sub233, Sub13, Sub11, Sub55
	common /varXs/ Sub112, Sub145, Sub89, Sub95, Sub151, Sub161
	common /varXs/ Sub113, Sub162, pave1, pave2, pave3, pave4
	common /varXs/ pave10, pave18, pave23

	ComplexType Sub218, Sub57, Sub59, Sub56, Sub58, Sub234(2)
	ComplexType Sub252(2), Sub259(2), Sub253(2), Sub216(2)
	ComplexType Sub217(2), Sub260(2), Sub227(2), Sub229(2)
	ComplexType Sub236(2), Sub220(2,2), Sub219(2,2), Sub194
	ComplexType Sub183, Sub235(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub218, Sub57, Sub59, Sub56, Sub58, Sub234
	common /varXa/ Sub252, Sub259, Sub253, Sub216, Sub217
	common /varXa/ Sub260, Sub227, Sub229, Sub236, Sub220
	common /varXa/ Sub219, Sub194, Sub183, Sub235, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave21, pave22, S, T, U

	HelType F1, F5, F3, F2, F7, F4, F8, F6
	HelType F20, F16, F12, F9, F15, F17, F22, F23, F21, F25, F18
	HelType F19, F10, F11, F33, F24, F35, F28, F27, F29, F32
	HelType F31, F34, F13, F26, F30, F14, Sub191, Sub187, Sub193
	HelType Sub202, Sub211, Sub212, Sub203, Sub208, Sub207
	HelType Sub195, Sub204, Sub192, Sub184, Sub185, Sub201
	HelType Sub189, Sub206, Sub205, Sub238(HelDim(2))
	HelType Sub166(HelDim(2)), Sub258(HelDim(2))
	HelType Sub240(HelDim(2)), Sub257(HelDim(2))
	HelType Sub182(HelDim(2)), Sub190(HelDim(2))
	HelType Sub196(HelDim(2)), Sub254(HelDim(2))
	HelType Sub186(HelDim(2)), Sub167(HelDim(2))
	HelType Sub237(HelDim(2)), Sub197(HelDim(2))
	HelType Sub200(HelDim(2)), Sub210(HelDim(2))
	HelType Sub242(HelDim(2)), Sub261(HelDim(2))
	HelType Sub118(HelDim(2)), Sub119(HelDim(2))
	HelType Sub117(HelDim(2)), Sub225(HelDim(2))
	HelType Sub172(HelDim(2)), Sub175(HelDim(2))
	HelType Sub125(HelDim(2)), Sub230(HelDim(2))
	HelType Sub221(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub62(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub66(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub179(HelDim(2),2)
	HelType Sub60(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub123(HelDim(2),2)
	HelType Sub68(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub188, Sub181, Sub178, Sub180
	HelType Sub177, Sub209, Sub199, Sub239(HelDim(2))
	HelType Sub241(HelDim(2)), Sub256(HelDim(2))
	HelType Sub255(HelDim(2)), Sub263(HelDim(2))
	HelType Sub244(HelDim(2),2), Sub226(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub215(HelDim(2),2), Sub198
	HelType Sub262(HelDim(2)), Sub251(HelDim(2),2)
	HelType Sub243(HelDim(2),2)
	common /varXh/ F1, F5, F3, F2, F7, F4, F8, F6, F20, F16, F12
	common /varXh/ F9, F15, F17, F22, F23, F21, F25, F18, F19
	common /varXh/ F10, F11, F33, F24, F35, F28, F27, F29, F32
	common /varXh/ F31, F34, F13, F26, F30, F14, Sub191, Sub187
	common /varXh/ Sub193, Sub202, Sub211, Sub212, Sub203
	common /varXh/ Sub208, Sub207, Sub195, Sub204, Sub192
	common /varXh/ Sub184, Sub185, Sub201, Sub189, Sub206
	common /varXh/ Sub205, Sub238, Sub166, Sub258, Sub240
	common /varXh/ Sub257, Sub182, Sub190, Sub196, Sub254
	common /varXh/ Sub186, Sub167, Sub237, Sub197, Sub200
	common /varXh/ Sub210, Sub242, Sub261, Sub118, Sub119
	common /varXh/ Sub117, Sub225, Sub172, Sub175, Sub125
	common /varXh/ Sub230, Sub221, Sub247, Sub249, Sub224
	common /varXh/ Sub222, Sub232, Sub245, Sub248, Sub250
	common /varXh/ Sub246, Sub62, Sub223, Sub169, Sub228, Sub124
	common /varXh/ Sub66, Sub168, Sub170, Sub173, Sub179, Sub60
	common /varXh/ Sub214, Sub61, Sub123, Sub68, Sub171, Sub174
	common /varXh/ Sub188, Sub181, Sub178, Sub180, Sub177
	common /varXh/ Sub209, Sub199, Sub239, Sub241, Sub256
	common /varXh/ Sub255, Sub263, Sub244, Sub226, Sub231
	common /varXh/ Sub215, Sub198, Sub262, Sub251, Sub243

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /dubar_n3x1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
