#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 13:22
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub5, Sub2, Sub3(2), Sub7(2), Sub4(2)
	ComplexType Sub9(2), Sub6(2), Sub10(2)
	ComplexType Sub106, Sub77, Sub122, Sub128, Sub83, Sub177
	ComplexType Sub129, Sub84, Sub92, Sub107, Sub123, Sub78
	ComplexType Sub76, Sub136, Sub145, Sub73, Sub153, Sub82
	ComplexType Sub105, Sub100, Sub127, Sub102, Sub90, Sub88
	ComplexType Sub124, Sub80, Sub74, Sub79, Sub132, Sub86
	ComplexType Sub137, Sub138, Sub139, Sub65, Sub141, Sub94
	ComplexType Sub95, Sub96, Sub148, Sub149, Sub150, Sub147
	ComplexType Sub110, Sub111, Sub112, Sub97(2), Sub116(2)
	ComplexType Sub72(2), Sub121(2), Sub99(2), Sub126(2)
	ComplexType Sub104(2), Sub131(2), Sub125(2), Sub101(2)
	ComplexType Sub103(2), Sub98(2), Sub130(2), Sub133(2)
	ComplexType Sub108(2), Sub115(2), Sub142(2), Sub70(2)
	ComplexType Sub143(2), Sub71(2), Sub155(2), Sub85(2)
	ComplexType Sub75(2), Sub151(2), Sub154(2), Sub158(2)
	ComplexType Sub81(2), Sub134(2), Sub135(2), Sub87(2)
	ComplexType Sub152(2), Sub91(2), Sub212(2), Sub144(2)
	ComplexType Sub117(2), Sub160(2), Sub109(2), Sub159(2)
	ComplexType Sub15(2), Sub61(2), Sub66(2), Sub165(2)
	ComplexType Sub31(2), Sub167(2), Sub67(2), Sub166(2)
	ComplexType Sub32(2), Sub14(2,2), Sub11(2,2), Sub38(2,2)
	ComplexType Sub37(2,2), Sub48(2,2), Sub40(2,2), Sub49(2,2)
	ComplexType Sub41(2,2), Sub47(2,2,2), Sub55(2,2,2), Sub235
	ComplexType Sub13(2,2), Sub12(2,2), Sub56, Sub113, Sub140
	ComplexType Sub89, Sub93, Sub146, Sub156, Sub114, Sub157
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave10(Ncc,2), pave18(Ncc,2,2), pave21
	common /varXs/ Sub8, Sub1, Sub5, Sub2, Sub3, Sub7, Sub4, Sub9
	common /varXs/ Sub6, Sub10, Sub106, Sub77, Sub122, Sub128
	common /varXs/ Sub83, Sub177, Sub129, Sub84, Sub92, Sub107
	common /varXs/ Sub123, Sub78, Sub76, Sub136, Sub145, Sub73
	common /varXs/ Sub153, Sub82, Sub105, Sub100, Sub127, Sub102
	common /varXs/ Sub90, Sub88, Sub124, Sub80, Sub74, Sub79
	common /varXs/ Sub132, Sub86, Sub137, Sub138, Sub139, Sub65
	common /varXs/ Sub141, Sub94, Sub95, Sub96, Sub148, Sub149
	common /varXs/ Sub150, Sub147, Sub110, Sub111, Sub112, Sub97
	common /varXs/ Sub116, Sub72, Sub121, Sub99, Sub126, Sub104
	common /varXs/ Sub131, Sub125, Sub101, Sub103, Sub98, Sub130
	common /varXs/ Sub133, Sub108, Sub115, Sub142, Sub70, Sub143
	common /varXs/ Sub71, Sub155, Sub85, Sub75, Sub151, Sub154
	common /varXs/ Sub158, Sub81, Sub134, Sub135, Sub87, Sub152
	common /varXs/ Sub91, Sub212, Sub144, Sub117, Sub160, Sub109
	common /varXs/ Sub159, Sub15, Sub61, Sub66, Sub165, Sub31
	common /varXs/ Sub167, Sub67, Sub166, Sub32, Sub14, Sub11
	common /varXs/ Sub38, Sub37, Sub48, Sub40, Sub49, Sub41
	common /varXs/ Sub47, Sub55, Sub235, Sub13, Sub12, Sub56
	common /varXs/ Sub113, Sub140, Sub89, Sub93, Sub146, Sub156
	common /varXs/ Sub114, Sub157, pave1, pave2, pave3, pave4
	common /varXs/ pave10, pave18, pave21

	ComplexType Sub220, Sub58, Sub60, Sub57, Sub59, Sub241(2)
	ComplexType Sub262(2), Sub254(2), Sub260(2), Sub218(2)
	ComplexType Sub217(2), Sub255(2), Sub229(2), Sub231(2)
	ComplexType Sub39(2,2), Sub219(2,2), Sub243(2), Sub221(2,2)
	ComplexType Sub195, Sub187, Sub242(2), pave5(Nbb)
	ComplexType pave6(Ncc,2), pave7(Ncc,2), pave8(Ncc,2)
	ComplexType pave9(Ncc,2), pave11(Ndd,2), pave12(Ndd,2)
	ComplexType pave13(Nbb,2), pave14(Nbb,2), pave15(Ncc,2)
	ComplexType pave16(Ncc,2), pave17(Ncc,2), pave19(Ndd,2,2)
	ComplexType pave20(Ncc,2), pave22(Nbb), pave23(Ndd,2,2)
	RealType S, T, U
	common /varXa/ Sub220, Sub58, Sub60, Sub57, Sub59, Sub241
	common /varXa/ Sub262, Sub254, Sub260, Sub218, Sub217
	common /varXa/ Sub255, Sub229, Sub231, Sub39, Sub219, Sub243
	common /varXa/ Sub221, Sub195, Sub187, Sub242, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave22, pave23, S, T, U

	HelType F1, F3, F2, F6, F8, F4, F7, F5
	HelType F20, F15, F12, F9, F18, F16, F23, F25, F21, F22, F17
	HelType F19, F10, F11, F34, F24, F35, F29, F28, F30, F32
	HelType F31, F33, F13, F26, F27, F14, Sub192, Sub188, Sub194
	HelType Sub210, Sub211, Sub202, Sub203, Sub208, Sub207
	HelType Sub196, Sub204, Sub193, Sub184, Sub185, Sub201
	HelType Sub190, Sub206, Sub205, Sub236(HelDim(2))
	HelType Sub161(HelDim(2)), Sub259(HelDim(2))
	HelType Sub238(HelDim(2)), Sub265(HelDim(2))
	HelType Sub209(HelDim(2)), Sub200(HelDim(2))
	HelType Sub214(HelDim(2)), Sub240(HelDim(2))
	HelType Sub119(HelDim(2)), Sub120(HelDim(2))
	HelType Sub183(HelDim(2)), Sub186(HelDim(2))
	HelType Sub191(HelDim(2)), Sub197(HelDim(2))
	HelType Sub162(HelDim(2)), Sub261(HelDim(2))
	HelType Sub244(HelDim(2)), Sub118(HelDim(2))
	HelType Sub227(HelDim(2)), Sub173(HelDim(2))
	HelType Sub176(HelDim(2)), Sub171(HelDim(2))
	HelType Sub222(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub223(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub64(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub164(HelDim(2),2), Sub230(HelDim(2),2)
	HelType Sub226(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub172(HelDim(2),2), Sub68(HelDim(2),2)
	HelType Sub163(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub180(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub63(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub69(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub175(HelDim(2),2), Sub189
	HelType Sub182, Sub179, Sub181, Sub178, Sub213, Sub199
	HelType Sub237(HelDim(2)), Sub239(HelDim(2))
	HelType Sub264(HelDim(2)), Sub257(HelDim(2))
	HelType Sub258(HelDim(2)), Sub256(HelDim(2))
	HelType Sub263(HelDim(2)), Sub246(HelDim(2),2)
	HelType Sub216(HelDim(2),2), Sub233(HelDim(2),2), Sub198
	HelType Sub253(HelDim(2),2), Sub245(HelDim(2),2)
	common /varXh/ F1, F3, F2, F6, F8, F4, F7, F5, F20, F15, F12
	common /varXh/ F9, F18, F16, F23, F25, F21, F22, F17, F19
	common /varXh/ F10, F11, F34, F24, F35, F29, F28, F30, F32
	common /varXh/ F31, F33, F13, F26, F27, F14, Sub192, Sub188
	common /varXh/ Sub194, Sub210, Sub211, Sub202, Sub203
	common /varXh/ Sub208, Sub207, Sub196, Sub204, Sub193
	common /varXh/ Sub184, Sub185, Sub201, Sub190, Sub206
	common /varXh/ Sub205, Sub236, Sub161, Sub259, Sub238
	common /varXh/ Sub265, Sub209, Sub200, Sub214, Sub240
	common /varXh/ Sub119, Sub120, Sub183, Sub186, Sub191
	common /varXh/ Sub197, Sub162, Sub261, Sub244, Sub118
	common /varXh/ Sub227, Sub173, Sub176, Sub171, Sub222
	common /varXh/ Sub249, Sub251, Sub225, Sub223, Sub234
	common /varXh/ Sub247, Sub250, Sub252, Sub248, Sub64, Sub224
	common /varXh/ Sub164, Sub230, Sub226, Sub228, Sub172, Sub68
	common /varXh/ Sub163, Sub232, Sub174, Sub169, Sub180, Sub62
	common /varXh/ Sub215, Sub63, Sub168, Sub69, Sub170, Sub175
	common /varXh/ Sub189, Sub182, Sub179, Sub181, Sub178
	common /varXh/ Sub213, Sub199, Sub237, Sub239, Sub264
	common /varXh/ Sub257, Sub258, Sub256, Sub263, Sub246
	common /varXh/ Sub216, Sub233, Sub198, Sub253, Sub245

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /dubar_n4x1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
