#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 19-Jun-2015 12:29
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub5, Sub2, Sub3(2), Sub7(2), Sub4(2)
	ComplexType Sub9(2), Sub6(2), Sub10(2)
	ComplexType Sub105, Sub76, Sub126, Sub132, Sub82, Sub175
	ComplexType Sub133, Sub83, Sub94, Sub106, Sub127, Sub77
	ComplexType Sub75, Sub140, Sub149, Sub72, Sub157, Sub81
	ComplexType Sub104, Sub99, Sub131, Sub101, Sub87, Sub88
	ComplexType Sub128, Sub79, Sub73, Sub78, Sub136, Sub85
	ComplexType Sub64, Sub145, Sub96, Sub91, Sub92, Sub152
	ComplexType Sub153, Sub154, Sub151, Sub141, Sub142, Sub143
	ComplexType Sub109, Sub110, Sub111, Sub93(2), Sub115(2)
	ComplexType Sub71(2), Sub125(2), Sub98(2), Sub130(2)
	ComplexType Sub103(2), Sub135(2), Sub129(2), Sub102(2)
	ComplexType Sub97(2), Sub100(2), Sub134(2), Sub137(2)
	ComplexType Sub107(2), Sub114(2), Sub146(2), Sub69(2)
	ComplexType Sub147(2), Sub70(2), Sub159(2), Sub84(2)
	ComplexType Sub74(2), Sub155(2), Sub158(2), Sub162(2)
	ComplexType Sub80(2), Sub138(2), Sub139(2), Sub86(2)
	ComplexType Sub156(2), Sub90(2), Sub211(2), Sub148(2)
	ComplexType Sub116(2), Sub164(2), Sub108(2), Sub163(2)
	ComplexType Sub15(2), Sub63(2), Sub65(2), Sub120(2)
	ComplexType Sub28(2), Sub122(2), Sub66(2), Sub121(2)
	ComplexType Sub29(2), Sub14(2,2), Sub12(2,2), Sub38(2,2)
	ComplexType Sub32(2,2), Sub47(2,2), Sub39(2,2), Sub48(2,2)
	ComplexType Sub40(2,2), Sub46(2,2,2), Sub54(2,2,2), Sub234
	ComplexType Sub13(2,2), Sub11(2,2), Sub55, Sub112, Sub144
	ComplexType Sub89, Sub95, Sub150, Sub160, Sub113, Sub161
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave10(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub8, Sub1, Sub5, Sub2, Sub3, Sub7, Sub4, Sub9
	common /varXs/ Sub6, Sub10, Sub105, Sub76, Sub126, Sub132
	common /varXs/ Sub82, Sub175, Sub133, Sub83, Sub94, Sub106
	common /varXs/ Sub127, Sub77, Sub75, Sub140, Sub149, Sub72
	common /varXs/ Sub157, Sub81, Sub104, Sub99, Sub131, Sub101
	common /varXs/ Sub87, Sub88, Sub128, Sub79, Sub73, Sub78
	common /varXs/ Sub136, Sub85, Sub64, Sub145, Sub96, Sub91
	common /varXs/ Sub92, Sub152, Sub153, Sub154, Sub151, Sub141
	common /varXs/ Sub142, Sub143, Sub109, Sub110, Sub111, Sub93
	common /varXs/ Sub115, Sub71, Sub125, Sub98, Sub130, Sub103
	common /varXs/ Sub135, Sub129, Sub102, Sub97, Sub100, Sub134
	common /varXs/ Sub137, Sub107, Sub114, Sub146, Sub69, Sub147
	common /varXs/ Sub70, Sub159, Sub84, Sub74, Sub155, Sub158
	common /varXs/ Sub162, Sub80, Sub138, Sub139, Sub86, Sub156
	common /varXs/ Sub90, Sub211, Sub148, Sub116, Sub164, Sub108
	common /varXs/ Sub163, Sub15, Sub63, Sub65, Sub120, Sub28
	common /varXs/ Sub122, Sub66, Sub121, Sub29, Sub14, Sub12
	common /varXs/ Sub38, Sub32, Sub47, Sub39, Sub48, Sub40
	common /varXs/ Sub46, Sub54, Sub234, Sub13, Sub11, Sub55
	common /varXs/ Sub112, Sub144, Sub89, Sub95, Sub150, Sub160
	common /varXs/ Sub113, Sub161, pave1, pave2, pave3, pave4
	common /varXs/ pave10, pave18, pave23

	ComplexType Sub219, Sub57, Sub58, Sub56, Sub59, Sub240(2)
	ComplexType Sub259(2), Sub253(2), Sub260(2), Sub217(2)
	ComplexType Sub216(2), Sub254(2), Sub228(2), Sub230(2)
	ComplexType Sub242(2), Sub218(2,2), Sub220(2,2), Sub186
	ComplexType Sub189, Sub241(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub219, Sub57, Sub58, Sub56, Sub59, Sub240
	common /varXa/ Sub259, Sub253, Sub260, Sub217, Sub216
	common /varXa/ Sub254, Sub228, Sub230, Sub242, Sub218
	common /varXa/ Sub220, Sub186, Sub189, Sub241, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave21, pave22, S, T, U

	HelType F3, F1, F5, F4, F8, F7, F6, F2
	HelType F20, F15, F12, F9, F17, F16, F22, F24, F21, F23, F18
	HelType F19, F11, F10, F31, F25, F32, F29, F26, F30, F34
	HelType F33, F35, F13, F27, F28, F14, Sub183, Sub190, Sub185
	HelType Sub212, Sub213, Sub195, Sub196, Sub187, Sub208
	HelType Sub207, Sub203, Sub184, Sub197, Sub198, Sub194
	HelType Sub192, Sub205, Sub204, Sub235(HelDim(2))
	HelType Sub165(HelDim(2)), Sub258(HelDim(2))
	HelType Sub237(HelDim(2)), Sub263(HelDim(2))
	HelType Sub206(HelDim(2)), Sub202(HelDim(2))
	HelType Sub210(HelDim(2)), Sub239(HelDim(2))
	HelType Sub118(HelDim(2)), Sub119(HelDim(2))
	HelType Sub182(HelDim(2)), Sub188(HelDim(2))
	HelType Sub193(HelDim(2)), Sub199(HelDim(2))
	HelType Sub166(HelDim(2)), Sub243(HelDim(2))
	HelType Sub117(HelDim(2)), Sub226(HelDim(2))
	HelType Sub176(HelDim(2)), Sub174(HelDim(2))
	HelType Sub167(HelDim(2)), Sub221(HelDim(2),2)
	HelType Sub244(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub224(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub223(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub124(HelDim(2),2)
	HelType Sub67(HelDim(2),2), Sub168(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub172(HelDim(2),2), Sub177(HelDim(2),2)
	HelType Sub60(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub123(HelDim(2),2)
	HelType Sub68(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub191, Sub178, Sub180, Sub179
	HelType Sub181, Sub209, Sub201, Sub236(HelDim(2))
	HelType Sub238(HelDim(2)), Sub256(HelDim(2))
	HelType Sub257(HelDim(2)), Sub255(HelDim(2))
	HelType Sub262(HelDim(2)), Sub261(HelDim(2))
	HelType Sub250(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub200, Sub248(HelDim(2),2)
	HelType Sub249(HelDim(2),2)
	common /varXh/ F3, F1, F5, F4, F8, F7, F6, F2, F20, F15, F12
	common /varXh/ F9, F17, F16, F22, F24, F21, F23, F18, F19
	common /varXh/ F11, F10, F31, F25, F32, F29, F26, F30, F34
	common /varXh/ F33, F35, F13, F27, F28, F14, Sub183, Sub190
	common /varXh/ Sub185, Sub212, Sub213, Sub195, Sub196
	common /varXh/ Sub187, Sub208, Sub207, Sub203, Sub184
	common /varXh/ Sub197, Sub198, Sub194, Sub192, Sub205
	common /varXh/ Sub204, Sub235, Sub165, Sub258, Sub237
	common /varXh/ Sub263, Sub206, Sub202, Sub210, Sub239
	common /varXh/ Sub118, Sub119, Sub182, Sub188, Sub193
	common /varXh/ Sub199, Sub166, Sub243, Sub117, Sub226
	common /varXh/ Sub176, Sub174, Sub167, Sub221, Sub244
	common /varXh/ Sub246, Sub224, Sub222, Sub233, Sub245
	common /varXh/ Sub247, Sub251, Sub252, Sub62, Sub223, Sub169
	common /varXh/ Sub229, Sub225, Sub227, Sub124, Sub67, Sub168
	common /varXh/ Sub231, Sub170, Sub172, Sub177, Sub60, Sub214
	common /varXh/ Sub61, Sub123, Sub68, Sub171, Sub173, Sub191
	common /varXh/ Sub178, Sub180, Sub179, Sub181, Sub209
	common /varXh/ Sub201, Sub236, Sub238, Sub256, Sub257
	common /varXh/ Sub255, Sub262, Sub261, Sub250, Sub215
	common /varXh/ Sub232, Sub200, Sub248, Sub249

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors_dubar_n1x1/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
