#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 19-Jun-2015 11:45
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub5, Sub2, Sub3(2), Sub7(2), Sub4(2)
	ComplexType Sub9(2), Sub6(2), Sub10(2)
	ComplexType Sub130, Sub152, Sub76, Sub114, Sub83, Sub175
	ComplexType Sub115, Sub84, Sub142, Sub131, Sub153, Sub77
	ComplexType Sub129, Sub93, Sub103, Sub94, Sub111, Sub113
	ComplexType Sub151, Sub147, Sub82, Sub86, Sub75, Sub136
	ComplexType Sub127, Sub132, Sub79, Sub78, Sub88, Sub89
	ComplexType Sub64, Sub99, Sub144, Sub139, Sub140, Sub106
	ComplexType Sub107, Sub108, Sub105, Sub95, Sub96, Sub97
	ComplexType Sub156, Sub157, Sub158, Sub141(2), Sub162(2)
	ComplexType Sub126(2), Sub74(2), Sub146(2), Sub81(2)
	ComplexType Sub150(2), Sub80(2), Sub87(2), Sub145(2)
	ComplexType Sub148(2), Sub149(2), Sub85(2), Sub90(2)
	ComplexType Sub154(2), Sub161(2), Sub100(2), Sub124(2)
	ComplexType Sub101(2), Sub125(2), Sub116(2), Sub134(2)
	ComplexType Sub128(2), Sub109(2), Sub112(2), Sub119(2)
	ComplexType Sub133(2), Sub91(2), Sub135(2), Sub92(2)
	ComplexType Sub110(2), Sub138(2), Sub214(2), Sub102(2)
	ComplexType Sub121(2), Sub163(2), Sub155(2), Sub120(2)
	ComplexType Sub15(2), Sub60(2), Sub65(2), Sub69(2), Sub24(2)
	ComplexType Sub71(2), Sub66(2), Sub70(2), Sub25(2)
	ComplexType Sub14(2,2), Sub12(2,2), Sub38(2,2), Sub37(2,2)
	ComplexType Sub47(2,2), Sub39(2,2), Sub48(2,2), Sub40(2,2)
	ComplexType Sub46(2,2,2), Sub54(2,2,2), Sub234, Sub13(2,2)
	ComplexType Sub11(2,2), Sub55, Sub159, Sub98, Sub137, Sub143
	ComplexType Sub104, Sub117, Sub160, Sub118, pave1(2)
	ComplexType pave2(2), pave3(Nbb), pave4(Ncc), pave10(Ncc,2)
	ComplexType pave18(Ncc,2,2), pave23
	common /varXs/ Sub8, Sub1, Sub5, Sub2, Sub3, Sub7, Sub4, Sub9
	common /varXs/ Sub6, Sub10, Sub130, Sub152, Sub76, Sub114
	common /varXs/ Sub83, Sub175, Sub115, Sub84, Sub142, Sub131
	common /varXs/ Sub153, Sub77, Sub129, Sub93, Sub103, Sub94
	common /varXs/ Sub111, Sub113, Sub151, Sub147, Sub82, Sub86
	common /varXs/ Sub75, Sub136, Sub127, Sub132, Sub79, Sub78
	common /varXs/ Sub88, Sub89, Sub64, Sub99, Sub144, Sub139
	common /varXs/ Sub140, Sub106, Sub107, Sub108, Sub105, Sub95
	common /varXs/ Sub96, Sub97, Sub156, Sub157, Sub158, Sub141
	common /varXs/ Sub162, Sub126, Sub74, Sub146, Sub81, Sub150
	common /varXs/ Sub80, Sub87, Sub145, Sub148, Sub149, Sub85
	common /varXs/ Sub90, Sub154, Sub161, Sub100, Sub124, Sub101
	common /varXs/ Sub125, Sub116, Sub134, Sub128, Sub109
	common /varXs/ Sub112, Sub119, Sub133, Sub91, Sub135, Sub92
	common /varXs/ Sub110, Sub138, Sub214, Sub102, Sub121
	common /varXs/ Sub163, Sub155, Sub120, Sub15, Sub60, Sub65
	common /varXs/ Sub69, Sub24, Sub71, Sub66, Sub70, Sub25
	common /varXs/ Sub14, Sub12, Sub38, Sub37, Sub47, Sub39
	common /varXs/ Sub48, Sub40, Sub46, Sub54, Sub234, Sub13
	common /varXs/ Sub11, Sub55, Sub159, Sub98, Sub137, Sub143
	common /varXs/ Sub104, Sub117, Sub160, Sub118, pave1, pave2
	common /varXs/ pave3, pave4, pave10, pave18, pave23

	ComplexType Sub219, Sub57, Sub59, Sub56, Sub58, Sub240(2)
	ComplexType Sub259(2), Sub253(2), Sub260(2), Sub217(2)
	ComplexType Sub216(2), Sub254(2), Sub228(2), Sub230(2)
	ComplexType Sub242(2), Sub218(2,2), Sub220(2,2), Sub191
	ComplexType Sub183, Sub241(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub219, Sub57, Sub59, Sub56, Sub58, Sub240
	common /varXa/ Sub259, Sub253, Sub260, Sub217, Sub216
	common /varXa/ Sub254, Sub228, Sub230, Sub242, Sub218
	common /varXa/ Sub220, Sub191, Sub183, Sub241, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave21, pave22, S, T, U

	HelType F1, F3, F5, F2, F7, F6, F8, F4
	HelType F20, F15, F12, F9, F17, F16, F22, F23, F21, F24, F18
	HelType F19, F10, F11, F31, F25, F32, F29, F26, F30, F34
	HelType F33, F35, F13, F27, F28, F14, Sub188, Sub184, Sub190
	HelType Sub202, Sub211, Sub212, Sub203, Sub192, Sub205
	HelType Sub204, Sub208, Sub189, Sub194, Sub195, Sub201
	HelType Sub186, Sub210, Sub209, Sub235(HelDim(2))
	HelType Sub164(HelDim(2)), Sub258(HelDim(2))
	HelType Sub237(HelDim(2)), Sub263(HelDim(2))
	HelType Sub197(HelDim(2)), Sub200(HelDim(2))
	HelType Sub207(HelDim(2)), Sub165(HelDim(2))
	HelType Sub166(HelDim(2)), Sub239(HelDim(2))
	HelType Sub182(HelDim(2)), Sub187(HelDim(2))
	HelType Sub193(HelDim(2)), Sub196(HelDim(2))
	HelType Sub123(HelDim(2)), Sub243(HelDim(2))
	HelType Sub122(HelDim(2)), Sub226(HelDim(2))
	HelType Sub172(HelDim(2)), Sub176(HelDim(2))
	HelType Sub169(HelDim(2)), Sub221(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub224(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub63(HelDim(2),2)
	HelType Sub223(HelDim(2),2), Sub168(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub73(HelDim(2),2)
	HelType Sub67(HelDim(2),2), Sub167(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub173(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub177(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub213(HelDim(2),2)
	HelType Sub62(HelDim(2),2), Sub72(HelDim(2),2)
	HelType Sub68(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub185, Sub181, Sub179, Sub180
	HelType Sub178, Sub206, Sub199, Sub236(HelDim(2))
	HelType Sub238(HelDim(2)), Sub256(HelDim(2))
	HelType Sub257(HelDim(2)), Sub255(HelDim(2))
	HelType Sub262(HelDim(2)), Sub261(HelDim(2))
	HelType Sub245(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub198, Sub252(HelDim(2),2)
	HelType Sub244(HelDim(2),2)
	common /varXh/ F1, F3, F5, F2, F7, F6, F8, F4, F20, F15, F12
	common /varXh/ F9, F17, F16, F22, F23, F21, F24, F18, F19
	common /varXh/ F10, F11, F31, F25, F32, F29, F26, F30, F34
	common /varXh/ F33, F35, F13, F27, F28, F14, Sub188, Sub184
	common /varXh/ Sub190, Sub202, Sub211, Sub212, Sub203
	common /varXh/ Sub192, Sub205, Sub204, Sub208, Sub189
	common /varXh/ Sub194, Sub195, Sub201, Sub186, Sub210
	common /varXh/ Sub209, Sub235, Sub164, Sub258, Sub237
	common /varXh/ Sub263, Sub197, Sub200, Sub207, Sub165
	common /varXh/ Sub166, Sub239, Sub182, Sub187, Sub193
	common /varXh/ Sub196, Sub123, Sub243, Sub122, Sub226
	common /varXh/ Sub172, Sub176, Sub169, Sub221, Sub248
	common /varXh/ Sub250, Sub224, Sub222, Sub233, Sub246
	common /varXh/ Sub249, Sub251, Sub247, Sub63, Sub223, Sub168
	common /varXh/ Sub229, Sub225, Sub227, Sub73, Sub67, Sub167
	common /varXh/ Sub231, Sub173, Sub170, Sub177, Sub61, Sub213
	common /varXh/ Sub62, Sub72, Sub68, Sub171, Sub174, Sub185
	common /varXh/ Sub181, Sub179, Sub180, Sub178, Sub206
	common /varXh/ Sub199, Sub236, Sub238, Sub256, Sub257
	common /varXh/ Sub255, Sub262, Sub261, Sub245, Sub215
	common /varXh/ Sub232, Sub198, Sub252, Sub244

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors_dubar_n1x2/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
