#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 19-Jun-2015 12:08
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub4, Sub1, Sub9, Sub2, Sub7(2), Sub3(2), Sub8(2)
	ComplexType Sub5(2), Sub10(2), Sub6(2)
	ComplexType Sub104, Sub75, Sub126, Sub132, Sub81, Sub177
	ComplexType Sub133, Sub82, Sub93, Sub105, Sub127, Sub76
	ComplexType Sub74, Sub140, Sub149, Sub71, Sub157, Sub80
	ComplexType Sub103, Sub98, Sub131, Sub100, Sub86, Sub87
	ComplexType Sub128, Sub78, Sub72, Sub77, Sub136, Sub84
	ComplexType Sub141, Sub64, Sub145, Sub95, Sub90, Sub91
	ComplexType Sub152, Sub153, Sub154, Sub151, Sub142, Sub143
	ComplexType Sub108, Sub109, Sub110, Sub92(2), Sub114(2)
	ComplexType Sub70(2), Sub125(2), Sub97(2), Sub130(2)
	ComplexType Sub102(2), Sub135(2), Sub129(2), Sub101(2)
	ComplexType Sub96(2), Sub99(2), Sub134(2), Sub137(2)
	ComplexType Sub106(2), Sub113(2), Sub146(2), Sub68(2)
	ComplexType Sub147(2), Sub69(2), Sub159(2), Sub83(2)
	ComplexType Sub73(2), Sub155(2), Sub158(2), Sub162(2)
	ComplexType Sub79(2), Sub138(2), Sub139(2), Sub85(2)
	ComplexType Sub156(2), Sub89(2), Sub213(2), Sub148(2)
	ComplexType Sub164(2), Sub115(2), Sub107(2), Sub163(2)
	ComplexType Sub15(2), Sub63(2), Sub65(2), Sub119(2)
	ComplexType Sub31(2), Sub121(2), Sub66(2), Sub120(2)
	ComplexType Sub32(2), Sub14(2,2), Sub12(2,2), Sub38(2,2)
	ComplexType Sub37(2,2), Sub47(2,2), Sub39(2,2), Sub48(2,2)
	ComplexType Sub40(2,2), Sub46(2,2,2), Sub54(2,2,2), Sub233
	ComplexType Sub13(2,2), Sub11(2,2), Sub55, Sub111, Sub144
	ComplexType Sub88, Sub94, Sub150, Sub160, Sub112, Sub161
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave10(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub4, Sub1, Sub9, Sub2, Sub7, Sub3, Sub8, Sub5
	common /varXs/ Sub10, Sub6, Sub104, Sub75, Sub126, Sub132
	common /varXs/ Sub81, Sub177, Sub133, Sub82, Sub93, Sub105
	common /varXs/ Sub127, Sub76, Sub74, Sub140, Sub149, Sub71
	common /varXs/ Sub157, Sub80, Sub103, Sub98, Sub131, Sub100
	common /varXs/ Sub86, Sub87, Sub128, Sub78, Sub72, Sub77
	common /varXs/ Sub136, Sub84, Sub141, Sub64, Sub145, Sub95
	common /varXs/ Sub90, Sub91, Sub152, Sub153, Sub154, Sub151
	common /varXs/ Sub142, Sub143, Sub108, Sub109, Sub110, Sub92
	common /varXs/ Sub114, Sub70, Sub125, Sub97, Sub130, Sub102
	common /varXs/ Sub135, Sub129, Sub101, Sub96, Sub99, Sub134
	common /varXs/ Sub137, Sub106, Sub113, Sub146, Sub68, Sub147
	common /varXs/ Sub69, Sub159, Sub83, Sub73, Sub155, Sub158
	common /varXs/ Sub162, Sub79, Sub138, Sub139, Sub85, Sub156
	common /varXs/ Sub89, Sub213, Sub148, Sub164, Sub115, Sub107
	common /varXs/ Sub163, Sub15, Sub63, Sub65, Sub119, Sub31
	common /varXs/ Sub121, Sub66, Sub120, Sub32, Sub14, Sub12
	common /varXs/ Sub38, Sub37, Sub47, Sub39, Sub48, Sub40
	common /varXs/ Sub46, Sub54, Sub233, Sub13, Sub11, Sub55
	common /varXs/ Sub111, Sub144, Sub88, Sub94, Sub150, Sub160
	common /varXs/ Sub112, Sub161, pave1, pave2, pave3, pave4
	common /varXs/ pave10, pave18, pave23

	ComplexType Sub218, Sub57, Sub59, Sub56, Sub58, Sub234(2)
	ComplexType Sub252(2), Sub259(2), Sub253(2), Sub216(2)
	ComplexType Sub217(2), Sub260(2), Sub227(2), Sub229(2)
	ComplexType Sub236(2), Sub220(2,2), Sub219(2,2), Sub194
	ComplexType Sub182, Sub235(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub218, Sub57, Sub59, Sub56, Sub58, Sub234
	common /varXa/ Sub252, Sub259, Sub253, Sub216, Sub217
	common /varXa/ Sub260, Sub227, Sub229, Sub236, Sub220
	common /varXa/ Sub219, Sub194, Sub182, Sub235, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave21, pave22, S, T, U

	HelType F1, F3, F2, F7, F8, F4, F5, F6
	HelType F20, F15, F12, F9, F18, F16, F22, F23, F21, F24, F17
	HelType F19, F10, F11, F33, F25, F34, F28, F27, F30, F32
	HelType F31, F35, F13, F26, F29, F14, Sub191, Sub187, Sub193
	HelType Sub205, Sub206, Sub199, Sub200, Sub204, Sub195
	HelType Sub203, Sub210, Sub192, Sub184, Sub185, Sub198
	HelType Sub189, Sub212, Sub211, Sub238(HelDim(2))
	HelType Sub165(HelDim(2)), Sub258(HelDim(2))
	HelType Sub240(HelDim(2)), Sub257(HelDim(2))
	HelType Sub183(HelDim(2)), Sub190(HelDim(2))
	HelType Sub196(HelDim(2)), Sub254(HelDim(2))
	HelType Sub186(HelDim(2)), Sub166(HelDim(2))
	HelType Sub237(HelDim(2)), Sub197(HelDim(2))
	HelType Sub202(HelDim(2)), Sub209(HelDim(2))
	HelType Sub242(HelDim(2)), Sub117(HelDim(2))
	HelType Sub261(HelDim(2)), Sub118(HelDim(2))
	HelType Sub116(HelDim(2)), Sub225(HelDim(2))
	HelType Sub174(HelDim(2)), Sub175(HelDim(2))
	HelType Sub167(HelDim(2)), Sub230(HelDim(2))
	HelType Sub221(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub62(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub67(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub172(HelDim(2),2), Sub176(HelDim(2),2)
	HelType Sub60(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub122(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub188, Sub181, Sub179, Sub180
	HelType Sub178, Sub201, Sub208, Sub239(HelDim(2))
	HelType Sub241(HelDim(2)), Sub256(HelDim(2))
	HelType Sub255(HelDim(2)), Sub263(HelDim(2))
	HelType Sub244(HelDim(2),2), Sub226(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub215(HelDim(2),2), Sub207
	HelType Sub262(HelDim(2)), Sub251(HelDim(2),2)
	HelType Sub243(HelDim(2),2)
	common /varXh/ F1, F3, F2, F7, F8, F4, F5, F6, F20, F15, F12
	common /varXh/ F9, F18, F16, F22, F23, F21, F24, F17, F19
	common /varXh/ F10, F11, F33, F25, F34, F28, F27, F30, F32
	common /varXh/ F31, F35, F13, F26, F29, F14, Sub191, Sub187
	common /varXh/ Sub193, Sub205, Sub206, Sub199, Sub200
	common /varXh/ Sub204, Sub195, Sub203, Sub210, Sub192
	common /varXh/ Sub184, Sub185, Sub198, Sub189, Sub212
	common /varXh/ Sub211, Sub238, Sub165, Sub258, Sub240
	common /varXh/ Sub257, Sub183, Sub190, Sub196, Sub254
	common /varXh/ Sub186, Sub166, Sub237, Sub197, Sub202
	common /varXh/ Sub209, Sub242, Sub117, Sub261, Sub118
	common /varXh/ Sub116, Sub225, Sub174, Sub175, Sub167
	common /varXh/ Sub230, Sub221, Sub247, Sub249, Sub224
	common /varXh/ Sub222, Sub232, Sub245, Sub248, Sub250
	common /varXh/ Sub246, Sub62, Sub223, Sub169, Sub228, Sub123
	common /varXh/ Sub67, Sub168, Sub170, Sub172, Sub176, Sub60
	common /varXh/ Sub214, Sub61, Sub122, Sub124, Sub171, Sub173
	common /varXh/ Sub188, Sub181, Sub179, Sub180, Sub178
	common /varXh/ Sub201, Sub208, Sub239, Sub241, Sub256
	common /varXh/ Sub255, Sub263, Sub244, Sub226, Sub231
	common /varXh/ Sub215, Sub207, Sub262, Sub251, Sub243

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors_dubar_n2x1/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
