#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 12:21
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub5, Sub2, Sub3(2), Sub7(2), Sub4(2)
	ComplexType Sub9(2), Sub6(2), Sub10(2)
	ComplexType Sub110, Sub81, Sub126, Sub132, Sub87, Sub174
	ComplexType Sub133, Sub88, Sub99, Sub111, Sub127, Sub82
	ComplexType Sub80, Sub140, Sub149, Sub77, Sub157, Sub86
	ComplexType Sub109, Sub104, Sub131, Sub106, Sub92, Sub93
	ComplexType Sub78, Sub128, Sub84, Sub83, Sub136, Sub90
	ComplexType Sub141, Sub142, Sub63, Sub145, Sub101, Sub96
	ComplexType Sub97, Sub152, Sub153, Sub154, Sub151, Sub143
	ComplexType Sub114, Sub115, Sub116, Sub98(2), Sub120(2)
	ComplexType Sub76(2), Sub125(2), Sub103(2), Sub130(2)
	ComplexType Sub108(2), Sub135(2), Sub129(2), Sub102(2)
	ComplexType Sub105(2), Sub107(2), Sub134(2), Sub137(2)
	ComplexType Sub112(2), Sub119(2), Sub146(2), Sub74(2)
	ComplexType Sub147(2), Sub75(2), Sub159(2), Sub89(2)
	ComplexType Sub79(2), Sub155(2), Sub158(2), Sub162(2)
	ComplexType Sub85(2), Sub138(2), Sub139(2), Sub91(2)
	ComplexType Sub156(2), Sub95(2), Sub210(2), Sub148(2)
	ComplexType Sub121(2), Sub164(2), Sub113(2), Sub163(2)
	ComplexType Sub15(2), Sub67(2), Sub64(2), Sub69(2), Sub31(2)
	ComplexType Sub71(2), Sub65(2), Sub70(2), Sub32(2)
	ComplexType Sub14(2,2), Sub12(2,2), Sub38(2,2), Sub37(2,2)
	ComplexType Sub47(2,2), Sub39(2,2), Sub48(2,2), Sub40(2,2)
	ComplexType Sub46(2,2,2), Sub54(2,2,2), Sub234, Sub13(2,2)
	ComplexType Sub11(2,2), Sub55, Sub117, Sub144, Sub94, Sub100
	ComplexType Sub150, Sub160, Sub118, Sub161, pave1(2)
	ComplexType pave2(2), pave3(Nbb), pave4(Ncc), pave10(Ncc,2)
	ComplexType pave18(Ncc,2,2), pave23
	common /varXs/ Sub8, Sub1, Sub5, Sub2, Sub3, Sub7, Sub4, Sub9
	common /varXs/ Sub6, Sub10, Sub110, Sub81, Sub126, Sub132
	common /varXs/ Sub87, Sub174, Sub133, Sub88, Sub99, Sub111
	common /varXs/ Sub127, Sub82, Sub80, Sub140, Sub149, Sub77
	common /varXs/ Sub157, Sub86, Sub109, Sub104, Sub131, Sub106
	common /varXs/ Sub92, Sub93, Sub78, Sub128, Sub84, Sub83
	common /varXs/ Sub136, Sub90, Sub141, Sub142, Sub63, Sub145
	common /varXs/ Sub101, Sub96, Sub97, Sub152, Sub153, Sub154
	common /varXs/ Sub151, Sub143, Sub114, Sub115, Sub116, Sub98
	common /varXs/ Sub120, Sub76, Sub125, Sub103, Sub130, Sub108
	common /varXs/ Sub135, Sub129, Sub102, Sub105, Sub107
	common /varXs/ Sub134, Sub137, Sub112, Sub119, Sub146, Sub74
	common /varXs/ Sub147, Sub75, Sub159, Sub89, Sub79, Sub155
	common /varXs/ Sub158, Sub162, Sub85, Sub138, Sub139, Sub91
	common /varXs/ Sub156, Sub95, Sub210, Sub148, Sub121, Sub164
	common /varXs/ Sub113, Sub163, Sub15, Sub67, Sub64, Sub69
	common /varXs/ Sub31, Sub71, Sub65, Sub70, Sub32, Sub14
	common /varXs/ Sub12, Sub38, Sub37, Sub47, Sub39, Sub48
	common /varXs/ Sub40, Sub46, Sub54, Sub234, Sub13, Sub11
	common /varXs/ Sub55, Sub117, Sub144, Sub94, Sub100, Sub150
	common /varXs/ Sub160, Sub118, Sub161, pave1, pave2, pave3
	common /varXs/ pave4, pave10, pave18, pave23

	ComplexType Sub219, Sub57, Sub58, Sub56, Sub59, Sub240(2)
	ComplexType Sub260(2), Sub253(2), Sub258(2), Sub217(2)
	ComplexType Sub216(2), Sub228(2), Sub230(2), Sub242(2)
	ComplexType Sub218(2,2), Sub220(2,2), Sub195, Sub190
	ComplexType Sub241(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub219, Sub57, Sub58, Sub56, Sub59, Sub240
	common /varXa/ Sub260, Sub253, Sub258, Sub217, Sub216
	common /varXa/ Sub228, Sub230, Sub242, Sub218, Sub220
	common /varXa/ Sub195, Sub190, Sub241, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave11, pave12, pave13, pave14
	common /varXa/ pave15, pave16, pave17, pave19, pave20
	common /varXa/ pave21, pave22, S, T, U

	HelType F1, F3, F5, F2, F8, F6, F7, F4
	HelType F20, F16, F12, F9, F15, F17, F22, F25, F21, F23, F18
	HelType F19, F11, F10, F31, F24, F32, F29, F26, F30, F34
	HelType F33, F35, F13, F27, F28, F14, Sub192, Sub185, Sub194
	HelType Sub199, Sub205, Sub206, Sub200, Sub196, Sub204
	HelType Sub203, Sub211, Sub193, Sub182, Sub183, Sub198
	HelType Sub187, Sub213, Sub212, Sub235(HelDim(2))
	HelType Sub165(HelDim(2)), Sub257(HelDim(2))
	HelType Sub237(HelDim(2)), Sub263(HelDim(2))
	HelType Sub191(HelDim(2)), Sub209(HelDim(2))
	HelType Sub202(HelDim(2)), Sub254(HelDim(2))
	HelType Sub239(HelDim(2)), Sub123(HelDim(2))
	HelType Sub189(HelDim(2)), Sub184(HelDim(2))
	HelType Sub188(HelDim(2)), Sub197(HelDim(2))
	HelType Sub166(HelDim(2)), Sub259(HelDim(2))
	HelType Sub243(HelDim(2)), Sub124(HelDim(2))
	HelType Sub122(HelDim(2)), Sub226(HelDim(2))
	HelType Sub170(HelDim(2)), Sub173(HelDim(2))
	HelType Sub167(HelDim(2)), Sub221(HelDim(2),2)
	HelType Sub248(HelDim(2),2), Sub250(HelDim(2),2)
	HelType Sub224(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub233(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub251(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub223(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub73(HelDim(2),2)
	HelType Sub66(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub231(HelDim(2),2), Sub175(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub177(HelDim(2),2)
	HelType Sub60(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub72(HelDim(2),2)
	HelType Sub68(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub176(HelDim(2),2), Sub186, Sub180, Sub178, Sub181
	HelType Sub179, Sub201, Sub208, Sub236(HelDim(2))
	HelType Sub238(HelDim(2)), Sub262(HelDim(2))
	HelType Sub256(HelDim(2)), Sub261(HelDim(2))
	HelType Sub245(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub207, Sub255(HelDim(2))
	HelType Sub252(HelDim(2),2), Sub244(HelDim(2),2)
	common /varXh/ F1, F3, F5, F2, F8, F6, F7, F4, F20, F16, F12
	common /varXh/ F9, F15, F17, F22, F25, F21, F23, F18, F19
	common /varXh/ F11, F10, F31, F24, F32, F29, F26, F30, F34
	common /varXh/ F33, F35, F13, F27, F28, F14, Sub192, Sub185
	common /varXh/ Sub194, Sub199, Sub205, Sub206, Sub200
	common /varXh/ Sub196, Sub204, Sub203, Sub211, Sub193
	common /varXh/ Sub182, Sub183, Sub198, Sub187, Sub213
	common /varXh/ Sub212, Sub235, Sub165, Sub257, Sub237
	common /varXh/ Sub263, Sub191, Sub209, Sub202, Sub254
	common /varXh/ Sub239, Sub123, Sub189, Sub184, Sub188
	common /varXh/ Sub197, Sub166, Sub259, Sub243, Sub124
	common /varXh/ Sub122, Sub226, Sub170, Sub173, Sub167
	common /varXh/ Sub221, Sub248, Sub250, Sub224, Sub222
	common /varXh/ Sub233, Sub246, Sub249, Sub251, Sub247, Sub62
	common /varXh/ Sub223, Sub172, Sub229, Sub225, Sub227, Sub73
	common /varXh/ Sub66, Sub171, Sub231, Sub175, Sub168, Sub177
	common /varXh/ Sub60, Sub214, Sub61, Sub72, Sub68, Sub169
	common /varXh/ Sub176, Sub186, Sub180, Sub178, Sub181
	common /varXh/ Sub179, Sub201, Sub208, Sub236, Sub238
	common /varXh/ Sub262, Sub256, Sub261, Sub245, Sub215
	common /varXh/ Sub232, Sub207, Sub255, Sub252, Sub244

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /dubar_n3x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
