#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 19-Jun-2015 12:42
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub5, Sub2, Sub3(2), Sub7(2), Sub4(2)
	ComplexType Sub9(2), Sub6(2), Sub10(2)
	ComplexType Sub105, Sub76, Sub127, Sub133, Sub82, Sub176
	ComplexType Sub134, Sub83, Sub94, Sub106, Sub128, Sub77
	ComplexType Sub75, Sub141, Sub150, Sub72, Sub158, Sub81
	ComplexType Sub104, Sub99, Sub132, Sub101, Sub87, Sub88
	ComplexType Sub73, Sub129, Sub79, Sub78, Sub137, Sub85
	ComplexType Sub142, Sub63, Sub146, Sub96, Sub91, Sub92
	ComplexType Sub153, Sub154, Sub155, Sub152, Sub143, Sub144
	ComplexType Sub109, Sub110, Sub111, Sub93(2), Sub115(2)
	ComplexType Sub71(2), Sub126(2), Sub98(2), Sub131(2)
	ComplexType Sub103(2), Sub136(2), Sub130(2), Sub102(2)
	ComplexType Sub97(2), Sub100(2), Sub135(2), Sub138(2)
	ComplexType Sub107(2), Sub114(2), Sub147(2), Sub69(2)
	ComplexType Sub148(2), Sub70(2), Sub160(2), Sub84(2)
	ComplexType Sub74(2), Sub156(2), Sub159(2), Sub163(2)
	ComplexType Sub80(2), Sub139(2), Sub140(2), Sub86(2)
	ComplexType Sub157(2), Sub90(2), Sub213(2), Sub149(2)
	ComplexType Sub116(2), Sub165(2), Sub108(2), Sub164(2)
	ComplexType Sub15(2), Sub67(2), Sub64(2), Sub120(2)
	ComplexType Sub31(2), Sub122(2), Sub65(2), Sub121(2)
	ComplexType Sub32(2), Sub14(2,2), Sub12(2,2), Sub38(2,2)
	ComplexType Sub37(2,2), Sub47(2,2), Sub39(2,2), Sub48(2,2)
	ComplexType Sub40(2,2), Sub46(2,2,2), Sub54(2,2,2), Sub234
	ComplexType Sub13(2,2), Sub11(2,2), Sub55, Sub112, Sub145
	ComplexType Sub89, Sub95, Sub151, Sub161, Sub113, Sub162
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave10(Ncc,2), pave18(Ncc,2,2), pave23
	common /varXs/ Sub8, Sub1, Sub5, Sub2, Sub3, Sub7, Sub4, Sub9
	common /varXs/ Sub6, Sub10, Sub105, Sub76, Sub127, Sub133
	common /varXs/ Sub82, Sub176, Sub134, Sub83, Sub94, Sub106
	common /varXs/ Sub128, Sub77, Sub75, Sub141, Sub150, Sub72
	common /varXs/ Sub158, Sub81, Sub104, Sub99, Sub132, Sub101
	common /varXs/ Sub87, Sub88, Sub73, Sub129, Sub79, Sub78
	common /varXs/ Sub137, Sub85, Sub142, Sub63, Sub146, Sub96
	common /varXs/ Sub91, Sub92, Sub153, Sub154, Sub155, Sub152
	common /varXs/ Sub143, Sub144, Sub109, Sub110, Sub111, Sub93
	common /varXs/ Sub115, Sub71, Sub126, Sub98, Sub131, Sub103
	common /varXs/ Sub136, Sub130, Sub102, Sub97, Sub100, Sub135
	common /varXs/ Sub138, Sub107, Sub114, Sub147, Sub69, Sub148
	common /varXs/ Sub70, Sub160, Sub84, Sub74, Sub156, Sub159
	common /varXs/ Sub163, Sub80, Sub139, Sub140, Sub86, Sub157
	common /varXs/ Sub90, Sub213, Sub149, Sub116, Sub165, Sub108
	common /varXs/ Sub164, Sub15, Sub67, Sub64, Sub120, Sub31
	common /varXs/ Sub122, Sub65, Sub121, Sub32, Sub14, Sub12
	common /varXs/ Sub38, Sub37, Sub47, Sub39, Sub48, Sub40
	common /varXs/ Sub46, Sub54, Sub234, Sub13, Sub11, Sub55
	common /varXs/ Sub112, Sub145, Sub89, Sub95, Sub151, Sub161
	common /varXs/ Sub113, Sub162, pave1, pave2, pave3, pave4
	common /varXs/ pave10, pave18, pave23

	ComplexType Sub219, Sub57, Sub59, Sub56, Sub58, Sub240(2)
	ComplexType Sub261(2), Sub253(2), Sub259(2), Sub217(2)
	ComplexType Sub216(2), Sub254(2), Sub228(2), Sub230(2)
	ComplexType Sub242(2), Sub218(2,2), Sub220(2,2), Sub195
	ComplexType Sub186, Sub241(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave11(Ndd,2), pave12(Ndd,2), pave13(Nbb,2)
	ComplexType pave14(Nbb,2), pave15(Ncc,2), pave16(Ncc,2)
	ComplexType pave17(Ncc,2), pave19(Ndd,2,2), pave20(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub219, Sub57, Sub59, Sub56, Sub58, Sub240
	common /varXa/ Sub261, Sub253, Sub259, Sub217, Sub216
	common /varXa/ Sub254, Sub228, Sub230, Sub242, Sub218
	common /varXa/ Sub220, Sub195, Sub186, Sub241, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave21, pave22, S, T, U

	HelType F1, F3, F5, F2, F7, F6, F8, F4
	HelType F20, F16, F12, F9, F15, F17, F23, F22, F21, F25, F18
	HelType F19, F10, F11, F31, F24, F32, F29, F28, F30, F34
	HelType F33, F35, F13, F26, F27, F14, Sub192, Sub187, Sub194
	HelType Sub202, Sub211, Sub212, Sub203, Sub196, Sub208
	HelType Sub207, Sub204, Sub193, Sub182, Sub183, Sub201
	HelType Sub189, Sub206, Sub205, Sub235(HelDim(2))
	HelType Sub166(HelDim(2)), Sub258(HelDim(2))
	HelType Sub237(HelDim(2)), Sub264(HelDim(2))
	HelType Sub191(HelDim(2)), Sub200(HelDim(2))
	HelType Sub210(HelDim(2)), Sub239(HelDim(2))
	HelType Sub118(HelDim(2)), Sub119(HelDim(2))
	HelType Sub185(HelDim(2)), Sub184(HelDim(2))
	HelType Sub190(HelDim(2)), Sub197(HelDim(2))
	HelType Sub167(HelDim(2)), Sub260(HelDim(2))
	HelType Sub243(HelDim(2)), Sub117(HelDim(2))
	HelType Sub226(HelDim(2)), Sub175(HelDim(2))
	HelType Sub170(HelDim(2)), Sub125(HelDim(2))
	HelType Sub221(HelDim(2),2), Sub244(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub252(HelDim(2),2)
	HelType Sub62(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub229(HelDim(2),2)
	HelType Sub225(HelDim(2),2), Sub227(HelDim(2),2)
	HelType Sub124(HelDim(2),2), Sub66(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub231(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub173(HelDim(2),2)
	HelType Sub179(HelDim(2),2), Sub60(HelDim(2),2)
	HelType Sub214(HelDim(2),2), Sub61(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub68(HelDim(2),2)
	HelType Sub172(HelDim(2),2), Sub174(HelDim(2),2), Sub188
	HelType Sub181, Sub178, Sub180, Sub177, Sub209, Sub199
	HelType Sub236(HelDim(2)), Sub238(HelDim(2))
	HelType Sub263(HelDim(2)), Sub256(HelDim(2))
	HelType Sub257(HelDim(2)), Sub255(HelDim(2))
	HelType Sub262(HelDim(2)), Sub250(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub232(HelDim(2),2), Sub198
	HelType Sub248(HelDim(2),2), Sub249(HelDim(2),2)
	common /varXh/ F1, F3, F5, F2, F7, F6, F8, F4, F20, F16, F12
	common /varXh/ F9, F15, F17, F23, F22, F21, F25, F18, F19
	common /varXh/ F10, F11, F31, F24, F32, F29, F28, F30, F34
	common /varXh/ F33, F35, F13, F26, F27, F14, Sub192, Sub187
	common /varXh/ Sub194, Sub202, Sub211, Sub212, Sub203
	common /varXh/ Sub196, Sub208, Sub207, Sub204, Sub193
	common /varXh/ Sub182, Sub183, Sub201, Sub189, Sub206
	common /varXh/ Sub205, Sub235, Sub166, Sub258, Sub237
	common /varXh/ Sub264, Sub191, Sub200, Sub210, Sub239
	common /varXh/ Sub118, Sub119, Sub185, Sub184, Sub190
	common /varXh/ Sub197, Sub167, Sub260, Sub243, Sub117
	common /varXh/ Sub226, Sub175, Sub170, Sub125, Sub221
	common /varXh/ Sub244, Sub246, Sub224, Sub222, Sub233
	common /varXh/ Sub245, Sub247, Sub251, Sub252, Sub62, Sub223
	common /varXh/ Sub169, Sub229, Sub225, Sub227, Sub124, Sub66
	common /varXh/ Sub168, Sub231, Sub171, Sub173, Sub179, Sub60
	common /varXh/ Sub214, Sub61, Sub123, Sub68, Sub172, Sub174
	common /varXh/ Sub188, Sub181, Sub178, Sub180, Sub177
	common /varXh/ Sub209, Sub199, Sub236, Sub238, Sub263
	common /varXh/ Sub256, Sub257, Sub255, Sub262, Sub250
	common /varXh/ Sub215, Sub232, Sub198, Sub248, Sub249

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors_dubar_n2x2/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
