#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 13:44
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub2, Sub7(2), Sub3(2), Sub9(2)
	ComplexType Sub4(2), Sub6(2), Sub10(2), Sub5(2)
	ComplexType Sub129, Sub77, Sub111, Sub82, Sub138, Sub181
	ComplexType Sub93, Sub112, Sub139, Sub83, Sub130, Sub78
	ComplexType Sub151, Sub142, Sub81, Sub86, Sub76, Sub159
	ComplexType Sub128, Sub105, Sub110, Sub107, Sub97, Sub92
	ComplexType Sub134, Sub74, Sub87, Sub140, Sub85, Sub84
	ComplexType Sub143, Sub144, Sub145, Sub68, Sub147, Sub154
	ComplexType Sub155, Sub156, Sub153, Sub95, Sub96, Sub99
	ComplexType Sub100, Sub115, Sub116, Sub117, Sub65, Sub118
	ComplexType Sub101(2), Sub122(2), Sub136(2), Sub137(2)
	ComplexType Sub104(2), Sub132(2), Sub109(2), Sub127(2)
	ComplexType Sub106(2), Sub108(2), Sub103(2), Sub133(2)
	ComplexType Sub113(2), Sub121(2), Sub131(2), Sub135(2)
	ComplexType Sub75(2), Sub148(2), Sub88(2), Sub149(2)
	ComplexType Sub79(2), Sub80(2), Sub161(2), Sub91(2)
	ComplexType Sub157(2), Sub160(2), Sub164(2), Sub90(2)
	ComplexType Sub141(2), Sub89(2), Sub102(2), Sub158(2)
	ComplexType Sub150(2), Sub213(2), Sub123(2), Sub166(2)
	ComplexType Sub165(2), Sub114(2), Sub72(2), Sub18(2)
	ComplexType Sub64(2), Sub29(2), Sub69(2), Sub66(2), Sub30(2)
	ComplexType Sub70(2), Sub13(2,2), Sub12(2,2), Sub37(2,2)
	ComplexType Sub38(2,2), Sub40(2,2), Sub48(2,2), Sub41(2,2)
	ComplexType Sub49(2,2), Sub47(2,2,2), Sub55(2,2,2), Sub234
	ComplexType Sub14(2,2), Sub11(2,2), Sub56, Sub119, Sub146
	ComplexType Sub98, Sub152, Sub94, Sub162, Sub163, Sub120
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave17(Ncc,2,2), pave20, pave23(Ncc,2)
	ComplexType pave24(Ncc,2)
	common /varXs/ Sub8, Sub1, Sub2, Sub7, Sub3, Sub9, Sub4, Sub6
	common /varXs/ Sub10, Sub5, Sub129, Sub77, Sub111, Sub82
	common /varXs/ Sub138, Sub181, Sub93, Sub112, Sub139, Sub83
	common /varXs/ Sub130, Sub78, Sub151, Sub142, Sub81, Sub86
	common /varXs/ Sub76, Sub159, Sub128, Sub105, Sub110, Sub107
	common /varXs/ Sub97, Sub92, Sub134, Sub74, Sub87, Sub140
	common /varXs/ Sub85, Sub84, Sub143, Sub144, Sub145, Sub68
	common /varXs/ Sub147, Sub154, Sub155, Sub156, Sub153, Sub95
	common /varXs/ Sub96, Sub99, Sub100, Sub115, Sub116, Sub117
	common /varXs/ Sub65, Sub118, Sub101, Sub122, Sub136, Sub137
	common /varXs/ Sub104, Sub132, Sub109, Sub127, Sub106
	common /varXs/ Sub108, Sub103, Sub133, Sub113, Sub121
	common /varXs/ Sub131, Sub135, Sub75, Sub148, Sub88, Sub149
	common /varXs/ Sub79, Sub80, Sub161, Sub91, Sub157, Sub160
	common /varXs/ Sub164, Sub90, Sub141, Sub89, Sub102, Sub158
	common /varXs/ Sub150, Sub213, Sub123, Sub166, Sub165
	common /varXs/ Sub114, Sub72, Sub18, Sub64, Sub29, Sub69
	common /varXs/ Sub66, Sub30, Sub70, Sub13, Sub12, Sub37
	common /varXs/ Sub38, Sub40, Sub48, Sub41, Sub49, Sub47
	common /varXs/ Sub55, Sub234, Sub14, Sub11, Sub56, Sub119
	common /varXs/ Sub146, Sub98, Sub152, Sub94, Sub162, Sub163
	common /varXs/ Sub120, pave1, pave2, pave3, pave4, pave17
	common /varXs/ pave20, pave23, pave24

	ComplexType Sub218, Sub58, Sub59, Sub57, Sub60, Sub235(2)
	ComplexType Sub260(2), Sub253(2), Sub216(2), Sub217(2)
	ComplexType Sub254(2), Sub261(2), Sub224(2), Sub226(2)
	ComplexType Sub39(2,2), Sub219(2,2), Sub237(2), Sub220(2,2)
	ComplexType Sub185, Sub236(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ndd,2), pave11(Ndd,2), pave12(Nbb,2)
	ComplexType pave13(Nbb,2), pave14(Ncc,2), pave15(Ncc,2)
	ComplexType pave16(Ncc,2), pave18(Ndd,2,2), pave19(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave22(Nbb)
	RealType S, T, U
	common /varXa/ Sub218, Sub58, Sub59, Sub57, Sub60, Sub235
	common /varXa/ Sub260, Sub253, Sub216, Sub217, Sub254
	common /varXa/ Sub261, Sub224, Sub226, Sub39, Sub219, Sub237
	common /varXa/ Sub220, Sub185, Sub236, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave18, pave19
	common /varXa/ pave21, pave22, S, T, U

	HelType F6, F4, F7, F5, F1, F8, F3, F2
	HelType F18, F15, F12, F20, F9, F16, F17, F37, F21, F11, F10
	HelType F35, F24, F22, F19, F29, F30, F36, F28, F23, F31
	HelType F27, F25, F14, F32, F13, F34, F26, F33, Sub193
	HelType Sub203, Sub187, Sub207, Sub210, Sub201, Sub212
	HelType Sub202, Sub205, Sub204, Sub194, Sub195, Sub189
	HelType Sub190, Sub200, Sub209, Sub186, Sub211
	HelType Sub239(HelDim(2)), Sub259(HelDim(2))
	HelType Sub241(HelDim(2)), Sub258(HelDim(2))
	HelType Sub264(HelDim(2)), Sub192(HelDim(2))
	HelType Sub199(HelDim(2)), Sub206(HelDim(2))
	HelType Sub208(HelDim(2)), Sub125(HelDim(2))
	HelType Sub238(HelDim(2)), Sub184(HelDim(2))
	HelType Sub191(HelDim(2)), Sub196(HelDim(2))
	HelType Sub188(HelDim(2)), Sub167(HelDim(2))
	HelType Sub168(HelDim(2)), Sub243(HelDim(2))
	HelType Sub124(HelDim(2)), Sub231(HelDim(2))
	HelType Sub177(HelDim(2)), Sub227(HelDim(2))
	HelType Sub171(HelDim(2)), Sub172(HelDim(2))
	HelType Sub221(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub229(HelDim(2),2)
	HelType Sub222(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub63(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub175(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub71(HelDim(2),2)
	HelType Sub126(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub176(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub178(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub214(HelDim(2),2), Sub61(HelDim(2),2)
	HelType Sub73(HelDim(2),2), Sub67(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub179, Sub182, Sub180, Sub183
	HelType Sub197, Sub198, Sub240(HelDim(2)), Sub242(HelDim(2))
	HelType Sub255(HelDim(2)), Sub257(HelDim(2))
	HelType Sub256(HelDim(2)), Sub245(HelDim(2),2)
	HelType Sub228(HelDim(2),2), Sub215(HelDim(2),2)
	HelType Sub263(HelDim(2)), Sub262(HelDim(2))
	HelType Sub252(HelDim(2),2), Sub244(HelDim(2),2)
	common /varXh/ F6, F4, F7, F5, F1, F8, F3, F2, F18, F15, F12
	common /varXh/ F20, F9, F16, F17, F37, F21, F11, F10, F35
	common /varXh/ F24, F22, F19, F29, F30, F36, F28, F23, F31
	common /varXh/ F27, F25, F14, F32, F13, F34, F26, F33
	common /varXh/ Sub193, Sub203, Sub187, Sub207, Sub210
	common /varXh/ Sub201, Sub212, Sub202, Sub205, Sub204
	common /varXh/ Sub194, Sub195, Sub189, Sub190, Sub200
	common /varXh/ Sub209, Sub186, Sub211, Sub239, Sub259
	common /varXh/ Sub241, Sub258, Sub264, Sub192, Sub199
	common /varXh/ Sub206, Sub208, Sub125, Sub238, Sub184
	common /varXh/ Sub191, Sub196, Sub188, Sub167, Sub168
	common /varXh/ Sub243, Sub124, Sub231, Sub177, Sub227
	common /varXh/ Sub171, Sub172, Sub221, Sub248, Sub250
	common /varXh/ Sub229, Sub222, Sub233, Sub246, Sub249
	common /varXh/ Sub251, Sub63, Sub247, Sub223, Sub174, Sub225
	common /varXh/ Sub230, Sub175, Sub169, Sub71, Sub126, Sub170
	common /varXh/ Sub176, Sub232, Sub178, Sub62, Sub214, Sub61
	common /varXh/ Sub73, Sub67, Sub173, Sub179, Sub182, Sub180
	common /varXh/ Sub183, Sub197, Sub198, Sub240, Sub242
	common /varXh/ Sub255, Sub257, Sub256, Sub245, Sub228
	common /varXh/ Sub215, Sub263, Sub262, Sub252, Sub244

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /udbar_n4x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
