#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 13:13
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub2, Sub7(2), Sub3(2), Sub9(2)
	ComplexType Sub4(2), Sub6(2), Sub10(2), Sub5(2)
	ComplexType Sub127, Sub76, Sub110, Sub86, Sub136, Sub182
	ComplexType Sub92, Sub111, Sub137, Sub87, Sub128, Sub77
	ComplexType Sub149, Sub140, Sub85, Sub82, Sub75, Sub157
	ComplexType Sub126, Sub104, Sub109, Sub106, Sub96, Sub91
	ComplexType Sub132, Sub73, Sub138, Sub89, Sub83, Sub88
	ComplexType Sub141, Sub142, Sub143, Sub67, Sub145, Sub152
	ComplexType Sub153, Sub154, Sub151, Sub94, Sub95, Sub98
	ComplexType Sub99, Sub114, Sub115, Sub116, Sub64, Sub117
	ComplexType Sub100(2), Sub121(2), Sub134(2), Sub135(2)
	ComplexType Sub103(2), Sub130(2), Sub108(2), Sub125(2)
	ComplexType Sub105(2), Sub107(2), Sub102(2), Sub131(2)
	ComplexType Sub112(2), Sub120(2), Sub129(2), Sub133(2)
	ComplexType Sub74(2), Sub146(2), Sub80(2), Sub147(2)
	ComplexType Sub78(2), Sub79(2), Sub159(2), Sub90(2)
	ComplexType Sub155(2), Sub158(2), Sub162(2), Sub84(2)
	ComplexType Sub139(2), Sub81(2), Sub101(2), Sub156(2)
	ComplexType Sub148(2), Sub212(2), Sub122(2), Sub164(2)
	ComplexType Sub163(2), Sub113(2), Sub71(2), Sub18(2)
	ComplexType Sub63(2), Sub29(2), Sub68(2), Sub65(2), Sub30(2)
	ComplexType Sub69(2), Sub14(2,2), Sub12(2,2), Sub37(2,2)
	ComplexType Sub38(2,2), Sub39(2,2), Sub47(2,2), Sub40(2,2)
	ComplexType Sub48(2,2), Sub46(2,2,2), Sub54(2,2,2), Sub233
	ComplexType Sub13(2,2), Sub11(2,2), Sub55, Sub118, Sub144
	ComplexType Sub97, Sub150, Sub93, Sub160, Sub161, Sub119
	ComplexType pave1(2), pave2(2), pave3(Nbb), pave4(Ncc)
	ComplexType pave17(Ncc,2,2), pave22(Ncc,2), pave23
	ComplexType pave24(Ncc,2)
	common /varXs/ Sub8, Sub1, Sub2, Sub7, Sub3, Sub9, Sub4, Sub6
	common /varXs/ Sub10, Sub5, Sub127, Sub76, Sub110, Sub86
	common /varXs/ Sub136, Sub182, Sub92, Sub111, Sub137, Sub87
	common /varXs/ Sub128, Sub77, Sub149, Sub140, Sub85, Sub82
	common /varXs/ Sub75, Sub157, Sub126, Sub104, Sub109, Sub106
	common /varXs/ Sub96, Sub91, Sub132, Sub73, Sub138, Sub89
	common /varXs/ Sub83, Sub88, Sub141, Sub142, Sub143, Sub67
	common /varXs/ Sub145, Sub152, Sub153, Sub154, Sub151, Sub94
	common /varXs/ Sub95, Sub98, Sub99, Sub114, Sub115, Sub116
	common /varXs/ Sub64, Sub117, Sub100, Sub121, Sub134, Sub135
	common /varXs/ Sub103, Sub130, Sub108, Sub125, Sub105
	common /varXs/ Sub107, Sub102, Sub131, Sub112, Sub120
	common /varXs/ Sub129, Sub133, Sub74, Sub146, Sub80, Sub147
	common /varXs/ Sub78, Sub79, Sub159, Sub90, Sub155, Sub158
	common /varXs/ Sub162, Sub84, Sub139, Sub81, Sub101, Sub156
	common /varXs/ Sub148, Sub212, Sub122, Sub164, Sub163
	common /varXs/ Sub113, Sub71, Sub18, Sub63, Sub29, Sub68
	common /varXs/ Sub65, Sub30, Sub69, Sub14, Sub12, Sub37
	common /varXs/ Sub38, Sub39, Sub47, Sub40, Sub48, Sub46
	common /varXs/ Sub54, Sub233, Sub13, Sub11, Sub55, Sub118
	common /varXs/ Sub144, Sub97, Sub150, Sub93, Sub160, Sub161
	common /varXs/ Sub119, pave1, pave2, pave3, pave4, pave17
	common /varXs/ pave22, pave23, pave24

	ComplexType Sub217, Sub57, Sub58, Sub56, Sub59, Sub234(2)
	ComplexType Sub259(2), Sub252(2), Sub215(2), Sub216(2)
	ComplexType Sub253(2), Sub260(2), Sub223(2), Sub225(2)
	ComplexType Sub236(2), Sub218(2,2), Sub219(2,2), Sub184
	ComplexType Sub235(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ndd,2), pave11(Ndd,2), pave12(Nbb,2)
	ComplexType pave13(Nbb,2), pave14(Ncc,2), pave15(Ncc,2)
	ComplexType pave16(Ncc,2), pave18(Ndd,2,2), pave19(Ncc,2)
	ComplexType pave20(Ndd,2,2), pave21(Nbb)
	RealType S, T, U
	common /varXa/ Sub217, Sub57, Sub58, Sub56, Sub59, Sub234
	common /varXa/ Sub259, Sub252, Sub215, Sub216, Sub253
	common /varXa/ Sub260, Sub223, Sub225, Sub236, Sub218
	common /varXa/ Sub219, Sub184, Sub235, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave18, pave19
	common /varXa/ pave20, pave21, S, T, U

	HelType F6, F1, F8, F3, F2, F7, F4, F5
	HelType F18, F15, F12, F20, F9, F16, F17, F37, F21, F10, F11
	HelType F35, F24, F22, F19, F28, F30, F36, F26, F23, F31
	HelType F29, F25, F13, F32, F14, F34, F27, F33, Sub194
	HelType Sub202, Sub186, Sub206, Sub209, Sub192, Sub211
	HelType Sub193, Sub203, Sub204, Sub196, Sub195, Sub189
	HelType Sub188, Sub191, Sub208, Sub185, Sub210
	HelType Sub238(HelDim(2)), Sub258(HelDim(2))
	HelType Sub240(HelDim(2)), Sub257(HelDim(2))
	HelType Sub263(HelDim(2)), Sub198(HelDim(2))
	HelType Sub201(HelDim(2)), Sub205(HelDim(2))
	HelType Sub207(HelDim(2)), Sub124(HelDim(2))
	HelType Sub237(HelDim(2)), Sub183(HelDim(2))
	HelType Sub190(HelDim(2)), Sub197(HelDim(2))
	HelType Sub187(HelDim(2)), Sub165(HelDim(2))
	HelType Sub166(HelDim(2)), Sub242(HelDim(2))
	HelType Sub123(HelDim(2)), Sub230(HelDim(2))
	HelType Sub176(HelDim(2)), Sub226(HelDim(2))
	HelType Sub173(HelDim(2)), Sub172(HelDim(2))
	HelType Sub220(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub221(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub175(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub70(HelDim(2),2)
	HelType Sub167(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub231(HelDim(2),2)
	HelType Sub177(HelDim(2),2), Sub61(HelDim(2),2)
	HelType Sub213(HelDim(2),2), Sub60(HelDim(2),2)
	HelType Sub72(HelDim(2),2), Sub66(HelDim(2),2)
	HelType Sub174(HelDim(2),2), Sub179, Sub181, Sub178, Sub180
	HelType Sub199, Sub200, Sub239(HelDim(2)), Sub241(HelDim(2))
	HelType Sub254(HelDim(2)), Sub256(HelDim(2))
	HelType Sub255(HelDim(2)), Sub244(HelDim(2),2)
	HelType Sub227(HelDim(2),2), Sub214(HelDim(2),2)
	HelType Sub262(HelDim(2)), Sub261(HelDim(2))
	HelType Sub251(HelDim(2),2), Sub243(HelDim(2),2)
	common /varXh/ F6, F1, F8, F3, F2, F7, F4, F5, F18, F15, F12
	common /varXh/ F20, F9, F16, F17, F37, F21, F10, F11, F35
	common /varXh/ F24, F22, F19, F28, F30, F36, F26, F23, F31
	common /varXh/ F29, F25, F13, F32, F14, F34, F27, F33
	common /varXh/ Sub194, Sub202, Sub186, Sub206, Sub209
	common /varXh/ Sub192, Sub211, Sub193, Sub203, Sub204
	common /varXh/ Sub196, Sub195, Sub189, Sub188, Sub191
	common /varXh/ Sub208, Sub185, Sub210, Sub238, Sub258
	common /varXh/ Sub240, Sub257, Sub263, Sub198, Sub201
	common /varXh/ Sub205, Sub207, Sub124, Sub237, Sub183
	common /varXh/ Sub190, Sub197, Sub187, Sub165, Sub166
	common /varXh/ Sub242, Sub123, Sub230, Sub176, Sub226
	common /varXh/ Sub173, Sub172, Sub220, Sub247, Sub249
	common /varXh/ Sub228, Sub221, Sub232, Sub245, Sub248
	common /varXh/ Sub250, Sub62, Sub246, Sub222, Sub175, Sub224
	common /varXh/ Sub229, Sub170, Sub168, Sub70, Sub167, Sub169
	common /varXh/ Sub171, Sub231, Sub177, Sub61, Sub213, Sub60
	common /varXh/ Sub72, Sub66, Sub174, Sub179, Sub181, Sub178
	common /varXh/ Sub180, Sub199, Sub200, Sub239, Sub241
	common /varXh/ Sub254, Sub256, Sub255, Sub244, Sub227
	common /varXh/ Sub214, Sub262, Sub261, Sub251, Sub243

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /udbar_n4x1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
