#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 12:07
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub2, Sub7(2), Sub3(2), Sub9(2)
	ComplexType Sub4(2), Sub6(2), Sub10(2), Sub5(2)
	ComplexType Sub124, Sub72, Sub106, Sub77, Sub133, Sub180
	ComplexType Sub94, Sub107, Sub134, Sub78, Sub125, Sub73
	ComplexType Sub146, Sub137, Sub76, Sub81, Sub71, Sub154
	ComplexType Sub123, Sub100, Sub105, Sub102, Sub90, Sub93
	ComplexType Sub129, Sub69, Sub82, Sub135, Sub80, Sub79
	ComplexType Sub138, Sub139, Sub164, Sub142, Sub149, Sub150
	ComplexType Sub151, Sub148, Sub96, Sub97, Sub87, Sub88
	ComplexType Sub140, Sub110, Sub111, Sub63, Sub112, Sub113
	ComplexType Sub89(2), Sub117(2), Sub131(2), Sub132(2)
	ComplexType Sub99(2), Sub127(2), Sub104(2), Sub122(2)
	ComplexType Sub101(2), Sub103(2), Sub98(2), Sub128(2)
	ComplexType Sub108(2), Sub116(2), Sub126(2), Sub130(2)
	ComplexType Sub70(2), Sub143(2), Sub83(2), Sub144(2)
	ComplexType Sub74(2), Sub75(2), Sub156(2), Sub86(2)
	ComplexType Sub152(2), Sub155(2), Sub159(2), Sub85(2)
	ComplexType Sub136(2), Sub84(2), Sub92(2), Sub153(2)
	ComplexType Sub145(2), Sub210(2), Sub118(2), Sub161(2)
	ComplexType Sub160(2), Sub109(2), Sub168(2), Sub20(2)
	ComplexType Sub62(2), Sub29(2), Sub165(2), Sub64(2)
	ComplexType Sub30(2), Sub166(2), Sub13(2,2), Sub11(2,2)
	ComplexType Sub37(2,2), Sub38(2,2), Sub41(2,2), Sub49(2,2)
	ComplexType Sub42(2,2), Sub50(2,2), Sub48(2,2,2)
	ComplexType Sub56(2,2,2), Sub235, Sub14(2,2), Sub12(2,2)
	ComplexType Sub57, Sub114, Sub141, Sub91, Sub147, Sub95
	ComplexType Sub157, Sub158, Sub115, pave1(2), pave2(2)
	ComplexType pave3(Nbb), pave4(Ncc), pave12(Ncc,2)
	ComplexType pave18(Ncc,2,2), pave21, pave24(Ncc,2)
	common /varXs/ Sub8, Sub1, Sub2, Sub7, Sub3, Sub9, Sub4, Sub6
	common /varXs/ Sub10, Sub5, Sub124, Sub72, Sub106, Sub77
	common /varXs/ Sub133, Sub180, Sub94, Sub107, Sub134, Sub78
	common /varXs/ Sub125, Sub73, Sub146, Sub137, Sub76, Sub81
	common /varXs/ Sub71, Sub154, Sub123, Sub100, Sub105, Sub102
	common /varXs/ Sub90, Sub93, Sub129, Sub69, Sub82, Sub135
	common /varXs/ Sub80, Sub79, Sub138, Sub139, Sub164, Sub142
	common /varXs/ Sub149, Sub150, Sub151, Sub148, Sub96, Sub97
	common /varXs/ Sub87, Sub88, Sub140, Sub110, Sub111, Sub63
	common /varXs/ Sub112, Sub113, Sub89, Sub117, Sub131, Sub132
	common /varXs/ Sub99, Sub127, Sub104, Sub122, Sub101, Sub103
	common /varXs/ Sub98, Sub128, Sub108, Sub116, Sub126, Sub130
	common /varXs/ Sub70, Sub143, Sub83, Sub144, Sub74, Sub75
	common /varXs/ Sub156, Sub86, Sub152, Sub155, Sub159, Sub85
	common /varXs/ Sub136, Sub84, Sub92, Sub153, Sub145, Sub210
	common /varXs/ Sub118, Sub161, Sub160, Sub109, Sub168, Sub20
	common /varXs/ Sub62, Sub29, Sub165, Sub64, Sub30, Sub166
	common /varXs/ Sub13, Sub11, Sub37, Sub38, Sub41, Sub49
	common /varXs/ Sub42, Sub50, Sub48, Sub56, Sub235, Sub14
	common /varXs/ Sub12, Sub57, Sub114, Sub141, Sub91, Sub147
	common /varXs/ Sub95, Sub157, Sub158, Sub115, pave1, pave2
	common /varXs/ pave3, pave4, pave12, pave18, pave21, pave24

	ComplexType Sub219, Sub59, Sub61, Sub58, Sub60, Sub236(2)
	ComplexType Sub261(2), Sub254(2), Sub262(2), Sub217(2)
	ComplexType Sub218(2), Sub255(2), Sub225(2), Sub227(2)
	ComplexType Sub40(2,2), Sub39(2,2), Sub220(2,2), Sub221(2,2)
	ComplexType Sub238(2), Sub199, Sub237(2), pave5(Nbb)
	ComplexType pave6(Ncc,2), pave7(Ncc,2), pave8(Ncc,2)
	ComplexType pave9(Ncc,2), pave10(Ndd,2), pave11(Ndd,2)
	ComplexType pave13(Nbb,2), pave14(Nbb,2), pave15(Ncc,2)
	ComplexType pave16(Ncc,2), pave17(Ncc,2), pave19(Ndd,2,2)
	ComplexType pave20(Ncc,2), pave22(Nbb), pave23(Ndd,2,2)
	RealType S, T, U
	common /varXa/ Sub219, Sub59, Sub61, Sub58, Sub60, Sub236
	common /varXa/ Sub261, Sub254, Sub262, Sub217, Sub218
	common /varXa/ Sub255, Sub225, Sub227, Sub40, Sub39, Sub220
	common /varXa/ Sub221, Sub238, Sub199, Sub237, pave5, pave6
	common /varXa/ pave7, pave8, pave9, pave10, pave11, pave13
	common /varXa/ pave14, pave15, pave16, pave17, pave19
	common /varXa/ pave20, pave22, pave23, S, T, U

	HelType F6, F4, F7, F5, F1, F8, F3, F2
	HelType F19, F15, F12, F21, F9, F16, F17, F37, F22, F10, F11
	HelType F34, F24, F20, F18, F29, F30, F35, F28, F23, F32
	HelType F27, F25, F14, F31, F13, F33, F26, F36, Sub186
	HelType Sub206, Sub191, Sub204, Sub212, Sub194, Sub214
	HelType Sub195, Sub208, Sub207, Sub187, Sub188, Sub196
	HelType Sub197, Sub193, Sub211, Sub190, Sub213
	HelType Sub240(HelDim(2)), Sub260(HelDim(2))
	HelType Sub242(HelDim(2)), Sub259(HelDim(2))
	HelType Sub265(HelDim(2)), Sub203(HelDim(2))
	HelType Sub202(HelDim(2)), Sub205(HelDim(2))
	HelType Sub209(HelDim(2)), Sub239(HelDim(2))
	HelType Sub119(HelDim(2)), Sub185(HelDim(2))
	HelType Sub189(HelDim(2)), Sub198(HelDim(2))
	HelType Sub192(HelDim(2)), Sub162(HelDim(2))
	HelType Sub163(HelDim(2)), Sub244(HelDim(2))
	HelType Sub120(HelDim(2)), Sub232(HelDim(2))
	HelType Sub176(HelDim(2)), Sub228(HelDim(2))
	HelType Sub174(HelDim(2)), Sub175(HelDim(2))
	HelType Sub222(HelDim(2),2), Sub245(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub230(HelDim(2),2)
	HelType Sub223(HelDim(2),2), Sub234(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub231(HelDim(2),2)
	HelType Sub178(HelDim(2),2), Sub68(HelDim(2),2)
	HelType Sub253(HelDim(2),2), Sub224(HelDim(2),2)
	HelType Sub226(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub167(HelDim(2),2)
	HelType Sub121(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub173(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub179(HelDim(2),2), Sub67(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub66(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub65(HelDim(2),2)
	HelType Sub177(HelDim(2),2), Sub182, Sub184, Sub181, Sub183
	HelType Sub200, Sub201, Sub241(HelDim(2)), Sub243(HelDim(2))
	HelType Sub256(HelDim(2)), Sub258(HelDim(2))
	HelType Sub257(HelDim(2)), Sub264(HelDim(2))
	HelType Sub263(HelDim(2)), Sub251(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub216(HelDim(2),2)
	HelType Sub249(HelDim(2),2), Sub250(HelDim(2),2)
	common /varXh/ F6, F4, F7, F5, F1, F8, F3, F2, F19, F15, F12
	common /varXh/ F21, F9, F16, F17, F37, F22, F10, F11, F34
	common /varXh/ F24, F20, F18, F29, F30, F35, F28, F23, F32
	common /varXh/ F27, F25, F14, F31, F13, F33, F26, F36
	common /varXh/ Sub186, Sub206, Sub191, Sub204, Sub212
	common /varXh/ Sub194, Sub214, Sub195, Sub208, Sub207
	common /varXh/ Sub187, Sub188, Sub196, Sub197, Sub193
	common /varXh/ Sub211, Sub190, Sub213, Sub240, Sub260
	common /varXh/ Sub242, Sub259, Sub265, Sub203, Sub202
	common /varXh/ Sub205, Sub209, Sub239, Sub119, Sub185
	common /varXh/ Sub189, Sub198, Sub192, Sub162, Sub163
	common /varXh/ Sub244, Sub120, Sub232, Sub176, Sub228
	common /varXh/ Sub174, Sub175, Sub222, Sub245, Sub247
	common /varXh/ Sub230, Sub223, Sub234, Sub246, Sub248
	common /varXh/ Sub252, Sub231, Sub178, Sub68, Sub253, Sub224
	common /varXh/ Sub226, Sub172, Sub170, Sub167, Sub121
	common /varXh/ Sub171, Sub173, Sub233, Sub179, Sub67, Sub215
	common /varXh/ Sub66, Sub169, Sub65, Sub177, Sub182, Sub184
	common /varXh/ Sub181, Sub183, Sub200, Sub201, Sub241
	common /varXh/ Sub243, Sub256, Sub258, Sub257, Sub264
	common /varXh/ Sub263, Sub251, Sub229, Sub216, Sub249, Sub250

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /udbar_n3x2_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
