#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 6-Jul-2015 12:00
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub1, Sub2, Sub7(2), Sub3(2), Sub9(2)
	ComplexType Sub4(2), Sub6(2), Sub10(2), Sub5(2)
	ComplexType Sub128, Sub73, Sub107, Sub83, Sub137, Sub177
	ComplexType Sub95, Sub108, Sub138, Sub84, Sub129, Sub74
	ComplexType Sub150, Sub141, Sub82, Sub79, Sub72, Sub158
	ComplexType Sub127, Sub101, Sub106, Sub103, Sub91, Sub94
	ComplexType Sub133, Sub70, Sub139, Sub86, Sub80, Sub85
	ComplexType Sub142, Sub143, Sub64, Sub146, Sub153, Sub154
	ComplexType Sub155, Sub152, Sub97, Sub98, Sub88, Sub89
	ComplexType Sub144, Sub111, Sub112, Sub123, Sub113, Sub114
	ComplexType Sub90(2), Sub118(2), Sub135(2), Sub136(2)
	ComplexType Sub100(2), Sub131(2), Sub105(2), Sub126(2)
	ComplexType Sub102(2), Sub104(2), Sub99(2), Sub132(2)
	ComplexType Sub109(2), Sub117(2), Sub130(2), Sub134(2)
	ComplexType Sub71(2), Sub147(2), Sub77(2), Sub148(2)
	ComplexType Sub75(2), Sub76(2), Sub160(2), Sub87(2)
	ComplexType Sub156(2), Sub159(2), Sub163(2), Sub81(2)
	ComplexType Sub140(2), Sub78(2), Sub93(2), Sub157(2)
	ComplexType Sub149(2), Sub213(2), Sub119(2), Sub165(2)
	ComplexType Sub164(2), Sub110(2), Sub68(2), Sub20(2)
	ComplexType Sub122(2), Sub29(2), Sub65(2), Sub124(2)
	ComplexType Sub30(2), Sub66(2), Sub13(2,2), Sub12(2,2)
	ComplexType Sub37(2,2), Sub38(2,2), Sub48(2,2), Sub40(2,2)
	ComplexType Sub49(2,2), Sub41(2,2), Sub47(2,2,2)
	ComplexType Sub55(2,2,2), Sub234, Sub14(2,2), Sub11(2,2)
	ComplexType Sub56, Sub115, Sub145, Sub92, Sub151, Sub96
	ComplexType Sub161, Sub162, Sub116, pave1(2), pave2(2)
	ComplexType pave3(Nbb), pave4(Ncc), pave17(Ncc,2,2), pave20
	ComplexType pave22(Ncc,2), pave24(Ncc,2)
	common /varXs/ Sub8, Sub1, Sub2, Sub7, Sub3, Sub9, Sub4, Sub6
	common /varXs/ Sub10, Sub5, Sub128, Sub73, Sub107, Sub83
	common /varXs/ Sub137, Sub177, Sub95, Sub108, Sub138, Sub84
	common /varXs/ Sub129, Sub74, Sub150, Sub141, Sub82, Sub79
	common /varXs/ Sub72, Sub158, Sub127, Sub101, Sub106, Sub103
	common /varXs/ Sub91, Sub94, Sub133, Sub70, Sub139, Sub86
	common /varXs/ Sub80, Sub85, Sub142, Sub143, Sub64, Sub146
	common /varXs/ Sub153, Sub154, Sub155, Sub152, Sub97, Sub98
	common /varXs/ Sub88, Sub89, Sub144, Sub111, Sub112, Sub123
	common /varXs/ Sub113, Sub114, Sub90, Sub118, Sub135, Sub136
	common /varXs/ Sub100, Sub131, Sub105, Sub126, Sub102
	common /varXs/ Sub104, Sub99, Sub132, Sub109, Sub117, Sub130
	common /varXs/ Sub134, Sub71, Sub147, Sub77, Sub148, Sub75
	common /varXs/ Sub76, Sub160, Sub87, Sub156, Sub159, Sub163
	common /varXs/ Sub81, Sub140, Sub78, Sub93, Sub157, Sub149
	common /varXs/ Sub213, Sub119, Sub165, Sub164, Sub110, Sub68
	common /varXs/ Sub20, Sub122, Sub29, Sub65, Sub124, Sub30
	common /varXs/ Sub66, Sub13, Sub12, Sub37, Sub38, Sub48
	common /varXs/ Sub40, Sub49, Sub41, Sub47, Sub55, Sub234
	common /varXs/ Sub14, Sub11, Sub56, Sub115, Sub145, Sub92
	common /varXs/ Sub151, Sub96, Sub161, Sub162, Sub116, pave1
	common /varXs/ pave2, pave3, pave4, pave17, pave20, pave22
	common /varXs/ pave24

	ComplexType Sub218, Sub58, Sub59, Sub57, Sub60, Sub235(2)
	ComplexType Sub260(2), Sub253(2), Sub216(2), Sub217(2)
	ComplexType Sub254(2), Sub261(2), Sub224(2), Sub226(2)
	ComplexType Sub39(2,2), Sub219(2,2), Sub237(2), Sub220(2,2)
	ComplexType Sub185, Sub236(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ndd,2), pave11(Ndd,2), pave12(Nbb,2)
	ComplexType pave13(Nbb,2), pave14(Ncc,2), pave15(Ncc,2)
	ComplexType pave16(Ncc,2), pave18(Ndd,2,2), pave19(Ncc,2)
	ComplexType pave21(Ndd,2,2), pave23(Nbb)
	RealType S, T, U
	common /varXa/ Sub218, Sub58, Sub59, Sub57, Sub60, Sub235
	common /varXa/ Sub260, Sub253, Sub216, Sub217, Sub254
	common /varXa/ Sub261, Sub224, Sub226, Sub39, Sub219, Sub237
	common /varXa/ Sub220, Sub185, Sub236, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave12, pave13
	common /varXa/ pave14, pave15, pave16, pave18, pave19
	common /varXa/ pave21, pave23, S, T, U

	HelType F6, F1, F7, F2, F3, F8, F5, F4
	HelType F18, F15, F12, F20, F9, F16, F17, F37, F21, F10, F11
	HelType F35, F24, F22, F19, F29, F30, F36, F28, F23, F31
	HelType F27, F25, F14, F32, F13, F34, F26, F33, Sub192
	HelType Sub203, Sub187, Sub207, Sub210, Sub201, Sub212
	HelType Sub202, Sub205, Sub204, Sub193, Sub194, Sub189
	HelType Sub190, Sub200, Sub209, Sub186, Sub211
	HelType Sub239(HelDim(2)), Sub259(HelDim(2))
	HelType Sub241(HelDim(2)), Sub258(HelDim(2))
	HelType Sub264(HelDim(2)), Sub199(HelDim(2))
	HelType Sub198(HelDim(2)), Sub206(HelDim(2))
	HelType Sub208(HelDim(2)), Sub238(HelDim(2))
	HelType Sub120(HelDim(2)), Sub184(HelDim(2))
	HelType Sub191(HelDim(2)), Sub195(HelDim(2))
	HelType Sub188(HelDim(2)), Sub166(HelDim(2))
	HelType Sub167(HelDim(2)), Sub243(HelDim(2))
	HelType Sub121(HelDim(2)), Sub231(HelDim(2))
	HelType Sub183(HelDim(2)), Sub227(HelDim(2))
	HelType Sub174(HelDim(2)), Sub173(HelDim(2))
	HelType Sub221(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub250(HelDim(2),2), Sub229(HelDim(2),2)
	HelType Sub176(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub225(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub246(HelDim(2),2), Sub249(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub63(HelDim(2),2)
	HelType Sub247(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub170(HelDim(2),2)
	HelType Sub168(HelDim(2),2), Sub67(HelDim(2),2)
	HelType Sub172(HelDim(2),2), Sub169(HelDim(2),2)
	HelType Sub171(HelDim(2),2), Sub232(HelDim(2),2)
	HelType Sub178(HelDim(2),2), Sub62(HelDim(2),2)
	HelType Sub214(HelDim(2),2), Sub61(HelDim(2),2)
	HelType Sub69(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub175(HelDim(2),2), Sub180, Sub182, Sub179, Sub181
	HelType Sub196, Sub197, Sub240(HelDim(2)), Sub242(HelDim(2))
	HelType Sub255(HelDim(2)), Sub257(HelDim(2))
	HelType Sub256(HelDim(2)), Sub263(HelDim(2))
	HelType Sub245(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub262(HelDim(2))
	HelType Sub252(HelDim(2),2), Sub244(HelDim(2),2)
	common /varXh/ F6, F1, F7, F2, F3, F8, F5, F4, F18, F15, F12
	common /varXh/ F20, F9, F16, F17, F37, F21, F10, F11, F35
	common /varXh/ F24, F22, F19, F29, F30, F36, F28, F23, F31
	common /varXh/ F27, F25, F14, F32, F13, F34, F26, F33
	common /varXh/ Sub192, Sub203, Sub187, Sub207, Sub210
	common /varXh/ Sub201, Sub212, Sub202, Sub205, Sub204
	common /varXh/ Sub193, Sub194, Sub189, Sub190, Sub200
	common /varXh/ Sub209, Sub186, Sub211, Sub239, Sub259
	common /varXh/ Sub241, Sub258, Sub264, Sub199, Sub198
	common /varXh/ Sub206, Sub208, Sub238, Sub120, Sub184
	common /varXh/ Sub191, Sub195, Sub188, Sub166, Sub167
	common /varXh/ Sub243, Sub121, Sub231, Sub183, Sub227
	common /varXh/ Sub174, Sub173, Sub221, Sub248, Sub250
	common /varXh/ Sub229, Sub176, Sub222, Sub225, Sub233
	common /varXh/ Sub246, Sub249, Sub251, Sub63, Sub247, Sub223
	common /varXh/ Sub230, Sub170, Sub168, Sub67, Sub172, Sub169
	common /varXh/ Sub171, Sub232, Sub178, Sub62, Sub214, Sub61
	common /varXh/ Sub69, Sub125, Sub175, Sub180, Sub182, Sub179
	common /varXh/ Sub181, Sub196, Sub197, Sub240, Sub242
	common /varXh/ Sub255, Sub257, Sub256, Sub263, Sub245
	common /varXh/ Sub228, Sub215, Sub262, Sub252, Sub244

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /udbar_n3x1_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
