#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 7-Oct-2015 14:19
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub1, Sub2
	ComplexType Sub4, Sub5, Sub3, pave1(Nbb), pave2(Ncc)
	common /varXs/ Sub1, Sub2, Sub4, Sub5, Sub3, pave1, pave2

	RealType S, T, U
	common /varXa/ S, T, U

	HelType F1, F2, F3, F4
	common /varXh/ F1, F2, F3, F4

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /udbar_n1x1_test_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
