#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 19-Jun-2015 12:35
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub8, Sub5, Sub6, Sub7(2), Sub1(2), Sub9(2)
	ComplexType Sub2(2), Sub4(2), Sub10(2), Sub3(2)
	ComplexType Sub129, Sub71, Sub105, Sub81, Sub138, Sub177
	ComplexType Sub93, Sub106, Sub139, Sub82, Sub130, Sub72
	ComplexType Sub151, Sub142, Sub80, Sub77, Sub70, Sub159
	ComplexType Sub128, Sub99, Sub104, Sub101, Sub89, Sub92
	ComplexType Sub134, Sub68, Sub140, Sub84, Sub78, Sub83
	ComplexType Sub120, Sub147, Sub154, Sub155, Sub156, Sub153
	ComplexType Sub95, Sub96, Sub86, Sub87, Sub143, Sub145
	ComplexType Sub144, Sub65, Sub109, Sub110, Sub111, Sub112
	ComplexType Sub88(2), Sub116(2), Sub136(2), Sub137(2)
	ComplexType Sub98(2), Sub132(2), Sub103(2), Sub127(2)
	ComplexType Sub102(2), Sub97(2), Sub100(2), Sub133(2)
	ComplexType Sub107(2), Sub115(2), Sub131(2), Sub135(2)
	ComplexType Sub69(2), Sub148(2), Sub75(2), Sub149(2)
	ComplexType Sub73(2), Sub74(2), Sub161(2), Sub85(2)
	ComplexType Sub157(2), Sub160(2), Sub164(2), Sub79(2)
	ComplexType Sub141(2), Sub76(2), Sub91(2), Sub158(2)
	ComplexType Sub150(2), Sub214(2), Sub117(2), Sub166(2)
	ComplexType Sub165(2), Sub108(2), Sub124(2), Sub20(2)
	ComplexType Sub64(2), Sub29(2), Sub121(2), Sub66(2)
	ComplexType Sub30(2), Sub122(2), Sub13(2,2), Sub12(2,2)
	ComplexType Sub37(2,2), Sub38(2,2), Sub40(2,2), Sub48(2,2)
	ComplexType Sub41(2,2), Sub49(2,2), Sub47(2,2,2)
	ComplexType Sub55(2,2,2), Sub234, Sub14(2,2), Sub11(2,2)
	ComplexType Sub56, Sub113, Sub146, Sub90, Sub152, Sub94
	ComplexType Sub162, Sub163, Sub114, pave1(2), pave2(2)
	ComplexType pave3(Nbb), pave4(Ncc), pave12(Ncc,2)
	ComplexType pave13(Ncc,2), pave19(Ncc,2,2), pave22
	common /varXs/ Sub8, Sub5, Sub6, Sub7, Sub1, Sub9, Sub2, Sub4
	common /varXs/ Sub10, Sub3, Sub129, Sub71, Sub105, Sub81
	common /varXs/ Sub138, Sub177, Sub93, Sub106, Sub139, Sub82
	common /varXs/ Sub130, Sub72, Sub151, Sub142, Sub80, Sub77
	common /varXs/ Sub70, Sub159, Sub128, Sub99, Sub104, Sub101
	common /varXs/ Sub89, Sub92, Sub134, Sub68, Sub140, Sub84
	common /varXs/ Sub78, Sub83, Sub120, Sub147, Sub154, Sub155
	common /varXs/ Sub156, Sub153, Sub95, Sub96, Sub86, Sub87
	common /varXs/ Sub143, Sub145, Sub144, Sub65, Sub109, Sub110
	common /varXs/ Sub111, Sub112, Sub88, Sub116, Sub136, Sub137
	common /varXs/ Sub98, Sub132, Sub103, Sub127, Sub102, Sub97
	common /varXs/ Sub100, Sub133, Sub107, Sub115, Sub131
	common /varXs/ Sub135, Sub69, Sub148, Sub75, Sub149, Sub73
	common /varXs/ Sub74, Sub161, Sub85, Sub157, Sub160, Sub164
	common /varXs/ Sub79, Sub141, Sub76, Sub91, Sub158, Sub150
	common /varXs/ Sub214, Sub117, Sub166, Sub165, Sub108
	common /varXs/ Sub124, Sub20, Sub64, Sub29, Sub121, Sub66
	common /varXs/ Sub30, Sub122, Sub13, Sub12, Sub37, Sub38
	common /varXs/ Sub40, Sub48, Sub41, Sub49, Sub47, Sub55
	common /varXs/ Sub234, Sub14, Sub11, Sub56, Sub113, Sub146
	common /varXs/ Sub90, Sub152, Sub94, Sub162, Sub163, Sub114
	common /varXs/ pave1, pave2, pave3, pave4, pave12, pave13
	common /varXs/ pave19, pave22

	ComplexType Sub218, Sub58, Sub59, Sub57, Sub60, Sub235(2)
	ComplexType Sub260(2), Sub254(2), Sub261(2), Sub255(2)
	ComplexType Sub216(2), Sub217(2), Sub224(2), Sub226(2)
	ComplexType Sub39(2,2), Sub219(2,2), Sub237(2), Sub220(2,2)
	ComplexType Sub185, Sub236(2), pave5(Nbb), pave6(Ncc,2)
	ComplexType pave7(Ncc,2), pave8(Ncc,2), pave9(Ncc,2)
	ComplexType pave10(Ndd,2), pave11(Ndd,2), pave14(Nbb,2)
	ComplexType pave15(Nbb,2), pave16(Ncc,2), pave17(Ncc,2)
	ComplexType pave18(Ncc,2), pave20(Ndd,2,2), pave21(Ncc,2)
	ComplexType pave23(Ndd,2,2), pave24(Nbb)
	RealType S, T, U
	common /varXa/ Sub218, Sub58, Sub59, Sub57, Sub60, Sub235
	common /varXa/ Sub260, Sub254, Sub261, Sub255, Sub216
	common /varXa/ Sub217, Sub224, Sub226, Sub39, Sub219, Sub237
	common /varXa/ Sub220, Sub185, Sub236, pave5, pave6, pave7
	common /varXa/ pave8, pave9, pave10, pave11, pave14, pave15
	common /varXa/ pave16, pave17, pave18, pave20, pave21
	common /varXa/ pave23, pave24, S, T, U

	HelType F6, F1, F7, F2, F3, F8, F4, F5
	HelType F19, F16, F12, F21, F9, F17, F15, F37, F22, F11, F10
	HelType F34, F24, F20, F18, F29, F31, F35, F28, F23, F33
	HelType F27, F25, F13, F30, F14, F32, F26, F36, Sub186
	HelType Sub209, Sub198, Sub207, Sub204, Sub191, Sub206
	HelType Sub192, Sub210, Sub211, Sub187, Sub188, Sub193
	HelType Sub194, Sub190, Sub203, Sub197, Sub205
	HelType Sub239(HelDim(2)), Sub259(HelDim(2))
	HelType Sub253(HelDim(2)), Sub241(HelDim(2))
	HelType Sub258(HelDim(2)), Sub264(HelDim(2))
	HelType Sub196(HelDim(2)), Sub202(HelDim(2))
	HelType Sub208(HelDim(2)), Sub212(HelDim(2))
	HelType Sub238(HelDim(2)), Sub118(HelDim(2))
	HelType Sub184(HelDim(2)), Sub189(HelDim(2))
	HelType Sub195(HelDim(2)), Sub199(HelDim(2))
	HelType Sub167(HelDim(2)), Sub168(HelDim(2))
	HelType Sub243(HelDim(2)), Sub119(HelDim(2))
	HelType Sub231(HelDim(2)), Sub178(HelDim(2))
	HelType Sub227(HelDim(2)), Sub176(HelDim(2))
	HelType Sub173(HelDim(2)), Sub221(HelDim(2),2)
	HelType Sub244(HelDim(2),2), Sub246(HelDim(2),2)
	HelType Sub229(HelDim(2),2), Sub222(HelDim(2),2)
	HelType Sub230(HelDim(2),2), Sub233(HelDim(2),2)
	HelType Sub245(HelDim(2),2), Sub247(HelDim(2),2)
	HelType Sub251(HelDim(2),2), Sub63(HelDim(2),2)
	HelType Sub252(HelDim(2),2), Sub223(HelDim(2),2)
	HelType Sub175(HelDim(2),2), Sub225(HelDim(2),2)
	HelType Sub169(HelDim(2),2), Sub171(HelDim(2),2)
	HelType Sub123(HelDim(2),2), Sub126(HelDim(2),2)
	HelType Sub170(HelDim(2),2), Sub172(HelDim(2),2)
	HelType Sub232(HelDim(2),2), Sub179(HelDim(2),2)
	HelType Sub62(HelDim(2),2), Sub213(HelDim(2),2)
	HelType Sub61(HelDim(2),2), Sub125(HelDim(2),2)
	HelType Sub67(HelDim(2),2), Sub174(HelDim(2),2), Sub180
	HelType Sub182, Sub181, Sub183, Sub200, Sub201
	HelType Sub240(HelDim(2)), Sub242(HelDim(2))
	HelType Sub257(HelDim(2)), Sub256(HelDim(2))
	HelType Sub263(HelDim(2)), Sub262(HelDim(2))
	HelType Sub250(HelDim(2),2), Sub228(HelDim(2),2)
	HelType Sub215(HelDim(2),2), Sub248(HelDim(2),2)
	HelType Sub249(HelDim(2),2)
	common /varXh/ F6, F1, F7, F2, F3, F8, F4, F5, F19, F16, F12
	common /varXh/ F21, F9, F17, F15, F37, F22, F11, F10, F34
	common /varXh/ F24, F20, F18, F29, F31, F35, F28, F23, F33
	common /varXh/ F27, F25, F13, F30, F14, F32, F26, F36
	common /varXh/ Sub186, Sub209, Sub198, Sub207, Sub204
	common /varXh/ Sub191, Sub206, Sub192, Sub210, Sub211
	common /varXh/ Sub187, Sub188, Sub193, Sub194, Sub190
	common /varXh/ Sub203, Sub197, Sub205, Sub239, Sub259
	common /varXh/ Sub253, Sub241, Sub258, Sub264, Sub196
	common /varXh/ Sub202, Sub208, Sub212, Sub238, Sub118
	common /varXh/ Sub184, Sub189, Sub195, Sub199, Sub167
	common /varXh/ Sub168, Sub243, Sub119, Sub231, Sub178
	common /varXh/ Sub227, Sub176, Sub173, Sub221, Sub244
	common /varXh/ Sub246, Sub229, Sub222, Sub230, Sub233
	common /varXh/ Sub245, Sub247, Sub251, Sub63, Sub252, Sub223
	common /varXh/ Sub175, Sub225, Sub169, Sub171, Sub123
	common /varXh/ Sub126, Sub170, Sub172, Sub232, Sub179, Sub62
	common /varXh/ Sub213, Sub61, Sub125, Sub67, Sub174, Sub180
	common /varXh/ Sub182, Sub181, Sub183, Sub200, Sub201
	common /varXh/ Sub240, Sub242, Sub257, Sub256, Sub263
	common /varXh/ Sub262, Sub250, Sub228, Sub215, Sub248, Sub249

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6, Sfe7
	common /indices/ Sfe5, Sfe6, Sfe7

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors_udbar_n1x1/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
