#!/bin/bash
PRE="uubar_"
for file in $(find . -type f -iname "uubar_vars.h"); do
    # alle Vorkommnisse von vars.h durch xxbar_vars.h ersetzen usw.
    sed -i -e "s/formfactors/${PRE}formfactors/g" $file
done

PRE="ddbar_"
for file in $(find . -type f -iname "ddbar_vars.h"); do
    # alle Vorkommnisse von vars.h durch xxbar_vars.h ersetzen usw.
    sed -i -e "s/formfactors/${PRE}formfactors/g" $file
done
