#if 0
* renconst.h
* RC declarations
* generated by FormCalc 8.4 on 13-Feb-2015 10:22
#endif

	ComplexType dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1, dZZA1
	ComplexType dZZZ1, dZbarfL1(4,3,3), dZbarfR1(4,3,3)
	ComplexType dZfL1(4,3,3), dZfR1(4,3,3)
	common /renconst/ dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1
	common /renconst/ dZZA1, dZZZ1, dZbarfL1, dZbarfR1, dZfL1
	common /renconst/ dZfR1


