#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 13-Feb-2015 10:22
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub2
	ComplexType Sub5, Sub15, Sub16, Sub4, Sub26, Sub24(2,2)
	ComplexType Sub22(2,2), Sub23(2,2), Sub11(2,2), Sub9, Sub6
	ComplexType Sub8, Sub7, Sub10, Sub31(2), Sub25(2,2), Sub3
	ComplexType pave1(Ncc,2,2), pave2(Ncc,2), pave3(Ncc,2,2)
	ComplexType pave4(Ncc), pave5(Nbb)
	common /varXs/ Sub2, Sub5, Sub15, Sub16, Sub4, Sub26, Sub24
	common /varXs/ Sub22, Sub23, Sub11, Sub9, Sub6, Sub8, Sub7
	common /varXs/ Sub10, Sub31, Sub25, Sub3, pave1, pave2
	common /varXs/ pave3, pave4, pave5

	ComplexType Sub30, Sub27, Sub29, Sub28, Sub14
	RealType S, T, U
	common /varXa/ Sub30, Sub27, Sub29, Sub28, Sub14, S, T, U

	HelType F1, F2, Sub1
	HelType F4, F3, Sub19, Sub18, Sub17, Sub21(HelDim(2))
	HelType Sub13(HelDim(2)), Sub20(HelDim(2),2)
	HelType Sub12(HelDim(2),2)
	common /varXh/ F1, F2, Sub1, F4, F3, Sub19, Sub18, Sub17
	common /varXh/ Sub21, Sub13, Sub20, Sub12

	integer seq(2), Hel(4)
	common /helind/ seq, Hel

	integer Sfe5, Sfe6
	common /indices/ Sfe5, Sfe6

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /uubar_formfactors/ Ctree, Cloop, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
