#!/usr/bin/perl -w
    &CombinePlots;

sub CombinePlots {
    print "------------------------------------------------------- \n";
    print " This is a small script to combine information on       \n";
    print " the same quantities that are plotted for two different \n";
    print " event files. Data of plots which have the same name are\n";
    print " combined in a single plot, and shown in two different  \n";
    print " colors .                                               \n";
    print " All plots contained in the first file are shown.       \n";
    print " Data from the second file are included only            \n";
    print " if a corresponding plot exist in the first file        \n";
    print "------------------------------------------------------- \n";
    print " Date: 22 Dec 2006                                      \n";
    print " Author: Fabio Maltoni                                  \n";
    print "------------------------------------------------------- \n";
#
#file names
#
    print "input first file name:\n";
    $in1=<STDIN>;
    chomp($in1);
    $in1=~ s/\ //g;

    print "input second file name:\n";
    $in2=<STDIN>;
    chomp($in2);
    $in2=~ s/\ //g;

    ($dataname1,$dummy) = split(/\./,$in1);
    ($dataname2,$dummy) = split(/\./,$in2);
    print ":$in1: $dataname1 \n";
    print ":$in2: $dataname2 \n";
    $out="$in1-$in2-combined.top";

    open(IN,$in1); 
    @plots1=<IN>;
    close(IN);

    open(IN,$in2); 
    @plots2=<IN>;
    close(IN);

    open(OUT,">$out");

 #find the beginning and the end of each plot 
    
    $begplot="SET WINDOW Y 2.5 TO 9.";
    $endplot="SET TITLE SIZE -2";
    $tag    ="TITLE TOP";
    $begdata="SET ORDER X Y DY";
    $info   ="INFO-BOX";
    @ini=();
    @fin=();
    @tags=();
    @data=();
    @box =();
    
    $listpos=0;

while($listpos<$#plots1){
    if($plots1[$listpos] =~ /$begplot/) {
    push(@ini,$listpos)}
    # print "inizio: $listpos"

    if($plots1[$listpos] =~ /$tag/)     {
    push(@tags,$plots1[$listpos])}
    #print "  tag: $plots1[$listpos] at $listpos"; 
    
    if($plots1[$listpos] =~ /$begdata/) {
    push(@data,$listpos)} 
    #print "  data start at $listpos"

    if($plots1[$listpos] =~ /$endplot/) {
    push(@fin,$listpos)}
    #print "  fine: $listpos \n"

    if($plots1[$listpos] =~ /$info/) {
    push(@box,$listpos)}
    #print "  box: $listpos \n"

    $listpos++;
}
    $nplots=$#ini;

    print "\n The number of plots is $nplots\n ";



$iplot=0;

#loop over plots
while($iplot<$nplots){

#tag
@temp=split(/"/,$tags[$iplot]);
$tagtofind=$temp[1];
$tagtofind=~ s/\(/\\\(/g;
$tagtofind=~ s/\*/\\\*/g;
$tagtofind=~ s/\)/\\\)/g;

 print "tag to find is :$tagtofind:  => ";

#variables
$listpos=0;
$read=1;
$start=0;
$end=0;
$begdata="SET ORDER X Y DY";
$enddata="HISTO";
$found=0;
$title1box="TITLE 3.8 1.4";
$title2box="TITLE 3.8 1.1";
$titlecount=0;

#start the loop over the second file to find the tag
while($listpos<$#plots2 && $read==1){
    if($plots2[$listpos] =~ /$tagtofind/) {
	 print "    found \n";
	 $found=1;
	 while($read == 1){
	    if($plots2[$listpos] =~ /$begdata/) {$start=$listpos}
	    if($plots2[$listpos] =~ /$enddata/) {$end=$listpos;$read=0}
	    $listpos++}
#     print "start: $start end: $end \n";	
	 while(!($plots2[$listpos] =~/NEW PLOT/)){
	    if($plots2[$listpos] =~ /$title1box/) {$t1box=$plots2[$listpos];$titlecount=$titlecount+1}
	    if($plots2[$listpos] =~ /$title2box/) {$t2box=$plots2[$listpos];$titlecount=$titlecount+1}
	    $listpos++}	        
        ($dummy,$t1box)=split(/"/,$t1box);
        ($dummy,$t2box)=split(/"/,$t2box);
#        print "$t1box\n $t2box\n";
        }
    
    $listpos++;
}#end loop over the second file

if($found==1){

#now I have all the information
@first  =@plots1[$ini[$iplot]..$fin[$iplot]];
@second =@plots2[$start..$end];


# add to @second the new data
shift(@second);
unshift(@second,"(DATA FROM $in2\n");
unshift(@second," TITLE 10 8.5 \"$dataname2\" \n");
unshift(@second," SET ORDER X Y DY\n");

push   (@second," SET COLOR RED\n");
push   (@second," TITLE 10 8 \"$dataname1\" \n");
push   (@second,"(DATA FROM $in1\n");

#find where the box starts in @first
$datastart=$box[$iplot]-$ini[$iplot]+1;
#add color to the box
splice(@first,$datastart,0,"  SET COLOR RED\n");

#find where the data starts in @first
$datastart=$data[$iplot]-$ini[$iplot];
#add them together
splice(@first,$datastart,0,@second);

#add the box info
push(@first,"  set color white \n");
push(@first,"  BOX 7.3 0.5 SIZE 9.5 0.7 \n");
push(@first,"  SET WINDOW Y 0. TO 2. \n");
push(@first,"  SET TITLE SIZE -1.5 \n");
push(@first,"  SET FONT DUPLEX \n");
push(@first,"  TITLE 3.8 0.6 \" $t1box \" \n");
push(@first,"  TITLE 3.8 0.3 \" $t2box \" \n");

#new plot
push(@first,"  NEW PLOT\n\n");

#print out the result to 
foreach $i (@first){
    print OUT $i;
}

 } # if found 
else
{print "not found\n";};


$iplot++;


} #end loop over plots

    
close(OUT);    


 }#end soubroutine CombinePlots

