# ----------------------------------------------------------------------------
#
# Makefile for MODEL directory
# Jan 25 2006
#
# ----------------------------------------------------------------------------


F77           = gfortran
FFLAGS        = -O -ffixed-line-length-132 -cpp
LIBRARY	      = ../libmodel.a
LIBDIR        = ../../../../
MODEL         = couplings.o read_slha.o printout.o hardstop.o

.f.o: ; $(F77) $(FFLAGS) -c $*.f

all: $(LIBDIR)libmodel.a

$(LIBDIR)libmodel.a: $(MODEL) makefile
	ar cru libmodel.a $(MODEL)
	ranlib libmodel.a
	mv libmodel.a  $(LIBDIR)